import { insertFr } from './fr-insert.mjs';

const FR = {
  spielziel_verstehen: {
    t: "Comprendre le but du jeu",
    e: "Avant de penser tactique, tu dois savoir de quoi il retourne dans un échange. Cela paraît simple, et au fond ça l'est : tu gagnes un point quand le speeder atterrit dans le terrain adverse — ou quand ton adversaire commet une faute.\n\nC'est là que réside déjà toute la tactique. Car ces deux façons de marquer un point ne sont pas également réparties. Placer activement le speeder dans le terrain, de sorte que l'adversaire ne puisse plus l'atteindre, est difficile. Mettre l'adversaire dans une situation où il commet la faute est souvent plus facile. Une bonne tactique signifie donc rarement marquer de façon spectaculaire. Elle signifie confier à l'adversaire la tâche la plus difficile.\n\nUne image : imagine l'échange comme une épreuve de force où chacun cherche à déséquilibrer l'autre. Celui qui reste en équilibre et fait vaciller l'autre gagne — pas celui qui frappe le plus fort.\n\nEt c'est là qu'intervient la particularité du Crossminton. Il n'y a pas de filet. Entre les deux terrains se trouve une zone neutre dans laquelle le speeder ne doit pas atterrir. Tu franchis donc une distance, pas une hauteur comme au badminton — et derrière t'attend une cible clairement délimitée. Toute ta réflexion tactique s'oriente ainsi vers cette question : comment amener le speeder proprement au-dessus de la zone dans un terrain que mon adversaire ne peut plus défendre ?\n\nTout le reste — position, longueur, lecture de l'adversaire — n'est que réponse à cette question précise.",
    r: "Repense à ton dernier match, ou fais-y consciemment attention au prochain : combien de tes points as-tu gagnés par un coup gagnant, actif, de ta part — et combien parce que l'adversaire a mis le speeder dehors ou dans la zone ? La plupart des débutants surestiment nettement la première voie. Si tu comptes honnêtement, tu verras à quel point la seconde voie mène plus souvent au point. Garder ce chiffre en tête change ta façon de jouer.",
  },
  zentrale_position: {
    t: "Position centrale et contrôle du terrain",
    e: "Il y a un endroit sur ton terrain qui te fait gagner plus de matchs que n'importe quelle frappe : le milieu. Depuis la position centrale, tes trajets vers tous les coins sont les plus courts. Qui s'y tient arrive partout à temps. Qui se tient ailleurs arrive quelque part trop tard.\n\nC'est pourquoi revenir au milieu après chaque frappe n'est pas de la simple course — c'est une décision tactique. Chaque speeder t'attire hors du milieu, dans un coin, vers l'avant, vers l'arrière. Et à cet instant précis, ton terrain est ouvert. L'art consiste à revenir immédiatement après la frappe, avant que ton adversaire puisse jouer dans le trou.\n\nPense au milieu comme à ta maison. Tu sors chercher une balle et tu reviens aussitôt. Plus tu restes dehors longtemps, plus la porte ouverte derrière toi est large.\n\nCela vaut particulièrement au Crossminton, parce que le terrain est un carré et que ton adversaire peut placer le speeder dans n'importe quel coin. Il n'y a pas de couloir étroit comme au jeu avec filet — le milieu est le seul endroit d'où tu atteins les quatre coins aussi vite.",
    r: "Au prochain match, surveille une seule chose : reviens-tu au milieu après chaque frappe, ou restes-tu là où tu viens de frapper ? La plupart perdent des points parce qu'ils s'arrêtent brièvement après un bon coup pour admirer leur propre balle — et c'est justement là que le speeder file dans le coin ouvert. Un « retour au milieu » conscient après chaque frappe change ton jeu plus que n'importe quelle nouvelle technique.",
  },
  laenge_tiefe: {
    t: "Longueur et profondeur, l'arme la plus simple",
    e: "Tu as une arme qui ne demande aucune frappe puissante et agit pourtant immédiatement : la longueur. Où tu places le speeder décide souvent plus que la force avec laquelle tu le frappes.\n\nLa raison tient à la position centrale. Ton adversaire veut, exactement comme toi, se tenir au milieu de son terrain — de là, il atteint chaque coin le plus vite. Quand tu joues le speeder profond vers l'arrière, tu le forces hors de ce milieu, loin derrière. Maintenant, son avant est ouvert. Le speeder suivant, joué court vers l'avant, devient pour lui une course-poursuite.\n\nC'est le schéma tactique le plus simple au Crossminton : profond, puis court. Tu tires l'adversaire vers l'arrière et places la balle suivante devant lui. Ou l'inverse — tu l'attires vers l'avant puis joues long par-dessus lui. Dans les deux cas, tu gagnes par la distance que ton adversaire doit couvrir — pas par la force.\n\nImagine-toi comme quelqu'un qui fait courir un chien en cercle au bout d'une longue laisse. Tu restes calmement au milieu, ton adversaire court. Plus tu allonges ses trajets, plus il arrive tôt en retard — et un adversaire en retard commet des fautes.\n\nComme il n'y a pas de filet au Crossminton, la balle profonde est particulièrement efficace. Tu n'as pas besoin de trouver de la hauteur pour jouer long — tu portes le speeder plat et loin à travers la zone neutre jusqu'à l'arrière du terrain adverse. Une balle plate et longue est plus difficile à lire et à renvoyer qu'une balle haute.",
    u: {
      titel: "Trouver la profondeur",
      ziel: "Placer le speeder de façon fiable dans l'arrière du terrain adverse.",
      schritte: [
        "Dispose une ligne cible ou une serviette comme repère dans le tiers arrière du terrain adverse.",
        "Depuis ton propre terrain, joue des services et des drives visant derrière ce repère.",
        "Compte combien de speeders sur dix atterrissent derrière le repère.",
        "Progresse sur plusieurs séries — d'abord le coup droit, puis le revers.",
      ],
      selbstkontrolle: "Observe si tu atteins la profondeur avec une frappe plate et portée ou si tu dois lober le speeder haut. La balle plate et longue est l'objectif — elle arrive plus vite et laisse moins de temps à l'adversaire.",
    },
  },
  rueckhand_des_gegners: {
    t: "Lire le revers de l'adversaire",
    e: "Jusqu'ici, il s'agissait de toi — ta position, ta longueur. Maintenant, tu portes pour la première fois le regard sur l'adversaire comme quelqu'un qui a une faiblesse dont tu peux tirer parti. Et la faiblesse la plus fréquente a un nom : le revers.\n\nChez la plupart des joueurs, le côté revers est le moins sûr. Il atteint moins de vitesse, moins de contrôle, moins d'allonge que le coup droit. C'est la règle, pas l'exception — chez toi aussi, comme tu le sais grâce à la partie technique. C'est justement pour cela que jouer le speeder encore et encore sur le côté revers de l'adversaire est l'une des décisions tactiques les plus fiables qui soient.\n\nL'effet est double. D'abord, tu obtiens des retours plus faibles et plus courts, que tu peux mettre plus facilement sous pression. Ensuite — et c'est plus subtil — tu forces l'adversaire à protéger son côté faible. Il se déplace pour couvrir le revers et ouvre ce faisant le côté coup droit. Maintenant, tu as deux cibles au lieu d'une.\n\nTu frappes sans cesse à la même porte. Soit elle cède — le retour faible arrive —, soit l'adversaire se plante devant et laisse l'autre porte sans surveillance.\n\nC'est le cœur du jeu tactique, pas un truc déloyal : repérer la faiblesse de l'autre et la jouer patiemment, au lieu d'espérer le seul grand coup.",
    u: {
      titel: "Toucher le coin revers",
      ziel: "Placer le speeder de façon délibérée et répétée sur le côté faible de l'adversaire.",
      schritte: [
        "Dans le terrain adverse, marque le coin revers (pour un droitier, le coin arrière gauche) avec une serviette.",
        "Depuis différentes positions, joue des speeders visant ce coin — d'abord des services, puis des drives.",
        "Compte tes réussites par dix tentatives.",
        "Augmente la difficulté : alterne une balle dans le coin revers et une balle courte vers l'avant, pour travailler le schéma « fixer le côté faible, puis l'ouvrir ».",
      ],
      selbstkontrolle: "Veille à jouer le coin avec une balle sûre et contrôlée, pas avec un coup gagnant risqué. La tactique du revers vit de la répétition, pas de la seule frappe parfaite.",
    },
  },
  aufschlag_taktisch: {
    t: "Utiliser le service tactiquement",
    e: "Le service est la seule action de tout le jeu que tu contrôles entièrement. Aucun adversaire ne te met sous pression, le speeder repose dans ta seule main, tu choisis le moment, la cible et le rythme. Laisser inutilisée cette occasion offerte serait du gaspillage.\n\nUn service conforme aux règles amène simplement le speeder dans le terrain adverse. Un service tactique l'amène là où il donne du fil à retordre à l'adversaire. Tu as pour cela deux leviers : la cible et la variation.\n\nPour la cible, ce que tu connais déjà s'applique : le côté revers. Un service profond dans le coin revers force l'adversaire, dès le début de l'échange, vers sa frappe la moins sûre. Souvent, tu obtiens un retour faible que tu peux aussitôt mettre sous pression.\n\nPour la variation : ne deviens pas prévisible. Si chacun de tes services arrive pareil — même longueur, même cible, même rythme —, l'adversaire s'y adapte. Mélange services profonds et plus courts, change de cible. À elle seule, l'imprévisibilité provoque des fautes.\n\nLe service est ton premier coup aux échecs. Tu peux le gâcher en jouant toujours le même — ou ouvrir un plan avec lui.",
    r: "Au prochain match, observe tes propres services : arrivent-ils tous pareils, ou varies-tu consciemment ? Et où sers-tu — simplement dans le terrain, ou délibérément sur le côté faible ? La plupart des débutants ne servent que pour lancer l'échange. Qui, au contraire, associe une intention à chaque service gagne des points avant même que l'échange ait vraiment commencé.",
  },
  fehler_vermeiden: {
    t: "Éviter les fautes : la tactique sous-estimée",
    e: "Pour finir, peut-être l'idée tactique la plus importante — et celle que la plupart des débutants ont le plus de mal à croire : à ton niveau, tu ne gagnes pas la plupart des points parce que tu frappes fort. Tu les gagnes parce que ton adversaire met le speeder dehors ou dans la zone. Et inversement, tu perds la plupart des points par tes propres fautes.\n\nCela paraît décourageant, mais c'est une bonne nouvelle. Car ton taux de fautes, tu peux le baisser tout de suite — sans meilleure technique. Il te suffit de choisir plus sûrement ce que tu joues.\n\nJouer sûr signifie : placer le speeder avec une marge vers l'intérieur, pas sur la ligne. Choisir l'angle qui te laisse de la marge, pas le spectaculaire. Mieux vaut renvoyer une balle de plus que tenter un coup gagnant risqué qui finit dehors trois fois sur quatre. Chaque balle que tu renvoies sûrement donne à ton adversaire l'occasion de commettre sa faute.\n\nImagine que vous portez tous les deux un seau d'eau à travers un parcours. Gagne celui qui en renverse le moins — pas celui qui court le plus vite. L'échange est exactement cela — une compétition pour savoir qui perd le premier sa patience ou son contrôle.\n\nCela ne veut pas dire qu'il ne faut jamais attaquer. Cela veut dire que la sécurité est ton réglage par défaut et l'attaque l'exception, pour laquelle se présente une occasion vraiment favorable. Qui inverse cela — l'attaque comme règle, la sécurité comme exception — offre le plus de points au niveau débutant.",
    r: "Au prochain match, compte consciemment tes propres fautes — chaque speeder que tu mets dehors ou dans la zone. Compare ce chiffre au nombre de tes vrais coups gagnants. Chez la plupart des débutants, les fautes personnelles dépassent nettement les coups gagnants. Connaître ce seul chiffre est le moyen le plus rapide de gagner plus de matchs — avant même toute amélioration technique.",
  },
  aufschlag_taktisch_delta_bad: {
    t: "Utiliser le service tactiquement — pour les joueurs venant du badminton",
    e: "Tu apportes un répertoire de services réfléchi — mais une grande partie vise quelque chose qui n'existe pas ici. Au badminton, la tactique de service tourne autour du filet : le service court tenu bas juste au-dessus du bord, tout le jeu autour de la troisième balle. Au Crossminton, cela disparaît. Pas de filet, pas d'avant-terrain court — entre vous se trouve la zone neutre, et ton service doit la franchir jusqu'à une cible profonde.\n\nTa représentation tactique se déplace ainsi de la hauteur vers la profondeur. Non plus « juste au-dessus et court », mais « plat, loin et ciblé ». Le service court, ton arme fine au badminton, perd ici son rôle. À sa place vient la variation par la longueur et la cible.\n\nCe que tu peux garder : jouer le revers. Servir sur le côté faible de l'adversaire fonctionne ici comme là-bas — seulement profond dans le coin revers au lieu de court au bord du filet.\n\nUn petit test : si tu remarques que tu poses le speeder court et haut, comme s'il fallait franchir un bord, tu joues encore au badminton. L'objectif est le service plat et long qui franchit la zone et arrive profond.",
  },
};

insertFr('data/bausteine.beginner-taktik.json', FR);
