import { insertFr } from './fr-insert.mjs';

const FR = {
  was_gutes_vermitteln_ausmacht: {
    t: "Ce qui fait un bon enseignement",
    e: "Qui enseigne le Crossminton fait face à une autre tâche que qui le joue. Tu n'as pas besoin de savoir toi-même exécuter la frappe parfaite — tu dois faire en sorte que d'autres la trouvent. C'est un métier à part, et il s'apprend.\n\nL'attitude de base la plus importante est simple : pense à partir du jeu. Les gens viennent au Crossminton parce qu'ils veulent jouer, non parce qu'ils veulent décomposer des enchaînements de mouvements. Qui laisse un groupe s'exercer une demi-heure à des frappes isolées avant le premier échange perd justement ce qui a amené les gens. Un bon enseignement met les gens tôt dans le jeu et affine la technique à partir de là.\n\nIl en découle une idée directrice qui traverse tous les modules suivants : d'abord l'expérience, ensuite l'explication. Laisse les apprenants vivre une situation avant de la leur expliquer. Un débutant qui a remarqué qu'il n'atteint pas le speeder comprend le jeu de jambes autrement que celui à qui tu l'expliques au préalable.\n\nVois-toi comme un jardinier, non comme un conférencier devant le tableau. Tu crées les conditions dans lesquelles quelque chose pousse — les bonnes formes de jeu, les tâches adaptées —, et tu interviens de façon ciblée là où c'est nécessaire. C'est la capacité elle-même qui doit pousser.\n\nLes quatre modules suivants montrent les quatre métiers de l'enseignement : rendre un contenu accessible, repérer et corriger les erreurs, construire des exercices, encadrer un groupe.",
    r: "Pense à un entraîneur ou un enseignant avec qui tu as toi-même bien appris quelque chose — dans quelque sport ou matière que ce soit. Qu'a fait concrètement cette personne ? Expliquait-elle beaucoup, ou te laissait-elle essayer tôt par toi-même ? Comment gérait-elle les erreurs ? Note deux ou trois choses que tu aimerais reprendre. Ta propre histoire d'apprentissage est la meilleure première source pour ton style d'enseignement."
  },
  inhalt_zugaenglich_machen: {
    t: "Rendre un contenu accessible",
    e: "Un débutant ne peut pas faire attention à dix choses à la fois. Ta première tâche dans l'enseignement est donc de rendre le contenu plus petit qu'il n'est — de le réduire à son noyau.\n\nChaque technique a un point nodal où elle tient ou s'effondre. Pour la prise, c'est la main détendue ; pour le service, le point de frappe sous la main de frappe ; pour le drive, le point de frappe devant le corps. Quand tu trouves ce noyau unique et que tu laisses d'abord tout le reste de côté, tu donnes à l'apprenant quelque chose qu'il peut effectivement mettre en œuvre. Dix conseils corrects d'un coup valent moins que le seul qui compte.\n\nTrois voies mènent à la compréhension, et elles agissent le mieux ensemble. Montrer : exécute le mouvement devant eux, lentement et sous un angle d'où le noyau devient visible. Dire : donne une consigne brève et claire — ce qu'il faut faire, non ce qu'il faut éviter. Et donner une image : une bonne analogie atteint plus que dix termes techniques. « Serre la main à la raquette » s'ancre aussitôt ; « tourne la main dans une position neutre légèrement pronée » embrouille.\n\nUne image à ce sujet, que tu peux utiliser toi-même : une image par chose. Quand tu remarques qu'il te faut trois comparaisons pour expliquer un mouvement, c'est que tu ne l'as pas encore réduit à son noyau.\n\nJustement pour ceux qui viennent d'autres sports de raquette : rattache-toi à ce qu'ils savent déjà, et ne nomme que la seule chose qui est différente. Cela épargne bien des efforts aux deux parties.",
    r: "Choisis une technique du domaine débutant — la prise, le service ou le coup droit. Formule pour elle trois choses : l'unique noyau du mouvement en une phrase, une consigne d'action brève, et une image ou une analogie. Vérifie ensuite de façon autocritique : le noyau pourrait-il être encore davantage réduit ? Cet exercice — la réduction à l'essentiel — est la compétence fondamentale de tout enseignement."
  },
  fehler_erkennen_korrigieren: {
    t: "Repérer et corriger les erreurs",
    e: "Corriger, c'est plus que nommer une erreur. L'art véritable réside dans le fait de trouver la cause derrière l'erreur visible — car les deux sont rarement la même chose.\n\nUn exemple : le speeder d'un apprenant atterrit toujours trop court. C'est le symptôme. La cause peut se trouver tout ailleurs — dans la prise crispée, dans le point de frappe trop tardif, dans un transfert de poids absent, dans une mauvaise position de départ. Qui se contente de soigner le symptôme (« continue à jouer ») ne change rien. Qui touche la cause résout le problème d'un seul conseil.\n\nC'est pourquoi un bon correctif se décompose en trois étapes. Premièrement voir : regarde de façon ciblée l'endroit où le mouvement naît, non seulement son résultat. Deuxièmement conclure : demande-toi quelle cause explique le plus probablement le tableau d'erreur observé. Troisièmement énoncer : donne exactement un conseil qui s'adresse à la cause — formulé positivement, comme une action que l'apprenant peut exécuter. « Frappe le speeder plus en avant » mène plus loin que « tu frappes trop tard ».\n\nSois un diagnosticien, non un commentateur. Un commentateur décrit ce qui a mal tourné. Un diagnosticien trouve pourquoi — et seul cela peut être traité.\n\nUn principe important pour finir : corrige avec parcimonie. Une correction qui porte vaut plus que cinq qui dépassent l'apprenant. Et donne du temps au mouvement — tout changement ne prend pas dès le premier essai.",
    r: "Prends un tableau d'erreur fréquent — par exemple « le service part toujours dehors » ou « le revers arrive trop court ». Rassemble pour ce seul symptôme au moins trois causes possibles à divers endroits du mouvement. Réfléchis ensuite, pour chaque cause, à un conseil de correction positif et orienté vers l'action. Cet exercice — conclure d'un symptôme à plusieurs causes possibles — est le cœur du correctif."
  },
  uebungen_aufbauen: {
    t: "Construire des exercices avec méthode",
    e: "Un bon exercice ne naît pas par hasard. Il a un but clair, la difficulté adaptée et une place dans un ordre sensé. Ce module montre comment construire des exercices de sorte qu'ils soient effectivement efficaces pour l'apprentissage.\n\nD'abord un aiguillage fondamental. Il y a deux voies pour construire une capacité. L'une est la série d'exercices : tu décomposes une technique et la fais travailler isolément, du simple au composé, jusqu'à ce que le jeu tienne à la fin. Cela donne de l'assurance et emmène aussi les apprenants plus faibles — mais coûte l'attrait du jeu, parce qu'on ne joue pas pendant longtemps. L'autre est la série de jeux : tu commences par une forme de jeu simplifiée et tu développes la technique à partir du jeu. Cela préserve la motivation, mais dépasse certains débutants. En pratique, tu mêles les deux — joue tôt, et travaille de façon ciblée ce qui coince dans le jeu.\n\nUn outil efficace pour cela, ce sont les règles modifiées. Avec une règle de provocation, tu forces une action précise : « Un point ne compte que si le speeder a été joué dans la zone arrière » — et déjà tout le monde travaille la longueur, sans que tu aies à l'expliquer individuellement. Avec une règle de continuité, tu maintiens le jeu en cours et donc la concentration élevée, au lieu d'interrompre après chaque erreur.\n\nTu règles la difficulté par quelques molettes : le tempo, l'exigence de précision, la pression temporelle, la taille du terrain. Un exercice trop facile ennuie ; un trop difficile frustre. Il est bien dosé quand il réussit, mais non sans effort.\n\nConstruis un escalier, non un mur. Chaque marche est juste accessible depuis la précédente. Qui se tient devant un mur ne grimpe pas — il abandonne.",
    r: "Conçois une petite suite d'exercices de trois étapes sur un thème débutant de ton choix — par exemple le service ou la longueur. Commence simplement, augmente à chaque étape exactement une exigence, et termine par une forme de jeu où figure ce qui a été travaillé. Intègre au moins une fois une règle de provocation. Vérifie ensuite : chaque marche est-elle juste accessible depuis la précédente ? Cette capacité — construire une progression solide — est la pièce maîtresse de la conception de l'entraînement."
  },
  gruppe_fuehren: {
    t: "Encadrer un groupe",
    e: "Dès que tu travailles avec plus d'une personne, l'organisation s'ajoute à l'enseignement. Encadrer un groupe, c'est former une séance sensée à partir de personnes différentes, d'un espace limité et d'un temps limité.\n\nQuatre choses, tu les rassembles pour cela. Premièrement les niveaux différents. Dans presque chaque groupe, des débutants côtoient des plus avancés. Au lieu de faire faire la même chose à tous, tu donnes le même exercice avec des exigences différentes — l'un joue vers une grande cible, l'autre vers une petite. Ainsi personne n'est sous-sollicité et personne n'est distancé.\n\nDeuxièmement la dramaturgie de la séance. Une bonne séance d'entraînement a un arc : un échauffement qui prépare et donne envie ; un corps de séance avec un axe clair ; un retour au calme, souvent un jeu libre qui applique l'axe. Qui planifie sans cet arc ne fait qu'aligner des exercices.\n\nTroisièmement l'espace et le matériel. Au Crossminton, c'est commode — sans filet et avec quelques marquages, tu montes vite plusieurs terrains. Fais en sorte que tous soient en mouvement et que personne n'attende longtemps. Les longues files d'attente sont l'erreur la plus fréquente et le moyen le plus sûr de perdre la motivation.\n\nQuatrièmement la motivation et la sécurité. Garde l'ambiance positive et les exigences atteignables, veille à un espace suffisant entre les terrains et à un maniement sûr de l'engin. Les gens apprennent mieux quand ils se sentent en sécurité et prennent du plaisir.\n\nTu es l'hôte, non le surveillant. Un bon hôte fait en sorte que tous soient occupés, se sentent bien et, à la fin, reviennent volontiers.",
    r: "Planifie une courte séance d'entraînement pour un groupe mixte : esquisse un échauffement, un corps de séance avec un seul axe et un retour au calme. Pour le corps de séance, réfléchis à la façon de rendre le même exercice différemment exigeant pour les plus forts et les plus faibles, et à la façon de répartir l'espace pour que personne n'attende longtemps. Cette planification à l'avance est la différence entre une séance encadrée et un simple enchaînement."
  }
};

insertFr('data/bausteine.trainer-trainingsgestaltung.json', FR);
