// Ring 0 (pl): füllt data/labels/pl.json mit polnischen UI-Labels.
// Liest data/labels/de.json für die STRUKTUR, ersetzt jedes Blatt durch den
// polnischen Wert aus PL (flach nach de-Pfad gekeyed). Wirft, wenn ein Blatt
// fehlt — so ist Vollständigkeit (515/515) garantiert. de/en/fr bleiben unberührt.
// Terminologie: docs/glossar-pl.md.
import { readFileSync, writeFileSync } from 'node:fs';

const de = JSON.parse(readFileSync('data/labels/de.json', 'utf8'));

const PL = {
  // ---- ui (254) ----
  'ui.app_titel': 'Podręcznik Crossmintona',
  'ui.hero_untertitel': 'Podręcznik nauki i treningu',
  'ui.hero_themen': 'Technika · Trening · Teoria · Zasady · Sprzęt',
  'ui.profil_intro': 'Twoje dane, twoje postępy i twoje ustawienia — do zmiany w każdej chwili.',
  'ui.weiter': 'Dalej',
  'ui.zurueck': 'Wstecz',
  'ui.ueberspringen': 'Pomiń',
  'ui.fertig': 'Gotowe',
  'ui.abbrechen': 'Anuluj',
  'ui.aendern': 'Zmień',
  'ui.uebernehmen': 'Zastosuj',
  'ui.entfernen': 'Usuń',
  'ui.schliessen': 'Zamknij',
  'ui.zur_liste': 'Do listy',
  'ui.baustein_navigation': 'Nawigacja modułów',
  'ui.nav_lernen': 'Nauka',
  'ui.nav_training': 'Trening',
  'ui.nav_regeln': 'Zasady',
  'ui.nav_ueber': 'O aplikacji',
  'ui.nav_mitmachen': 'Współtwórz',
  'ui.nav_profil': 'Profil',
  'ui.nav_mehr': 'Więcej',
  'ui.nav_suche': 'Szukaj',
  'ui.footer_impressum': 'Nota prawna',
  'ui.footer_datenschutz': 'Prywatność',
  'ui.menue': 'Menu',
  'ui.menue_schliessen': 'Zamknij menu',
  'ui.onboarding_titel': 'Zanim zaczniesz',
  'ui.onboarding_intro': 'Trzy krótkie informacje zestawią odpowiednie dla ciebie treści. Wszystko można później zmienić w profilu.',
  'ui.onboarding_schritt': 'Krok {a} z {b}',
  'ui.wk_titel': 'Naucz się crossmintona — uderzenie po uderzeniu.',
  'ui.wk_untertitel': 'Małe moduły, jasna technika, twoje tempo. Działa w całości w przeglądarce — bez logowania, twoje postępy zostają na twoim urządzeniu.',
  'ui.wk_einstieg': 'Zanim zaczniesz: wybierz swój start',
  'ui.wk_handbuch_titel': 'Prosto do podręcznika',
  'ui.wk_handbuch_text': 'Przeglądaj od razu wszystkie {n} rozdziały — bez podawania danych, bez okrężnych dróg.',
  'ui.wk_gefuehrt_titel': 'Na jakim etapie gry jesteś?',
  'ui.wk_gefuehrt_text': 'Trzy krótkie pytania, duży efekt: podręcznik układa się według twojego poziomu — a osoby przechodzące z innych sportów rakietowych otrzymują specjalnie dopasowane objaśnienia.',
  'ui.ohne_angaben': 'Kontynuuj bez podawania danych — prosto do rozdziałów',
  'ui.stufe_waehlen': 'Wybierz poziom',
  'ui.stufe_fehlt': 'Nie wybrano jeszcze poziomu — bez niego nie ma prowadzonej ścieżki. Wybór zajmuje minutę i można go zmienić w każdej chwili.',
  'ui.onboarding_einladung': 'Trzy krótkie pytania ułożą dla ciebie prowadzoną ścieżkę — możesz to nadrobić w każdej chwili.',
  'ui.onboarding_starten': 'Odpowiedz na pytania',
  'ui.onboarding': 'Wprowadzenie',
  'ui.kapitel_entdecken': 'Odkryj rozdziały',
  'ui.ansehen': 'Zobacz',
  'ui.regeln_kachel': 'Oficjalne zasady gry i regulamin turniejowy — do sprawdzenia.',
  'ui.keine_angabe': 'Bez odpowiedzi',
  'ui.frage_stufe': 'Na jakim etapie gry jesteś?',
  'ui.frage_trainer': 'Uczysz się także po to, aby uczyć innych?',
  'ui.anker_beginner': 'Dopiero zaczynasz z crossmintonem albo masz za sobą kilka pierwszych gier. Speeder raz leci przez pole, raz obok — wiele wciąż wydaje się obce. Chcesz nauczyć się podstaw od zera.',
  'ui.anker_fortgeschritten': 'Potrafisz niezawodnie utrzymać wymianę w grze. Forhend, bekhend i serwis masz w zasadzie opanowane, a po polu poruszasz się sensownie. Teraz chcesz grać pewniej i bardziej różnorodnie.',
  'ui.anker_experte': 'Aktywnie kształtujesz długie wymiany i celowo naciskasz przeciwnika. Świadomie zmieniasz tempo, długość i umiejscowienie oraz czytasz grę. Szukasz szlifu i taktycznej głębi.',
  'ui.trainer_ja': 'Tak — odblokuj perspektywę trenera',
  'ui.anker_trainer': 'Chcesz nie tylko sam grać w crossmintona, ale też uczyć innych — rozpoznawać błędy, korygować je, budować ćwiczenia i jednostki treningowe. Tę perspektywę odblokowujesz dodatkowo, obok swojego poziomu gry.',
  'ui.trainer_nein': 'Nie — uczę się dla własnej gry',
  'ui.frage_herkunft': 'Czy masz doświadczenie z innego sportu rakietowego?',
  'ui.herkunft_hinweis': 'Do wyboru są sporty, dla których istnieją dopasowane treści. Przy pasującym pochodzeniu pojedyncze objaśnienia zostaną dla ciebie wymienione.',
  'ui.herkunft_keine': 'Brak wcześniejszego doświadczenia',
  'ui.frage_ziel': 'Czy chcesz nad czymś konkretnym popracować?',
  'ui.ziel_hinweis': 'Wybierz jeden lub więcej celów — zostaną zapisane, a w ścieżce celu możesz za nimi podążać. To, których ścieżek używasz, pozostaje od tego niezależne.',
  'ui.vormarkieren_titel': 'Już opanowane?',
  'ui.vormarkieren_text': 'Dla tych modułów przy twoim pochodzeniu nie jest potrzebne żadne dopasowanie. Jeśli masz je już pewnie opanowane, możesz je z góry oznaczyć jako zrobione.',
  'ui.vormarkieren_leer': 'Możesz nic nie wybierać — to całkowicie w porządku. Wstępnego oznaczenia dokonasz w profilu w każdej chwili.',
  'ui.pfad_kompetenz': 'Ścieżka kompetencji',
  'ui.pfad_kompetenz_text': 'Prowadzona droga przez twój poziom — moduł po module w sensownej kolejności.',
  'ui.pfad_themen': 'Ścieżka tematyczna',
  'ui.pfad_themen_text': 'Swobodne przeglądanie według obszaru tematycznego. Kolejność jest proponowana, ty decydujesz.',
  'ui.pfad_spielform': 'Gra podwójna',
  'ui.pfad_spielform_text': 'Cała gra podwójna jako temat przekrojowy — w poprzek taktyki, przygotowania fizycznego i mentalnego.',
  'ui.pfad_umgebung': 'Gra na zewnątrz',
  'ui.pfad_umgebung_text': 'Crossminton na świeżym powietrzu — wiatr, słońce, wilgoć, upał i różne podłoża.',
  'ui.umgebung_wetter': 'Według pogody',
  'ui.umgebung_boden': 'Według podłoża',
  'ui.umgebung_alle': 'Cała seria plenerowa',
  'ui.pfad_individual': 'Ścieżka celu',
  'ui.pfad_individual_text': 'Tylko te moduły, które wspierają twój wybrany cel.',
  'ui.pfad_training': 'Ścieżka treningowa',
  'ui.pfad_training_text': 'Gotowe jednostki złożone z ćwiczeń — do natychmiastowego startu.',
  'ui.plan_titel': 'Plan treningowy',
  'ui.plan_kachel_text': 'Ułóż sobie z jednostek plan tygodniowy — z możliwością dostosowania, jako PDF lub kalendarz.',
  'ui.plan_erstellen': 'Utwórz plan',
  'ui.plan_intro': 'Wybierz zakres i punkt startu — aplikacja ułoży dla ciebie plan tygodniowy z pasujących jednostek, który potem możesz dostosować.',
  'ui.plan_wochen': 'Tygodnie',
  'ui.plan_pro_woche': 'Jednostki na tydzień',
  'ui.plan_start': 'Data startu',
  'ui.plan_spielform': 'Forma gry',
  'ui.plan_spielform_alle': 'Wszystkie',
  'ui.plan_generieren': 'Wygeneruj plan',
  'ui.plan_woche': 'Tydzień {n}',
  'ui.plan_umfang': '{wochen} tygodni · {n} jednostek',
  'ui.plan_pdf': 'Jako PDF',
  'ui.plan_ical': 'Kalendarz (.ics)',
  'ui.plan_neu': 'Odrzuć i od nowa',
  'ui.plan_tauschen': 'Wymień jednostkę',
  'ui.plan_entfernen': 'Usuń',
  'ui.plan_leer': 'Brak jednostek w planie — dostosuj zakres lub wygeneruj od nowa.',
  'ui.plan_keine_einheiten': 'Dla twojego poziomu nie ma jeszcze jednostek do zaplanowania. Wybierz poziom w profilu.',
  'ui.pfade': 'Ścieżki',
  'ui.n_bausteine': '{n} modułów',
  'ui.n_einheiten': '{n} jednostek',
  'ui.weiterlernen': 'Ucz się dalej',
  'ui.station_x_von_y': 'Etap {a} z {b}',
  'ui.pfad_abgeschlossen_kurz': 'Ścieżka ukończona',
  'ui.vorgeschlagene_reihenfolge': 'Proponowana kolejność — do swobodnego wyboru.',
  'ui.empfohlen_vorher': 'Zalecane wcześniej:',
  'ui.ausserhalb_auswahl': 'Poza twoim wyborem celów:',
  'ui.kann_ich_schon': 'Już to umiem — oznacz jako zrobione',
  'ui.ziel_waehlen': 'Wybierz cel',
  'ui.ziel_aktuell': 'Twoje cele',
  'ui.ziel_keins': 'Nie wybrano celów',
  'ui.ziel_entfernen': 'Usuń cele',
  'ui.ziel_aendern': 'Zmień cele',
  'ui.status_offen': 'do zrobienia',
  'ui.status_teilweise': 'częściowo zrobione',
  'ui.status_absolviert': 'ukończone',
  'ui.nicht_gefunden': 'Tej treści (już) nie ma.',
  'ui.spielziele_gruppe': 'Cele gry',
  'ui.vermittlungsziele_gruppe': 'Cele dydaktyczne',
  'ui.erklaerteil': 'Objaśnienie',
  'ui.uebungsteil': 'Ćwiczenie',
  'ui.reflexionsaufgabe': 'Zadanie refleksyjne',
  'ui.als_mitgenommen': 'Odhacz jako przyswojone',
  'ui.mitgenommen': 'Przyswojone',
  'ui.trainer_layer': 'Warstwa trenera: typowe błędy',
  'ui.trainer_layer_hinweis': 'Widok diagnostyczny dla trenera — widoczny tylko w perspektywie trenera.',
  'ui.fb_symptom': 'Objaw',
  'ui.fb_ursache': 'Przyczyna',
  'ui.fb_korrektur': 'Korekta i wskazówka',
  'ui.als_gelesen': 'Odhacz jako przeczytane',
  'ui.gelesen': 'Przeczytane',
  'ui.als_erledigt': 'Odhacz jako zrobione',
  'ui.erledigt': 'Zrobione',
  'ui.zuruecknehmen': 'Dotknij, aby cofnąć',
  'ui.baustein_abgeschlossen': 'Moduł ukończony.',
  'ui.weiter_zu': 'Dalej do: {titel}',
  'ui.delta_hinweis': 'Dopasowane dla osób przechodzących z {herkunft}.',
  'ui.delta_uebungsteil_gilt': 'Ćwiczenie jest standardowe — obowiązuje dla wszystkich bez zmian.',
  'ui.lektuere_empfehlung': 'Pasujące wskazówki:',
  'ui.hinweis_suffix': 'Wskazówka',
  'ui.grafik_folgt': 'Grafika w przygotowaniu',
  'ui.einordnung': 'Klasyfikacja',
  'ui.meta_spielziele': 'Cele gry',
  'ui.meta_vermittlungsziele': 'Cele dydaktyczne',
  'ui.meta_untergrund': 'Podłoże',
  'ui.meta_witterung': 'Pogoda',
  'ui.meta_transfer': 'Pochodzenie (transfer)',
  'ui.meta_voraussetzungen': 'Wymagania wstępne',
  'ui.teil_1': 'Część 1',
  'ui.teil_2': 'Część 2',
  'ui.ue_ziel': 'Cel',
  'ui.ue_schritte': 'Jak to zrobić',
  'ui.ue_steigerung': 'Progresja',
  'ui.ue_selbstkontrolle': 'Samokontrola',
  'ui.ue_abschluss': 'Zakończenie',
  'ui.ue_naechste_stufe': 'Następny poziom',
  'ui.meilenstein_titel': 'Kamień milowy osiągnięty',
  'ui.meilenstein_kompetenz': '{pfad} na twoim poziomie — ukończona. To wypracowana zmiana stanu, nie przypadek.',
  'ui.meilenstein_individual': 'Masz ukończone wszystkie moduły dla swojego celu.',
  'ui.meilenstein_weiter': 'Wszystko inne znajdziesz w pozostałych ścieżkach — albo w treningu.',
  'ui.einheit_starten': 'Rozpocznij jednostkę',
  'ui.einheit_fortsetzen': 'Dalej',
  'ui.uebung_x_von_y': 'Ćwiczenie {a} z {b}',
  'ui.phase_erwaermung': 'Rozgrzewka',
  'ui.phase_hauptteil': 'Część główna',
  'ui.phase_ausklang': 'Wyciszenie',
  'ui.einheit_schwerpunkt': 'Nacisk',
  'ui.uebung_erledigt_weiter': 'Zrobione — dalej',
  'ui.einheit_abschliessen': 'Zakończ jednostkę',
  'ui.einheit_abgeschlossen': 'Jednostka ukończona.',
  'ui.einheit_abbrechen_hinweis': 'Przerwać można w każdej chwili — licznik pozostaje nienaruszony.',
  'ui.kontinuitaet_stand': 'Łącznie {n} ukończonych jednostek.',
  'ui.kontinuitaet_erste': 'Twoja pierwsza ukończona jednostka.',
  'ui.mal_absolviert': 'Ukończono {n} razy',
  'ui.noch_nicht_absolviert': 'Jeszcze nie ukończono',
  'ui.uebungen_anzahl': '{n} ćwiczeń',
  'ui.zum_baustein': 'Do modułu',
  'ui.kontinuitaet': 'Regularność',
  'ui.kontinuitaet_text': 'Ukończone jednostki się sumują. Przerwy niczego nie unieważniają.',
  'ui.regeln_titel': 'Zasady gry',
  'ui.regeln_intro': 'Oficjalne zasady gry w crossmintona — każda reguła wiernie oddana i poniżej wyjaśniona prostym językiem. To kompendium, nie ścieżka nauki: tu nie ma nic do odhaczenia.',
  'ui.regeln_quelle': 'Źródło',
  'ui.regeln_stand': 'Stan na',
  'ui.regeln_quelle_link': 'Przepisy jako PDF (crossminton.de)',
  'ui.regel_label': 'Reguła',
  'ui.regel_bedeutung': 'Co to oznacza',
  'ui.regeln_querverweis': 'Powiązane w podręczniku',
  'ui.regeln_grafiken': 'Pole gry i sygnały ręczne',
  'ui.turnier_titel': 'Regulamin turniejowy',
  'ui.turnier_kachel_text': 'Jakie wymogi obowiązują na oficjalnym turnieju? Wybierz kategorię — od Fun do 1000 — i zobacz, co dochodzi na każdym poziomie.',
  'ui.turnier_frage': 'Jaki turniej planujesz?',
  'ui.turnier_konkurrenz': 'Kategoria',
  'ui.turnier_einzel': 'Gra pojedyncza',
  'ui.turnier_auflagen_fuer': 'Wymogi dla turnieju {name}',
  'ui.turnier_davon': 'w tym',
  'ui.turnier_basis': 'Podstawa każdego oficjalnego turnieju',
  'ui.turnier_wie_zuvor': 'jak przy {vorher} — nic nie dochodzi',
  'ui.turnier_ggue': 'względem {vorher}',
  'ui.turnier_neu': 'nowe',
  'ui.turnier_verschaerft': 'zaostrzone',
  'ui.turnier_pflicht': 'Obowiązkowe',
  'ui.turnier_empfehlung': 'Zalecane',
  'ui.turnier_variante_titel': '{variante} — to obowiązuje dodatkowo',
  'ui.turnier_dokumente': 'Oficjalne dokumenty i źródła',
  'ui.turnier_quelle': 'Źródło',
  'ui.turnier_stand': 'Stan na',
  'ui.turnier_leer': 'Dla tej kategorii nie ma osobnych wymogów.',
  'ui.fortschritt': 'Postępy',
  'ui.fortschritt_global': 'Łącznie',
  'ui.bausteine_erledigt': '{a} z {b} modułów',
  'ui.teile_stand': 'Objaśnienia {a}/{b} · Zadania {c}/{d}',
  'ui.profil_diagnose': 'Twoje dane',
  'ui.profil_diagnose_text': 'Wszystko tutaj można zmienić w każdej chwili. Twoje postępy przy tym zostają zachowane — są przypisane do modułu, nie do ścieżki.',
  'ui.profil_stufe': 'Poziom',
  'ui.profil_trainer': 'Perspektywa trenera',
  'ui.profil_trainer_an': 'odblokowana',
  'ui.profil_trainer_aus': 'nieodblokowana',
  'ui.profil_herkunft': 'Pochodzenie',
  'ui.profil_ziel': 'Cele',
  'ui.vormarkieren_profil': 'Wstępnie oznacz opanowane moduły',
  'ui.vormarkieren_keine': 'Obecnie brak kandydatów — cała reszta ma dopasowanie albo jest już zrobiona.',
  'ui.einstellungen': 'Ustawienia',
  'ui.sprache': 'Język',
  'ui.uebersetzung_fehlt': 'Tłumaczenia wkrótce — treści na razie pojawiają się po niemiecku.',
  'ui.thema': 'Wygląd',
  'ui.thema_auto': 'Automatycznie (system)',
  'ui.thema_auto_kurz': 'Auto',
  'ui.thema_hell': 'Jasny',
  'ui.thema_dunkel': 'Ciemny',
  'ui.transfer_schalter': 'Pokaż skróty transferu',
  'ui.transfer_schalter_text': 'Dyskretne skróty pokazują, z jakiego sportu pochodzi dana treść.',
  'ui.daten_reset': 'Zresetuj postępy i dane',
  'ui.reset_bestaetigen': 'Na pewno zresetować wszystko? Twoje lokalne postępy i dane zostaną usunięte.',
  'ui.ueber': 'O tej aplikacji',
  'ui.ueber_text': 'Aplikacja do nauki crossmintona działająca po stronie klienta (pierwsza wersja). Treści po niemiecku; postępy zapisywane tylko na tym urządzeniu.',
  'ui.leer_stufe': 'Dla tego poziomu nie ma jeszcze modułów. Pierwsza wersja zawiera ścieżkę techniki dla początkujących.',
  'ui.leer_domaene': 'Dla tego obszaru tematycznego nie ma jeszcze modułów.',
  'ui.leer_ziel': 'Dla tego celu nie ma jeszcze modułów. Pierwsza wersja obejmuje obszar techniki dla początkujących.',
  'ui.leer_training': 'Nie ma jeszcze żadnych jednostek.',
  'ui.leer_weiterlernen': 'Wszystkie moduły twojego poziomu są ukończone.',
  'ui.suche_titel': 'Wyszukiwarka',
  'ui.suche_intro': 'Znajdź moduł według słowa kluczowego — w poprzek wszystkich tematów.',
  'ui.suche_feld_label': 'Wpisz szukane hasło',
  'ui.suche_platzhalter': 'Technika, serwis, gra podwójna, wiatr …',
  'ui.suche_start': 'Wpisz hasło — albo przeglądaj bezpośrednio według tematu:',
  'ui.suche_treffer': '{n} wyników',
  'ui.suche_keine_treffer': 'Nic nie znaleziono dla „{q}”. Spróbuj innego hasła albo przeglądaj według tematu.',
  'ui.fehler_laden_titel': 'Nie udało się wczytać treści',
  'ui.fehler_laden_text': 'Pliki danych były nieosiągalne. Jeśli strona jest otwierana bezpośrednio z systemu plików (file://), przeglądarka blokuje wczytywanie — uruchom zamiast tego mały lokalny serwer w folderze projektu, np.: python3 -m http.server',
  'ui.erneut_versuchen': 'Spróbuj ponownie',
  'ui.speicher_warnung': 'Uwaga: przeglądarka nie pozwala na trwały zapis (np. tryb prywatny). Postępy zostaną utracone po zamknięciu.',
  'ui.nav_ausruestung': 'Sprzęt',
  'ui.ausruestung_untertitel': 'Speeder, rakiety, buty i odzież',
  'ui.ausruestung_intro': 'Właściwy sprzęt sprawia, że gra jest łatwiejsza, bezpieczniejsza i daje więcej radości. Tu znajdziesz to, co naprawdę się liczy przy speederze, rakiecie, naciągu, butach i odzieży.',
  'ui.thema_wechseln': 'Zmień wygląd',

  // ---- bausteine (106) ----
  'bausteine.grundposition': 'Pozycja podstawowa',
  'bausteine.griff': 'Chwyt uniwersalny',
  'bausteine.aufschlag': 'Serwis',
  'bausteine.vorhand_drive': 'Drive forhendowy',
  'bausteine.rueckhand': 'Bekhend',
  'bausteine.beinarbeit': 'Praca nóg: centrum i split-step',
  'bausteine.spielziel_verstehen': 'Zrozumieć cel gry',
  'bausteine.zentrale_position': 'Pozycja centralna i kontrola pola',
  'bausteine.laenge_tiefe': 'Długość i głębokość jako najprostsza broń',
  'bausteine.rueckhand_des_gegners': 'Czytanie bekhendu przeciwnika',
  'bausteine.aufschlag_taktisch': 'Taktyczne wykorzystanie serwisu',
  'bausteine.fehler_vermeiden': 'Unikanie błędów: niedoceniana taktyka',
  'bausteine.warum_der_kopf_mitspielt': 'Dlaczego głowa gra razem',
  'bausteine.routine_vor_dem_aufschlag': 'Rutyna przed serwisem',
  'bausteine.ruhig_bleiben_wenn_es_eng_wird': 'Zachować spokój, gdy robi się ciasno',
  'bausteine.den_fehler_abhaken': 'Zostawić błąd za sobą',
  'bausteine.bei_der_sache_bleiben': 'Utrzymać koncentrację',
  'bausteine.warum_athletik_dein_spiel_traegt': 'Dlaczego przygotowanie fizyczne niesie twoją grę',
  'bausteine.richtig_aufwaermen': 'Prawidłowa rozgrzewka',
  'bausteine.beweglichkeit_und_schulter': 'Mobilność i bark',
  'bausteine.schnelle_fuesse': 'Szybkie stopy',
  'bausteine.durchhalten': 'Wytrwać',
  'bausteine.erholen': 'Regeneracja',
  'bausteine.handgelenk_peitsche': 'Ruch nadgarstka: bat',
  'bausteine.ueberkopf_clear': 'Uderzenie nad głową i clear',
  'bausteine.smash': 'Smecz',
  'bausteine.kurzes_spiel_stopp': 'Gra krótka: skrót',
  'bausteine.schnitt_spin': 'Podcięcie i rotacja',
  'bausteine.beinarbeit_system': 'System pracy nóg',
  'bausteine.umschalten': 'Atak i obrona — przełączanie',
  'bausteine.punkt_aufbauen': 'Budowanie punktu — długo i krótko',
  'bausteine.smash_vorbereiten': 'Przygotowanie smecza',
  'bausteine.gegner_lesen_muster': 'Czytanie przeciwnika i łamanie schematów',
  'bausteine.doppel_grundlagen': 'Gra podwójna — podstawy',
  'bausteine.engen_satz_fuehren': 'Prowadzenie wyrównanego seta',
  'bausteine.vom_werkzeug_zum_system': 'Od narzędzia do systemu',
  'bausteine.selbstgespraech_steuern': 'Kierowanie dialogiem wewnętrznym',
  'bausteine.sich_das_spiel_vorstellen': 'Wyobrażanie sobie gry',
  'bausteine.momentum_lesen_und_drehen': 'Czytanie i odwracanie momentum',
  'bausteine.ueber_das_match_stabil_bleiben': 'Utrzymać stabilność przez cały mecz',
  'bausteine.gezielt_trainieren': 'Trenować celowo',
  'bausteine.explosivitaet': 'Eksplozywność i skoczność',
  'bausteine.rumpfstabilitaet': 'Stabilność tułowia i przenoszenie siły',
  'bausteine.intervallausdauer': 'Wytrzymałość specyficzna — charakter interwałowy',
  'bausteine.belastung_steuern_regenerieren': 'Sterowanie obciążeniem i regeneracja',
  'bausteine.doppel_als_eigenes_spiel': 'Gra podwójna jako osobna gra',
  'bausteine.angriff_im_paar': 'Atak w parze',
  'bausteine.verteidigung_im_paar': 'Obrona w parze',
  'bausteine.bewegung_als_einheit': 'Ruch jako jedność',
  'bausteine.verstaendigung_im_paar': 'Porozumienie w parze',
  'bausteine.aufschlag_rueckschlag_doppel': 'Serwis i odbiór w grze podwójnej',
  'bausteine.das_umschalten_im_doppel': 'Przełączanie w grze podwójnej',
  'bausteine.taeuschung': 'Zwód — ukrycie zamiaru',
  'bausteine.frueh_nehmen': 'Wczesne przyjmowanie speedera',
  'bausteine.tempo_rhythmus_wechsel': 'Zmiana tempa i rytmu',
  'bausteine.sprung_smash': 'Smecz z wyskoku',
  'bausteine.praezision_an_die_linien': 'Precyzja przy liniach',
  'bausteine.konstanz_unter_hoechstdruck': 'Stałość pod najwyższą presją',
  'bausteine.der_matchplan': 'Plan meczu',
  'bausteine.gegner_typen_gegenrezepte': 'Typy przeciwników i kontrśrodki',
  'bausteine.dem_gegner_aufzwingen': 'Narzucić przeciwnikowi własną grę',
  'bausteine.schwaeche_systematisch_angreifen': 'Systematyczne atakowanie słabości',
  'bausteine.matchverlauf_steuern': 'Sterowanie przebiegiem meczu',
  'bausteine.entscheidender_punkt': 'Decydujący punkt',
  'bausteine.was_gutes_vermitteln_ausmacht': 'Na czym polega dobre nauczanie',
  'bausteine.inhalt_zugaenglich_machen': 'Uczynić treść przystępną',
  'bausteine.fehler_erkennen_korrigieren': 'Rozpoznawanie i korygowanie błędów',
  'bausteine.uebungen_aufbauen': 'Sensowne budowanie ćwiczeń',
  'bausteine.gruppe_fuehren': 'Prowadzenie grupy',
  'bausteine.optimaler_wettkampfzustand': 'Optymalny stan startowy',
  'bausteine.in_den_flow_finden': 'Wejść w flow',
  'bausteine.druck_als_herausforderung': 'Presję traktować jako wyzwanie',
  'bausteine.gelassen_bei_unfairness': 'Zachować spokój, gdy gra jest nie fair',
  'bausteine.mentale_staerke_entwickeln': 'Rozwijanie własnej siły mentalnej',
  'bausteine.form_ueber_die_saison': 'Planowanie formy na sezon',
  'bausteine.reaktivkraft_bodenkontakt': 'Siła reaktywna — szybki kontakt z podłożem',
  'bausteine.bewegungsoekonomie': 'Ekonomia ruchu — efektywnie zamiast nerwowo',
  'bausteine.antizipative_schnelligkeit': 'Szybkość antycypacyjna — wczesny start',
  'bausteine.langfristig_belastbar': 'Zdrowie i wytrzymałość na długo',
  'bausteine.draussen_spielen': 'Gra na zewnątrz',
  'bausteine.wind_lesen_nutzen': 'Czytanie i wykorzystanie wiatru',
  'bausteine.sonne_blendung': 'Słońce i oślepienie',
  'bausteine.naesse_sicherer_stand': 'Wilgoć i stabilna postawa',
  'bausteine.hitze': 'Upał',
  'bausteine.verschiedene_boeden': 'Różne podłoża',
  'bausteine.deine_ausruestung': 'Twój sprzęt',
  'bausteine.der_speeder': 'Speeder',
  'bausteine.der_schlaeger': 'Rakieta',
  'bausteine.schuhe_finden': 'Dobór butów',
  'bausteine.funktionskleidung': 'Odzież funkcyjna',
  'bausteine.die_bespannung': 'Naciąg',
  'bausteine.griff_und_griffband': 'Chwyt i owijka',
  'bausteine.erste_schritte_doppel': 'Pierwsze kroki w grze podwójnej',
  'bausteine.wer_nimmt_den_ball': 'Kto bierze piłkę',
  'bausteine.aufschlag_im_doppel_einfach': 'Serwis w grze podwójnej, prosto',
  'bausteine.sich_absprechen': 'Umawianie się',
  'bausteine.einander_platz_lassen': 'Zostawiać sobie miejsce',
  'bausteine.paar_als_system': 'Para jako system',
  'bausteine.gegnerisches_paar_lesen': 'Czytanie pary przeciwników',
  'bausteine.partner_in_position_bringen': 'Ustawić partnera w pozycji',
  'bausteine.nahtlos_umschalten': 'Płynne przełączanie',
  'bausteine.blindes_verstaendnis': 'Ślepe porozumienie',
  'bausteine.spielarten_ueberblick': 'Przegląd odmian gry',
  'bausteine.snowminton': 'Snowminton — gra na śniegu',
  'bausteine.beachminton': 'Beachminton — gra na piasku',
  'bausteine.blackminton': 'Blackminton — gra w ciemności',

  // ---- fehlerbilder (1) ----
  'fehlerbilder.griff_fehler_zu_fest': 'Zbyt mocny chwyt',

  // ---- grafiken (61) ----
  'grafiken.G-001': 'Grafika główna: chwyt uniwersalny z ułożeniem V',
  'grafiken.G-002': 'Grafika główna: pozycja podstawowa',
  'grafiken.G-003': 'Grafika główna: drive forhendowy',
  'grafiken.G-004': 'Grafika główna: bekhend',
  'grafiken.G-005': 'Serwis, obraz 1: speeder opada',
  'grafiken.G-006': 'Serwis, obraz 2: punkt kontaktu poniżej dłoni uderzającej',
  'grafiken.G-007': 'Praca nóg, obraz 1: split-step',
  'grafiken.G-008': 'Praca nóg, obraz 2: obieg ruchu',
  'grafiken.G-009': 'Grafika główna: ruch nadgarstka',
  'grafiken.G-010': 'Grafika główna: uderzenie nad głową',
  'grafiken.G-011': 'Grafika główna: smecz',
  'grafiken.G-012': 'Grafika główna: skrót',
  'grafiken.G-013': 'Grafika główna: podcięcie',
  'grafiken.G-014': 'Grafika główna: system pracy nóg',
  'grafiken.G-015': 'Grafika główna: wczesne przyjmowanie speedera',
  'grafiken.G-016': 'Zwód, obraz 1: identyczne przygotowanie',
  'grafiken.G-017': 'Zwód, obraz 2: późna decyzja',
  'grafiken.G-018': 'Zmiana tempa, obraz 1: wysokie tempo',
  'grafiken.G-019': 'Zmiana tempa, obraz 2: przełamany rytm',
  'grafiken.G-020': 'Grafika główna: smecz z wyskoku',
  'grafiken.G-021': 'Grafika główna: precyzja przy liniach',
  'grafiken.G-022': 'Grafika główna: stałość pod najwyższą presją',
  'grafiken.G-023': 'Grafika główna: zrozumieć cel gry',
  'grafiken.G-024': 'Grafika główna: pozycja centralna i kontrola pola',
  'grafiken.G-025': 'Grafika główna: długość i głębokość jako najprostsza broń',
  'grafiken.G-026': 'Grafika główna: czytanie bekhendu przeciwnika',
  'grafiken.G-027': 'Grafika główna: taktyczne wykorzystanie serwisu',
  'grafiken.G-028': 'Grafika główna: budowanie punktu — długo i krótko',
  'grafiken.G-029': 'Grafika główna: przygotowanie smecza',
  'grafiken.G-030': 'Grafika główna: typy przeciwników i kontrśrodki',
  'grafiken.G-031': 'Grafika główna: systematyczne atakowanie słabości',
  'grafiken.G-032': 'Grafika główna: szybkie stopy',
  'grafiken.G-033': 'Grafika główna: mobilność i bark',
  'grafiken.G-034': 'Grafika główna: eksplozywność i skoczność',
  'grafiken.G-035': 'Grafika główna: siła reaktywna — szybki kontakt z podłożem',
  'grafiken.G-036': 'Grafika główna: ekonomia ruchu — efektywnie zamiast nerwowo',
  'grafiken.G-037': 'Grafika główna: gra podwójna jako osobna gra',
  'grafiken.G-038': 'Grafika główna: atak w parze',
  'grafiken.G-039': 'Grafika główna: obrona w parze',
  'grafiken.G-040': 'Grafika główna: serwis i odbiór w grze podwójnej',
  'grafiken.G-041': 'Grafika główna: przełączanie w grze podwójnej',
  'grafiken.G-042': 'Grafika główna: ruch jako jedność',
  'grafiken.G-043': 'Grafika główna: porozumienie w parze',
  'grafiken.G-044': 'Grafika główna: pierwsze kroki w grze podwójnej',
  'grafiken.G-045': 'Grafika główna: kto bierze piłkę',
  'grafiken.G-046': 'Grafika główna: serwis w grze podwójnej, prosto',
  'grafiken.G-047': 'Grafika główna: umawianie się',
  'grafiken.G-048': 'Grafika główna: zostawiać sobie miejsce',
  'grafiken.G-049': 'Grafika główna: para jako system',
  'grafiken.G-050': 'Grafika główna: czytanie pary przeciwników',
  'grafiken.G-051': 'Grafika główna: ustawić partnera w pozycji',
  'grafiken.G-052': 'Grafika główna: płynne przełączanie',
  'grafiken.G-053': 'Grafika główna: ślepe porozumienie',
  'grafiken.G-054': 'Grafika główna: gra na zewnątrz',
  'grafiken.G-055': 'Grafika główna: czytanie i wykorzystanie wiatru',
  'grafiken.G-056': 'Grafika główna: słońce i oślepienie',
  'grafiken.G-057': 'Grafika główna: wilgoć i stabilna postawa',
  'grafiken.G-058': 'Grafika główna: upał',
  'grafiken.G-059': 'Grafika główna: różne podłoża',
  'grafiken.G-060': 'Grafika: wymiarowane pole gry',
  'grafiken.G-061': 'Grafika: sygnały ręczne sędziego',

  // ---- vokabeln.domaene (6) ----
  'vokabeln.domaene.technik': 'Technika',
  'vokabeln.domaene.taktik': 'Taktyka',
  'vokabeln.domaene.trainingsgestaltung': 'Prowadzenie treningu',
  'vokabeln.domaene.mentales': 'Mentalne',
  'vokabeln.domaene.athletik_kondition': 'Przygotowanie fizyczne',
  'vokabeln.domaene.ausruestung': 'Sprzęt',

  // ---- vokabeln.kompetenzstufe (4) ----
  'vokabeln.kompetenzstufe.beginner': 'Początkujący',
  'vokabeln.kompetenzstufe.fortgeschritten': 'Zaawansowany',
  'vokabeln.kompetenzstufe.experte': 'Ekspert',
  'vokabeln.kompetenzstufe.trainer': 'Perspektywa trenera',

  // ---- vokabeln.spielform (2) ----
  'vokabeln.spielform.einzel': 'Gra pojedyncza',
  'vokabeln.spielform.doppel': 'Gra podwójna',

  // ---- vokabeln.baustein_typ (5) ----
  'vokabeln.baustein_typ.micro': 'Mikromoduł',
  'vokabeln.baustein_typ.vertiefung': 'Pogłębienie',
  'vokabeln.baustein_typ.delta': 'Wskazówka cross-sport',
  'vokabeln.baustein_typ.fehlerbild': 'Typowy błąd',
  'vokabeln.baustein_typ.umgebungs_baustein': 'Moduł środowiskowy',

  // ---- vokabeln.transfer_herkunft (7) ----
  'vokabeln.transfer_herkunft.CM': 'Crossminton',
  'vokabeln.transfer_herkunft.BAD': 'Badminton',
  'vokabeln.transfer_herkunft.TEN': 'Tenis',
  'vokabeln.transfer_herkunft.SQ': 'Squash',
  'vokabeln.transfer_herkunft.BS': 'Szkoła piłki',
  'vokabeln.transfer_herkunft.SP': 'Psychologia sportu',
  'vokabeln.transfer_herkunft.AT': 'Nauki o treningu',

  // ---- vokabeln.untergrund (6) ----
  'vokabeln.untergrund.halle': 'Hala',
  'vokabeln.untergrund.sand': 'Piasek',
  'vokabeln.untergrund.rasen': 'Trawa',
  'vokabeln.untergrund.asche': 'Mączka',
  'vokabeln.untergrund.kunstrasen': 'Sztuczna trawa',
  'vokabeln.untergrund.schnee': 'Śnieg',

  // ---- vokabeln.witterung (6) ----
  'vokabeln.witterung.wind': 'Wiatr',
  'vokabeln.witterung.sonne_blendung': 'Słońce i oślepienie',
  'vokabeln.witterung.naesse': 'Wilgoć',
  'vokabeln.witterung.hitze': 'Upał',
  'vokabeln.witterung.kaelte': 'Zimno',
  'vokabeln.witterung.dunkelheit': 'Ciemność',

  // ---- vokabeln.abschluss_status (3) ----
  'vokabeln.abschluss_status.offen': 'do zrobienia',
  'vokabeln.abschluss_status.erledigt': 'zrobione',
  'vokabeln.abschluss_status.beherrscht': 'opanowane',

  // ---- spielziele.bereiche (6) ----
  'spielziele.bereiche.energetik': 'Energetyka',
  'spielziele.bereiche.praezision_kontrolle': 'Precyzja i kontrola',
  'spielziele.bereiche.wahrnehmung_antizipation': 'Percepcja i antycypacja',
  'spielziele.bereiche.psychoregulation': 'Psychoregulacja',
  'spielziele.bereiche.umgebungsanpassung': 'Adaptacja do otoczenia',
  'spielziele.bereiche.technisch_taktisches_repertoire': 'Repertuar techniczno-taktyczny',

  // ---- spielziele.faktoren (22) ----
  'spielziele.faktoren.rally_ausdauer': 'Wytrzymałość w wymianach',
  'spielziele.faktoren.wiederholte_antrittsschnelligkeit': 'Powtarzalna szybkość startowa',
  'spielziele.faktoren.satz_match_regeneration': 'Regeneracja w secie i meczu',
  'spielziele.faktoren.treffsicherheit_im_ziel': 'Celność trafień',
  'spielziele.faktoren.laengen_tiefensteuerung': 'Sterowanie długością i głębokością',
  'spielziele.faktoren.tempo_haertedosierung': 'Dawkowanie tempa i mocy',
  'spielziele.faktoren.konstanz_unter_wiederholung': 'Stałość przy powtarzaniu',
  'spielziele.faktoren.fruehe_flugbahnlesung': 'Wczesne czytanie toru lotu',
  'spielziele.faktoren.gegner_muster_lesen': 'Czytanie schematów przeciwnika',
  'spielziele.faktoren.umschaltmoment_erkennen': 'Rozpoznawanie momentu przełączenia',
  'spielziele.faktoren.nervenstaerke_enger_satz': 'Odporność nerwowa w wyrównanym secie',
  'spielziele.faktoren.fehler_resilienz': 'Odporność na błędy',
  'spielziele.faktoren.konzentrationskonstanz': 'Stałość koncentracji',
  'spielziele.faktoren.vorbereitende_selbststeuerung': 'Przygotowawcza samoregulacja',
  'spielziele.faktoren.windspiel': 'Gra w wietrze',
  'spielziele.faktoren.untergrundwechsel': 'Zmiana podłoża',
  'spielziele.faktoren.licht_und_sicht': 'Światło i widoczność',
  'spielziele.faktoren.temperatur': 'Temperatura',
  'spielziele.faktoren.antwort_gegen_angreifer': 'Odpowiedź na atakującego',
  'spielziele.faktoren.antwort_gegen_defensivspieler': 'Odpowiedź na gracza defensywnego',
  'spielziele.faktoren.umschaltloesung': 'Rozwiązanie na przełączanie',
  'spielziele.faktoren.aufschlag_rueckschlag_eroeffnung': 'Otwarcie serwisem i odbiorem',
  'spielziele.faktoren.doppel_spezifische_loesungen': 'Rozwiązania specyficzne dla gry podwójnej',

  // ---- vermittlungsziele.bereiche (4) ----
  'vermittlungsziele.bereiche.vermitteln_zugaenglichmachen': 'Nauczanie i uprzystępnianie',
  'vermittlungsziele.bereiche.diagnostizieren_korrigieren': 'Diagnozowanie i korygowanie',
  'vermittlungsziele.bereiche.progression_lernprozess_steuern': 'Progresja i sterowanie procesem uczenia',
  'vermittlungsziele.bereiche.gruppe_setting_fuehren': 'Prowadzenie grupy i zajęć',

  // ---- vermittlungsziele.faktoren (14) ----
  'vermittlungsziele.faktoren.bewegungskern_herausarbeiten': 'Wydobycie rdzenia ruchu',
  'vermittlungsziele.faktoren.demonstrieren_modell_geben': 'Demonstrowanie / dawanie wzoru',
  'vermittlungsziele.faktoren.in_bilder_analogien_uebersetzen': 'Przekładanie na obrazy i analogie',
  'vermittlungsziele.faktoren.fehlerbild_erkennen': 'Rozpoznanie typowego błędu',
  'vermittlungsziele.faktoren.ursache_von_symptom_trennen': 'Oddzielenie przyczyny od objawu',
  'vermittlungsziele.faktoren.korrekturansage_geben': 'Udzielanie wskazówki korygującej',
  'vermittlungsziele.faktoren.uebungsreihe_sequenzieren': 'Sekwencjonowanie serii ćwiczeń',
  'vermittlungsziele.faktoren.schwierigkeit_dosieren': 'Dawkowanie trudności',
  'vermittlungsziele.faktoren.lernphasen_uebergang_gestalten': 'Kształtowanie przejść między fazami nauki',
  'vermittlungsziele.faktoren.heterogene_gruppe_organisieren': 'Organizacja grupy zróżnicowanej',
  'vermittlungsziele.faktoren.einheit_strukturieren': 'Strukturyzowanie jednostki',
  'vermittlungsziele.faktoren.raum_material_organisieren': 'Organizacja przestrzeni i sprzętu',
  'vermittlungsziele.faktoren.motivation_sicherheit_halten': 'Utrzymanie motywacji i bezpieczeństwa',

  // ---- trainingseinheiten (8) ----
  'trainingseinheiten.beginner_erste_schlaege': 'Pierwsze uderzenia',
  'trainingseinheiten.beginner_bewegung_und_position': 'Ruch i pozycja',
  'trainingseinheiten.fortgeschritten_angriff_aufbauen': 'Budowanie ataku',
  'trainingseinheiten.doppel_als_paar_spielen': 'Gra jako para',
  'trainingseinheiten.experte_praezision_und_taeuschung': 'Precyzja i zwód',
  'trainingseinheiten.experte_tempo_und_konstanz': 'Tempo i stałość',
  'trainingseinheiten.outdoor_wind_und_boden': 'Wiatr i podłoże',
  'trainingseinheiten.doppel_beginner_zusammenspiel': 'Pierwsza współpraca w grze podwójnej',
};

// ---- Struktur von de.json spiegeln, Blätter durch PL[pfad] ersetzen ----
const fehlend = [];
function uebersetze(knoten, pfad) {
  if (typeof knoten === 'string') {
    const wert = PL[pfad];
    if (wert === undefined) { fehlend.push(pfad); return ''; }
    return wert;
  }
  const out = {};
  for (const [k, v] of Object.entries(knoten)) {
    out[k] = uebersetze(v, pfad ? `${pfad}.${k}` : k);
  }
  return out;
}

const pl = {};
pl._meta = {
  sprache: 'pl',
  status: 'ui_labels_uebersetzt',
  hinweis: 'UI-Labels vollständig polnisch (Ring 0). Inhaltsknoten folgen ringweise; bis dahin greift die Fallback-Kette pl → de. Terminologie: docs/glossar-pl.md.',
};
for (const [gruppe, knoten] of Object.entries(de)) {
  if (gruppe === '_meta') continue;
  pl[gruppe] = uebersetze(knoten, gruppe);
}

if (fehlend.length) {
  console.error(`FEHLEN (${fehlend.length}):`);
  for (const p of fehlend) console.error('  ' + p);
  process.exit(1);
}

// Zusatzschlüssel in PL, die es in de nicht gibt (Tippfehler-Guard)
const alleDePfade = new Set();
(function sammle(k, p) {
  if (typeof k === 'string') { alleDePfade.add(p); return; }
  for (const [kk, vv] of Object.entries(k)) sammle(vv, p ? `${p}.${kk}` : kk);
})(de, '');
const extra = Object.keys(PL).filter((p) => !alleDePfade.has(p));
if (extra.length) {
  console.error(`UNBEKANNTE PL-SCHLÜSSEL (${extra.length}):`);
  for (const p of extra) console.error('  ' + p);
  process.exit(1);
}

writeFileSync('data/labels/pl.json', JSON.stringify(pl, null, 2) + '\n', 'utf8');
console.log(`pl.json geschrieben — ${Object.keys(PL).length} Labels übersetzt.`);
