// Ring 4 (pl): Beginner-Ausrüstung (15) + Beginner-Doppel (15) = 30 Knoten.
import { insertPl } from './pl-core.mjs';

const AUSRUESTUNG = [
  'Twój sprzęt',
  'Crossminton obywa się małym: rakieta, kilka speederów, odpowiednie buty. A mimo to każdy element wpływa na to, jak grasz — i większość z nich dobierzesz trafnie za pomocą kilku prostych reguł.\n\nSpeeder to twoja piłka. Leci ciężko i szybko i jest wyraźnie stabilniejszy przy wietrze niż lotka — ale tylko w odpowiednim typie. Są wolniejsze speedery na start i do hali oraz cięższe na zewnątrz przy wietrze; w niektórych modelach regulujesz tempo małymi nakładkami. Miej na początku dwa lub trzy pod ręką: materiał do ćwiczeń się zużywa, a nadszarpnięty speeder leci nieobliczalnie.\n\nRakieta jest krótsza i sztywniejsza niż rakieta do badmintona i tak jak ona jest naciągnięta. Napięcie naciągu to kompromis — mocniej naciągnięta daje więcej kontroli, luźniej naciągnięta więcej tempa z samej rakiety. Jako początkującemu pasuje ci standardowy naciąg; nad tym nie musisz się jeszcze zastanawiać. Ważniejszy jest chwyt: jeśli ślizga się od potu, wymień owijkę. Pewny chwyt oszczędza siłę i chroni nadgarstek.\n\nButy niosą twoją grę bardziej, niż się wydaje. Crossminton żyje z krótkich, twardych zrywów w bok — do tego potrzebujesz bocznego oparcia i podeszwy, która trzyma. W hali należy się jasna, niebrudząca podeszwa; wiele hal tego wymaga. Na zewnątrz decyduje podłoże: na piasku, mączce czy trawie chwyta bieżnik, który w hali tylko by się ślizgał.\n\nOdzież ma pozwalać ci się swobodnie ruszać: przewiewna i na tyle luźna, by starczyło na głębokie wykroki. Na zewnątrz dobierasz ją do pogody — w razie wątpliwości jedna warstwa więcej, którą można zdjąć. Na oficjalnych turniejach należy się koszulka z twoim nazwiskiem (szczegóły w regulaminie turniejowym pod „Zasady").\n\nDobry sprzęt nie zrobi z ciebie lepszego gracza. Ale zły lub zużyty cię hamuje. Przeglądaj go od czasu do czasu, a nigdy nie stanie twojej grze na drodze. Kolejne moduły omawiają cztery elementy po kolei.',
  'Połóż przed sobą rakietę, kilka speederów i buty i przejrzyj je raz: czy chwyt jest jeszcze chwytny, czy ślizga się od potu? Czy twoje speedery pasują do miejsca, w którym najczęściej grasz — hala czy zewnątrz? Czy podeszwa zostawia ślady na podłodze hali? Zanotuj sobie jedną rzecz, którą chcesz wymienić, uzupełnić lub raz wypróbować, i zajmij się nią przed następnym meczem.',
  'Speeder',
  'Speeder to piłka crossmintona — i powód, dla którego ten sport w ogóle istnieje. Na początku było poszukiwanie piłki, która leci także przy wietrze, tam gdzie lotka dawno by zniosło. Odpowiedź jest krótsza, cięższa i węższa w budowie niż lotka: skrócona spódniczka niesie mniejszy opór powietrza, wyższa masa daje więcej bezwładności. Razem daje to płaski, szybki, daleki tor, który pozostaje stabilny. Speeder waży od 8 do 10 gramów, około trzy razy tyle co lotka, i jest wodoodporny oraz odporny na rozrywanie.\n\nWystępuje w kilku typach, a dla twojej gry liczy się przede wszystkim sięgnąć po właściwy. Czerwony Fun Speeder jest najlżejszy i najwolniejszy: idealny na start, dla dzieci i na trening — w kategorii U12 jest wręcz obowiązkowy. Żółty Match Speeder to oficjalna piłka turniejowa; nim gra się we wszystkich pozostałych kategoriach. Cross Speeder jest najcięższy i leci najdalej, pomyślany na długie dystanse i wiatr. Night Speeder nosi przezroczystą nakładkę na świecącą pałeczkę i umożliwia grę w ciemności. Heli jest szczególnie stabilny przy wietrze i zbudowany na krótkie drogi.\n\nPodawane przez producentów zasięgi i tempa wahają się zależnie od źródła mocno — bierz je jako rząd wielkości, nie jako wartość pomiarową. Pewna jest kolejność: Fun najwolniejszy, Match pośrodku, Cross najszybszy i najdalszy.\n\nPrzy wietrze masz trzy stopnie. Sam speeder jest zbudowany tak, by dało się nim grać do mniej więcej siły wiatru 4 — to jego właściwy cel. Jeśli to nie wystarcza, wsuwasz pod nakładkę pierścień wiatrowy: zwiększa masę, a większa masa przy tej samej powierzchni czoła czyni tor bardziej bezwładnym wobec wiatru bocznego, czyli stabilniejszym. Rozpowszechnionym błędem jest sądzić, że pierścień obniża opór powietrza. To nieprawda: pozostawia kształt bez zmian i zwiększa jedynie masę. Dopiero gdy i to nie wystarcza, sięgasz po cięższy typ jak Cross — w zawodach jednak tylko po uzgodnieniu z organizatorem i za zgodą sędziego głównego.\n\nDwie reguły warto znać. Kształt speedera nie może się zmieniać — chowanie go w międzyczasie do kieszeni spodni jest wyraźnie zabronione. I widocznie uszkodzonego speedera nie wolno ci celowo grać dalej; jeśli odkształci się w wymianie, punkt się powtarza. Sprawdzaj dlatego swoje speedery po każdym meczu i odkładaj nadszarpnięte.',
  'Przyjrzyj się swoim speederom: który typ leży u ciebie w torbie — czerwony (Fun) czy żółty (Match)? Czy pasuje do tego, w co najczęściej grasz? Obróć każdy raz w dłoni i sprawdź na pęknięcia i wgniecenia; nadszarpnięte speedery lecą nieobliczalnie i trzeba je odłożyć. A jeśli grasz na zewnątrz: czy masz przy sobie odpowiedź na wiatr — pierścień wiatrowy albo cięższego speedera?',
  'Rakieta',
  'Dlaczego w ogóle istnieje osobna rakieta do crossmintona, mówi wiele o tym sporcie. Pierwsze wymiany grano rakietami do badmintona i squasha. Rakiety do badmintona nie wytrzymywały siły — speeder jest około trzy razy cięższy niż lotka i rozbijał delikatne ramy. Rakiety do squasha były zbyt długie i zbyt ociężałe wobec tempa. Z tej luki powstała własna forma budowy: krótka i zwrotna jak w squashu, ale dość wytrzymała na ciężką piłkę.\n\nPrzepisy wyznaczają tylko dwie granice: rakieta ma najwyżej 61 centymetrów długości, a główka mierzy najwyżej 650 centymetrów kwadratowych. Wszystko inne — masa, materiał, balans, naciąg, grubość chwytu — jest dowolne. Twój wybór kieruje się więc tobą, nie przepisem.\n\nMasa leży zwykle między 100 a 145 gramami. Lżejsza rakieta jest zwrotniejsza i później męczy dłoń uderzającą — zaleta, bo crossmintona gra się z wysoką częstotliwością we wszystkie cztery narożniki. Cięższa niesie więcej masy w uderzenie. Na początek bezpiecznym wyborem jest raczej lekka, wyważona rakieta.\n\nPrzy materiale rozchodzą się start i turniej. Rakiety dla początkujących są przeważnie z aluminium: tanie, wytrzymałe, często z krótszym trzonem i większą powierzchnią uderzenia, co ułatwia trafianie — akurat dobre do szkoły i wypożyczalni. Rakiety turniejowe są z grafitu i carbonu, często wzmocnione kevlarem; są lżejsze, sztywniejsze i dają bardziej bezpośrednie czucie przy trafieniu. Różnica materiału ma następstwo, które staje się ważne przy naciąganiu: aluminium znosi wyraźnie mniejszy ciąg naciągu niż carbon.\n\nTrzy pojęcia spotkasz w każdej poradzie zakupowej. Balans mówi, gdzie siedzi masa: przeważenie w główce wspiera siłę uderzenia, przeważenie w chwycie prowadzenie, wyważenie jest wszechstronne. Sztywność opisuje, jak bardzo rama ustępuje: sztywna melduje trafienie bezpośrednio, elastyczna wybacza więcej. A sweet spot to optymalny obszar trafienia — większa główka czyni go większym, a trafianie łatwiejszym. Te dane pochodzą ze sportów rakietowych i nie są dla crossmintona osobno potwierdzone; bierz je jako punkt orientacyjny i ostatecznie zaufaj własnemu czuciu przy próbnym uderzaniu.',
  'Weź rakietę do ręki i wsłuchaj się w nią: czy po długiej wymianie wciąż wydaje się lekka, czy ciągnie dłoń w dół? Jest z aluminium czy z carbonu? Zbalansuj ją luźno na jednym palcu — masa siedzi raczej w główce (siła) czy w chwycie (kontrola)? Zastanów się, czy to pasuje do sposobu, w jaki chcesz grać.',
  'Dobór butów',
  'Zacznijmy od szczerej informacji: nie ma osobnych butów do crossmintona ani reguły o butach. Gra się w butach do badmintona, squasha lub ogólnych butach halowych. Przepisy zajmują się podłożem — nie może stwarzać podwyższonego ryzyka kontuzji —, but pozostawiają tobie.\n\nPrzeniesienie ze sportu halowego pasuje dobrze, ale nie do końca. Buty do badmintona i squasha są zbudowane pod pole, które pracuje w przód i w tył — do siatki, do przedniej ściany. Pole crossmintona to kwadrat z czterema równorzędnymi narożnikami wokół środka. Wymagany jest więc nie tyle ruch w przód, co pewny wykrok w każdym kierunku. Kluczowe wymagania butów halowych i tak w to trafiają, bo i tak celują w stop-and-go, boczne oparcie i szybkie zmiany kierunku.\n\nNa co zwracasz uwagę w hali: jasna, niebrudząca podeszwa, której wiele hal wymaga już przy wejściu; boczna stabilność z twardym zapiętkiem przeciw skręceniu przy wykroku; płaska, elastyczna budowa dla szybkich reakcji; nieco amortyzacji przeciw wstrząsom przy odbiciu i lądowaniu; i pewne osadzenie, by przy zrywie nie tracić siły. Buty tenisowe nadają się tylko warunkowo — są cięższe i zbudowane pod inne drogi. Buty do piłki ręcznej i siatkówki mogą pasować, jeśli spełniają te punkty.\n\nJednego konfliktu celów nie rozwiążesz, możesz go tylko wyważyć: amortyzacja i stabilność stoją przeciw lekkości i szybkości reakcji. Co jest dla ciebie ważniejsze, decydujesz sam.\n\nNa zewnątrz robi się nieprzejrzyście. Crossminton toczy się na trawie, piasku, asfalcie, mączce i sztucznej trawie, a dla żadnego z tych podłoży nie ma miarodajnej rekomendacji butów. Pewne jest tylko: podeszwa halowa na asfalcie szybko się ściera, a przyczepność różni się zależnie od nawierzchni zasadniczo. Jeśli regularnie grasz na zewnątrz, opłaca się druga para z bieżnikiem — którą, najprędzej dojdziesz przez próby na swoim boisku. Jak nastawić się na zmieniające się podłoża, stoi w części plenerowej podręcznika.',
  'Odwróć buty halowe i spójrz na podeszwę: brudzi, czy jest jasna i chwytna? Zrób w hali twardy wykrok w bok — but trzyma, czy stopa ucieka na zewnątrz? A jeśli grasz też na zewnątrz: czy ta sama podeszwa chwyta na twoim boisku, czy się ślizgasz? Zanotuj, czy druga para na zewnątrz miałaby sens.',
  'Odzież funkcyjna',
  'Przy odzieży jedna reguła stoi ponad wszystkim, i jest ona crossmintonowi własna: jeśli speeder dotknie twojego ciała lub odzieży — wyraźnie łącznie z butami i skarpetami —, punkt jest stracony. Luźne, powiewające rzeczy są tym samym bezpośrednim ryzykiem. Luźna koszula, którą speeder muśnie w przelocie, kosztuje cię wymianę. Pierwsza reguła stroju do gry brzmi dlatego po prostu: dość obcisłe, by nic nie powiewało.\n\nDo tego dochodzi na oficjalnych turniejach obowiązek koszulki. Na dużych turniejach nosisz we wszystkich meczach koszulkę ze swoim nazwiskiem i krajem na plecach; na mniejszych obowiązuje to od półfinału, na turniejach 100-punktowych wcale. Szczegóły stoją w regulaminie turniejowym pod „Zasady".\n\nPrzy materiale opłaca się spojrzeć na tkaninę. Bawełna nasiąka potem i trzyma potem wilgotną warstwę wprost na skórze; w pełni lata przyjemnie to chłodzi, w chłodne dni odbiera ci ciepło z ciała. Włókna funkcyjne z poliestru prawie nie chłoną wilgoci, transportują ją na zewnątrz i szybko schną — do krótkich, intensywnych jednostek pierwszy wybór. Wełna merynosowa wprawdzie chłonie wilgoć, ale odprowadza ją lepiej niż bawełna i dłużej pachnie świeżo; jej siłą jest długie noszenie przy zmiennej temperaturze.\n\nNa zewnątrz pomaga zasada warstw: cienka warstwa bazowa, która odprowadza pot od skóry, na niej warstwa grzejąca z uwięzionego powietrza, a przy wietrze lub wilgoci warstwa ochronna na wierzchu. Zaletą jest to, że warstwy możesz zdejmować i znów nakładać. Ważna jest ciągłość: jedna jedyna warstwa bawełny w środku nasiąka i niweczy cały system. W chłodne dni odzież może siedzieć nieco luźniej, bo powietrze między warstwami izoluje — „luźno" znaczy tu warstwę powietrza, nie powiewanie; reguła błędu z góry obowiązuje dalej.\n\nWiatr i słońce wymagają niewiele ekstra. Wiatroszczelna, obcisło skrojona kurtka odcina wiatr i mimo to pozostaje przewiewna; przy wietrze powiewająca kurtka jest podwójnie niekorzystna, jako ryzyko punktu i jako zakłócenie. Przeciw słońcu są koszulki sportowe z wysoką ochroną UV, które odcinają wyraźnie więcej niż biała koszulka bawełniana. Jak ciepło lub zimno ci przy tym jest, różni się od osoby do osoby; właśnie dlatego zasada warstw jest tak praktyczna, bo daje się dopasować do twojego własnego odczucia.',
  'Załóż to, co nosisz podczas gry, i zrób głęboki wykrok: czy gdzieś powiewa coś, co speeder mógłby złapać? Poczuj tkaninę — bawełna, która nasiąka, czy materiał funkcyjny, który zostaje suchy? A jeśli grasz na zewnątrz: czy masz przy sobie warstwę, którą przy wietrze lub zimnie nałożysz, a przy cieple znów zdejmiesz?',
];

const DOPPEL = [
  'Pierwsze kroki w grze podwójnej',
  'W grze podwójnej dzielisz swoje pole z partnerem. Z jednego gracza robi się dwóch — i to zmienia wszystko. Wspólnie pokrywacie więcej powierzchni, ale musicie się też dostroić, żeby sobie nie wchodzić w drogę. Debel to osobna, wspólna gra, nie singiel we dwoje.\n\nPierwsza myśl przewodnia to myśleć jako para. Nie odpowiadasz sam za swoją połowę pola, a partner za drugą — gracie razem i pomagacie sobie nawzajem. Gdy partner bierze piłkę, ty kryjesz zwalniającą się przestrzeń. Poruszacie się względem siebie, nie każdy dla siebie.\n\nDruga myśl przewodnia to uważać na partnera. Trzymasz w polu widzenia, gdzie stoi i co robi. Jeśli bierze piłkę, zostajesz z tyłu i szykujesz się na następną. Zmieniacie się i uzupełniacie, zamiast obaj robić to samo.\n\nKolejne moduły omawiają proste podstawy: kto bierze piłkę, jak serwujecie, jak się umawiacie i jak zostawiacie sobie miejsce. Wszystko dalsze na tym się buduje.\n\nDobry debel jest jak dwoje tancerzy, którzy dzielą parkiet. Każdy ma swoją przestrzeń, oboje poruszają się względem siebie — i nikt nie nadeptuje drugiemu na stopy.',
  'Gdy następnym razem będziesz grać debla, zwróć świadomie uwagę, by myśleć jako para, a nie jako dwóch pojedynczych graczy: czy trzymasz w polu widzenia, gdzie stoi partner? Czy kryjesz przestrzeń, którą opuszcza, gdy bierze piłkę? Postanów sobie poruszać się jako wspólny zespół, który się uzupełnia, zamiast żeby każdy pilnował tylko własnego kawałka pola.',
  'Kto bierze piłkę',
  'Najczęstsza pułapka w deblu początkujących to piłka w środku. Leci dokładnie między was — i wtedy dzieje się jedno z dwojga: albo obaj idą i wchodzą sobie w drogę, albo nikt nie idzie, bo każdy myśli, że zrobi to drugi. W obu przypadkach punkt pada.\n\nRozwiązaniem jest prosta reguła podstawowa: dla każdej piłki jasne jest, kto ją bierze. Najprościej idzie to przez krótki okrzyk. Kto bierze piłkę, woła „Moja!"; kto zostawia ją partnerowi, woła „Twoja!" albo „Zostaw!". Jedno jedyne słowo w odpowiednim momencie zapobiega zderzeniu i utracie punktów przez wahanie.\n\nProsta zasada dodatkowo pomaga: kto lepiej stoi i wygodniej dosięga piłki, ten ją bierze. Przeważnie to ten, po którego stronie piłka leci, albo ten, który może ją wziąć mocniejszym forhendem. Ustalcie to spokojnie także przed grą: kto w razie wątpliwości bierze środek?\n\nNajważniejsze to wołać wcześnie i wyraźnie. Późne „Moja!" przychodzi za późno. Kto wcześnie decyduje i mówi to głośno, daje partnerowi pewność, by skupić się na reszcie.\n\nPiłka w środku jest jak drzwi, przez które dwoje chce przejść naraz. Krótkie słowo wyjaśnia, kto idzie pierwszy — i już nikt się nie zderza.',
  {
    titel: 'Moja czy twoja',
    ziel: 'Piłki w środku jasno i wcześnie przypisać jednemu z dwojga.',
    schritte: [
      'Niech trzecia osoba podaje wam na przemian piłki, także celowo w środek między was.',
      'Przy każdej piłce jeden woła wcześnie i wyraźnie „Moja!" albo „Twoja!".',
      'Trzymajcie się zasady: kto lepiej stoi lub ma mocniejszy forhend, bierze piłkę.',
      'Zadbajcie o to, by okrzyk padał wcześnie, nie dopiero w ostatniej chwili.',
      'Po każdej piłce krótko sprawdźcie: czy przypisanie było jasne, czy było wahanie?',
    ],
    selbstkontrolle: 'Wołacie dość wcześnie, czy uzgodnienie przychodzi za późno? Czy przy każdej piłce w środku jasne jest, kto ją bierze, czy jest jeszcze wahanie i niedoszłe zderzenia? Wczesny, wyraźny okrzyk rozwiązuje niemal wszystkie problemy z piłką w środku.',
    abschluss: 'Kto bierze piłkę, to najważniejsze podstawowe uzgodnienie w deblu. Krótkie, wczesne słowo zapobiega najczęstszym błędom początkujących.',
  },
  'Serwis w grze podwójnej, prosto',
  'Serwis działa w deblu jak w singlu — od dołu, ze strefy serwisowej, jedna stopa na podłożu. Nowe jest tylko to, że jest was czworo, a serwis podąża za stałą kolejnością. Na początek wystarczy zrozumieć podstawową logikę; pełna rotacja przychodzi później.\n\nNajważniejsze najpierw: w deblu serwuje zawsze gracz tylny, gracz z tyłu. Stoi w strefie serwisowej i wprowadza speedera do gry. Jego partner, gracz atakujący, stoi bardziej z przodu i jest gotów przechwycić po serwisie pierwszą krótką piłkę.\n\nPrawo serwisu wędruje w stałej kolejności przez wszystkich czterech graczy. Na początek musisz zapamiętać tylko: każdy przychodzi raz, w ustalonym porządku, a poza kolejnością nikt nie serwuje. Dokładną sekwencję nauczysz się, gdy nabierzecie pewności — w deblu zaawansowanym jest wyjaśniona obszernie.\n\nProste uzgodnienie pomaga już teraz: ustalcie krótko przed serwisem, kto jest właśnie na kolejce, żeby nikt się nie pogubił. Spojrzenie lub słowo wystarczy.\n\nSerwis w deblu jest jak rozdawanie kart po kolei. Każdy jest raz na kolejce, w stałym porządku — i nikt nie wchodzi przed swoją koleją.',
  {
    titel: 'Serwować po kolei',
    ziel: 'Zagrać serwis deblowy ze strefy serwisowej w prostej, stałej kolejności.',
    schritte: [
      'Ustawcie się we czworo: po jednym graczu tylnym (z tyłu) i jednym atakującym (z przodu) na pole.',
      'Gracz tylny serwuje od dołu ze strefy serwisowej, jedna stopa zostaje na podłożu.',
      'Gracz przedni szykuje się przechwycić pierwszą krótką piłkę.',
      'Ustalcie krótko przed każdym serwisem, kto jest właśnie na kolejce.',
      'Zagrajcie kilka serwisów, aż prosta kolejność się utrwali.',
    ],
    selbstkontrolle: 'Czy serwuje gracz tylny, a przedni stoi gotowy? Czy jasne jest wam, kto jest właśnie na kolejce? Na początek wystarczy podstawowa logika — pełna rotacja przychodzi w deblu zaawansowanym.',
    abschluss: 'Serwis deblowy podąża za stałym porządkiem. Kto rozumie podstawową logikę i krótko się umawia, pewnie wchodzi do gry.',
  },
  'Umawianie się',
  'Debel żyje z porozumienia. Dwoje graczy, którzy ze sobą rozmawiają, lepiej pokrywa pole i popełnia mniej błędów niż dwoje, którzy w milczeniu grają obok siebie. Rozmowa jest w deblu częścią gry, nie sprawą uboczną.\n\nPorozumienie ma trzy proste momenty. Przed punktem ustalacie krótko najważniejsze: kto serwuje, kto w razie wątpliwości bierze środek, na co uważacie? Jedno zdanie wystarczy. W czasie wymiany krótkie okrzyki — „Moja!", „Twoja!", „Zostaw!" — pomagają partnerowi szybko zdecydować. A między punktami dajecie sobie zwięzły, przyjazny feedback: „Grajmy więcej na jego bekhend".\n\nRównie ważne jak co, jest jak. Debel to współdziałanie, nie przeciwdziałanie. Gdy partner popełni błąd, dodające otuchy „Nic się nie stało, następna!" pomaga bardziej niż krytyka. Para, która się nawzajem podnosi, gra lepiej niż taka, która robi sobie wyrzuty. Zostań głośny, zostań pozytywny.\n\nNajważniejsze to w ogóle rozmawiać. Wielu początkujących gra w ciszy z nieśmiałości — i oddaje tym największą zaletę debla.\n\nDwoje, którzy razem niosą ciężki mebel, wołają do siebie „W lewo!", „Stój!", „Dalej!". Bez tych słów potykają się. Z nimi niosą bez trudu.',
  'Pomyśl o swoim ostatnim deblu: rozmawialiście ze sobą, czy graliście w milczeniu obok siebie? Postanów sobie na następny raz trzy proste rzeczy: przed punktem krótko ustalić najważniejsze, w czasie wymiany wołać „Moja!"/„Twoja!", a po błędzie partnera zareagować dodając otuchy zamiast krytykować. Obserwuj, czy jako zespół lepiej gracie razem, gdy rozmawiacie.',
  'Zostawiać sobie miejsce',
  'Dwoje graczy na jednym polu potrzebuje przestrzeni dla siebie nawzajem. Kto nie wchodzi partnerowi w drogę, gra pewniej i szybciej — i unika zderzeń, które bolą i kosztują punkty. Zostawianie sobie miejsca to kwestia ruchu.\n\nMyśl przewodnia to poruszać się względem siebie. Idzie partner do przodu, ty zostajesz z tyłu; ciągnie w jedną stronę, ty idziesz w drugą. Wspólnie wypełniacie pole, nie nakładając się na siebie. Gdy jeden bierze piłkę, drugi świadomie schodzi z drogi i kryje zwalniającą się przestrzeń.\n\nPomaga przy tym jasny obraz: wyobraź sobie, że ty i partner jesteście połączeni niewidzialną liną. Poruszy się jeden, reaguje drugi. Lina trzyma was w dobrej odległości — dość blisko, by się uzupełniać, dość daleko, by sobie nie przeszkadzać.\n\nWłaśnie przy piłce w środku uskok jest ważny. Gdy tylko jasne jest, kto ją bierze (przez okrzyk), drugi natychmiast robi miejsce, zamiast z odruchu też iść. Tak ten, kto uderza, dostaje wolną drogę.\n\nDwoje rowerzystów jadących obok siebie instynktownie trzyma odstęp i odbija od siebie, gdy robi się ciasno. Tak samo dajecie sobie w deblu przestrzeń — automatycznie i względem siebie.',
  {
    titel: 'Na niewidzialnej linie',
    ziel: 'Poruszać się względem siebie i świadomie zostawiać sobie miejsce.',
    schritte: [
      'Poruszajcie się we dwoje po polu i wyobraźcie sobie, że jesteście połączeni niewidzialną liną.',
      'Idzie jeden do przodu, drugi zostaje z tyłu; ciągnie jeden w bok, drugi uskakuje w drugą stronę.',
      'Niech ktoś podaje wam piłki: kto bierze piłkę, woła; drugi natychmiast uskakuje i kryje zwalniającą się przestrzeń.',
      'Zadbajcie o to, by zostać dość blisko dla uzupełniania, ale dość daleko bez przeszkadzania.',
      'Obserwujcie, czy zdarzają się jeszcze niedoszłe zderzenia, i dopasujcie odstęp.',
    ],
    selbstkontrolle: 'Poruszacie się względem siebie, czy wchodzicie sobie w drogę? Czy drugi uskakuje, gdy tylko jasne jest, kto bierze piłkę? Niewidzialna lina trzyma was w dobrej odległości — dość blisko do uzupełniania, dość daleko bez zderzeń.',
    abschluss: 'Zostawianie sobie miejsca czyni debla pewnym i płynnym. Kto porusza się względem partnera, unika zderzeń i lepiej pokrywa pole.',
  },
];

const r1 = insertPl('data/bausteine.ausruestung-grundlagen.json', AUSRUESTUNG);
const r2 = insertPl('data/bausteine.doppel-beginner.json', DOPPEL);
console.log(`Ring 4 pl: ausruestung ${r1.knoten} + doppel ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
