// Ring 10 (pl): herkunftsreine TEN/SQ-Deltas — delta-tennis (16) + delta-squash (12) = 28 Knoten
// (je anzeigetitel + erklaerteil, delta-typisch ohne Übungsteil). Damit gesamter Baustein-Pool + alle Deltas polnisch.
import { insertPl } from './pl-core.mjs';

const TENNIS = [
  'Chwyt — dla graczy przechodzących z tenisa',
  'W tenisie stale zmieniasz chwyt: jeden do forhendu, inny do bekhendu, jeszcze inny do serwisu i woleja. Ta zmiana siedzi w tobie głęboko — i właśnie ją tutaj odkładasz. W crossmintonie jest jeden jedyny chwyt do wszystkiego.\n\nDobra wiadomość: ten jeden chwyt już znasz. Crossmintonowy chwyt uniwersalny to praktycznie twój chwyt kontynentalny — chwyt jak przy uścisku dłoni z V między kciukiem a palcem wskazującym, którego i tak używasz do serwisu, woleja i uderzenia nad głową. Nie musisz więc uczyć się nowego chwytu, lecz tylko używać znanego do wszystkiego.\n\nCo odkładasz, to dwie rzeczy. Po pierwsze samo zmienianie — tu nie ma zmiany chwytu, speeder jest na to zbyt szybki. Po drugie skrajne chwyty forhendowe (semi-western, western), którymi w tenisie nadajesz topspin. Tutaj nie działają; zostajesz na neutralnym chwycie jak przy uścisku dłoni.\n\nTwój oburęczny bekhend to osobny temat — więcej o tym w module o bekhendzie.\n\nMały test: obserwuj dłoń uderzającą między uderzeniami. Czy obraca się, by szukać chwytu forhendowego lub bekhendowego? To znaczy, że wciąż zmieniasz na modłę tenisową. Celem jest, by ręka pozostawała spokojnie na tym jednym chwycie uniwersalnym — chwycie, który znasz już z serwisu.',
  'Serwis — dla graczy przechodzących z tenisa',
  'Przy serwisie musisz odłożyć na bok swoje najważniejsze tenisowe uderzenie. Twój serwis tenisowy idzie nad głową: podrzucić piłkę, wyciągnąć się, trafić z góry. Serwis crossmintonowy to coś całkiem innego — gra się go od dołu.\n\nTutaj wypuszczasz speedera z wolnej ręki i trafiasz go od dołu, przy czym cały speeder jest w chwili trafienia poniżej twojej dłoni uderzającej. Żadnego podrzucania, żadnego wyciągania w górę, żadnego uderzenia z góry. Ruch biegnie płasko i od dołu, z tylnej strefy twojego pola. Naucz się go najlepiej od nowa, tak jak opisano w module podstawowym — twój serwis tenisowy tu ci nie pomaga.\n\nAle nie wyrzucaj tego ruchu. Twój serwis tenisowy to skarb, który wydobędziesz później: jego ruch — stać bokiem, wyciągnąć się w górę, użyć nadgarstka w najwyższym punkcie — przenosi się niemal jeden do jednego na uderzenie nad głową, którego uczysz się na poziomie zaawansowanym. To, co tu nie pasuje, tam stanie się twoją zaletą.\n\nMały test: łapiesz się na tym, że chcesz podrzucić speedera i trafić nad głową? To odruch tenisowy. Serwis crossmintonowy pozostaje nisko — speeder opada, trafiasz go poniżej dłoni.',
  'Drive forhendowy — dla graczy przechodzących z tenisa',
  'Twój forhend tenisowy to potężne, długie uderzenie: duży zamach, pełne przeprowadzenie, często muśnięte od dołu do góry dla topspinu. Jest zbudowany na ciężką piłkę na dużym korcie, z czasem po odbiciu. Dwie rzeczy z tego musisz tu dostosować.\n\nPo pierwsze długość. Crossminton jest szybki i ciasny. Duży zamach jak w tenisie przychodzi o wiele za późno — speedera dawno już nie ma. Zrób wszystko zwięźlejsze: krótki zamach, oszczędne uderzenie, punkt kontaktu wyraźnie przed ciałem. Siła przyjdzie później ze strzału nadgarstka, którego uczysz się na poziomie zaawansowanym, nie z długiego zamachu.\n\nPo drugie odbicie od podłoża, którego tu nie ma. W tenisie czekasz, aż piłka się odbije, i trafiasz ją na wygodnej wysokości. Speeder się nie odbija — grasz go z powietrza, gdy opada. Twój punkt kontaktu i timing przesuwają się tym samym: trafiasz wcześniej, w powietrzu, często w locie.\n\nTwój forhend tenisowy to szeroko zamachnięte uderzenie wiosłem. Twój forhend crossmintonowy to krótki, szybki pchnięcie. To samo ramię, ale o wiele krótsza droga.\n\nMały test: zamachujesz się szeroko i czekasz na odbicie? To znaczy, że wciąż grasz w tenisa. Celem jest zwięzłe uderzenie przed ciałem, trafione z powietrza.',
  'Bekhend — dla graczy przechodzących z tenisa',
  'Jeśli jak większość tenisistów grasz bekhend oburęczny, to tutaj twoja największa przestawka. Crossmintona gra się zawsze jednorącz — jeden chwyt, jedna ręka, także na bekhendzie. Twoja druga ręka schodzi z rakiety.\n\nZ początku czuje się to słabo i obco. Twój oburęczny bekhend czerpał stabilność i siłę z drugiej ręki, która prowadziła uderzenie. Gdy odpada, ramię wydaje się najpierw pozostawione samo. To mija z powtórzeniami — bekhend jednoręczny ma własną stabilność, którą budujesz.\n\nDobra strona: crossmintonowy chwyt uniwersalny czyni bekhend jednoręczny łatwiejszym niż w tenisie. Zostajesz na tym samym chwycie jak przy uścisku dłoni co przy forhendzie, zamiast obracać w osobny chwyt bekhendowy — ruch to odbity lustrzanie forhend, jak opisano w module podstawowym.\n\nI jak przy forhendzie obowiązuje: krócej i z powietrza. Zwięzły zamach, punkt kontaktu przed ciałem, żadnego czekania na odbicie. Szczegóły znajdziesz we wskazówce do forhendu.\n\nMały test: czy twoja druga ręka odruchowo sięga do rakiety, gdy piłka przychodzi na bekhend? To znaczy, że odruch tenisowy wciąż jest. Celem jest spokojny bekhend jednoręczny na chwycie uniwersalnym.',
  'Uderzenie nad głową — dla graczy przechodzących z tenisa',
  'Teraz opłaca się twój serwis tenisowy. Uderzenie nad głową to uderzenie, do którego twoje tenisowe doświadczenie jest jak stworzone — tu wnosisz prawdziwą zaletę.\n\nRuch znasz ze swojego serwisu niemal jeden do jednego: stać bokiem, wolne ramię wskazuje w górę, wyciągasz się do najwyższego punktu i na końcu włączasz rotację przedramienia i nadgarstek — pronację i strzał, które nadają twojemu serwisowi siłę. Ta mechanika przenosi się wprost. Ledwie musisz się jej uczyć na nowo.\n\nDwie rzeczy przestawiasz. Po pierwsze nie ma podrzutu piłki: speeder przychodzi od przeciwnika, musisz dopasować swój punkt kontaktu do jego lotu, zamiast sam sobie go podrzucać. Po drugie nie ma siatki ani głębokiej linii końcowej przeciwnika w tenisowej odległości. Zamiast unosić piłkę wysoko nad siatkę, niesiesz ją płaściej i daleko ponad strefą neutralną głęboko w pole przeciwnika. Do tego dochodzi sztywniejszy, lżejszy sprzęt.\n\nMały test: grasz uderzenie nad głową wysokim łukiem swojego serwisu tenisowego, jakbyś musiał pokonać siatkę? To znaczy, że wciąż niesie cię tenisowy tor lotu. Celem jest płaściejszy, daleki tor, który mostem przechodzi ponad strefą — dokładnie twoim znajomym ruchem serwisu.',
  'System pracy nóg — dla graczy przechodzących z tenisa',
  'Niektóre z twoich tenisowych ruchów pomagają ci tutaj: split-step przed uderzeniem, powrót do pozycji wyjściowej, eksplozywny zryw. Te podstawy wnosisz ze sobą. Co przeuczasz, to przestrzeń, w której je stosujesz.\n\nTwoja tenisowa praca nóg jest zbudowana wokół dużego kortu z siatką. Myślisz od linii końcowej, kryjesz szerokie pole długimi drogami, ustawiasz się do siatki i wracasz za linię końcową. Ta mapa głęboko kształtuje twój ruch.\n\nCrossmintona gra się w małym, bezsiatkowym kwadracie, który bronisz z jego środka — na wszystkie cztery narożniki równo. Nie ma linii końcowej, do której się orientujesz, nie ma siatki, do której się ustawiasz, a drogi są o wiele krótsze i szybsze. Twój ruch układa się na nowo: precz od szerokiej, zwróconej do siatki gry od linii końcowej, ku zwięzłemu, symetrycznemu kwadratowi z czterema równorzędnymi narożnikami.\n\nW tenisie obgrywasz szeroką scenę z tyłu. W crossmintonie stoisz w środku małego ringu i kryjesz go na wszystkie strony. Te same kroki, ale całkiem inna mapa.\n\nMały test: dryfujesz w tył do wyobrażonej linii końcowej albo ustawiasz się do wyobrażonej siatki? To znaczy, że wciąż niesie cię tenisowa mapa. Celem jest równomierne krycie wszystkich czterech narożników ze środka kwadratu.',
  'Serwis i kolejność w grze podwójnej — dla graczy przechodzących z tenisa',
  'Serwis w deblu działa w crossmintonie całkiem inaczej niż w tenisie — i ta przestawka wymaga przyzwyczajenia.\n\nW deblu tenisowym serwujesz przez całego gema, na przemian z pola równowagi i pola przewagi, po skosie przez siatkę w pole serwisowe. Serwis zostaje przy tobie na dłuższą chwilę, a twoja strona jest ustalona. Ta struktura siedzi głęboko.\n\nW crossmintonie prawo serwisu wędruje natomiast w stałej kolejności przez wszystkich czterech graczy: każdy jest po kolei na kolejce, nikt nie serwuje przez całego gema. Do tego dochodzi: nie ma siatki ani skośnego pola serwisowego — serwujesz od dołu ze strefy serwisowej ponad strefą neutralną w pole przeciwnika, a cały speeder musi być przy tym w chwili trafienia poniżej twojej dłoni uderzającej.\n\nCo odkładasz, to dwie rzeczy: wyobrażenie, że zatrzymujesz serwis przez kilka punktów, i skośną logikę ponad siatką. Co przejmujesz, to rotację po kolei przez wszystkich czterech graczy i płaski serwis od dołu ze strefy.\n\nZamiast jak w tenisie grać całą serię serwisów, przekazujesz prawo serwisu po kolei dalej jak kartę, która obchodzi krąg.',
  'Cel gry — dla graczy przechodzących z tenisa',
  'Cel gry brzmi dla ciebie z tenisa znajomo — wprowadzić piłkę w pole przeciwnika —, ale centralny punkt odniesienia odpada, i to zmienia twoje myślenie.\n\nW tenisie miarą jest siatka. Grasz ponad siatką, celujesz tuż nad nią, a środkowe pole — ziemię niczyją (no man’s land) — omijasz. Cały twój podział przestrzeni jest zorientowany na siatkę.\n\nW crossmintonie nie ma siatki. Na jej miejscu stoi strefa neutralna: wolna przestrzeń między dwoma polami, w którą speeder nie może wpaść. Grasz ponad odległością w wyraźnie ograniczony kwadrat, nie ponad przeszkodą. Zbyt krótka piłka ląduje w strefie neutralnej zamiast w siatce — i jest tak samo stracona.\n\nCo odkładasz, to orientację na siatkę: żadnego dobiegania do siatki, żadnej gry tuż nad krawędzią. Co przejmujesz, to myślenie w strefie neutralnej i kwadracie docelowym — speeder musi pewnie przekroczyć strefę i wylądować w polu przeciwnika.\n\nZamiast grać ponad murem jak w tenisie, grasz ponad rowem. Kto celuje za krótko, wpada do niego — także bez siatki.',
];

const SQUASH = [
  'Chwyt — dla graczy przechodzących ze squasha',
  'Przy chwycie ledwie masz coś do przestawienia — przeciwnie, wnosisz dokładnie to, na czym inni najpierw się potykają. W squashu grasz od dawna jednym jedynym chwytem do wszystkiego: chwyt jak przy uścisku dłoni z V między kciukiem a palcem wskazującym, do forhendu jak i bekhendu tak samo, bez zmiany. To praktycznie crossmintonowy chwyt uniwersalny. Największą przeszkodę masz już za sobą.\n\nDwie drobne subtelności dostosowujesz. Po pierwsze powierzchnię rakiety: w squashu trzymasz rakietę lekko otwartą, tak że po obu stronach widzisz naciąg — pomaga ci to tam w podcinaniu i grze z narożników. W crossmintonie bierzesz powierzchnię najpierw bardziej neutralnie, bo speedera trafiasz przeważnie pełno i płasko. Świadome podcięcie zostawiasz sobie na później.\n\nPo drugie nadgarstek: w squashu jest często postawiony do góry, główka rakiety nad nadgarstkiem. Tutaj trzymasz go na początku spokojniej i bardziej neutralnie. Świadome użycie nadgarstka — bat — przychodzi na poziomie zaawansowanym, dopasowane do sprzętu crossmintonowego.\n\nMały test: czy przy spokojnym trzymaniu widzisz po obu stronach swój naciąg jak w squashu? To znaczy, że powierzchnia jest jeszcze otwarta. Celem jest neutralna powierzchnia na tym znajomym jednym chwycie — którego w gruncie rzeczy używasz już całe swoje squashowe życie.',
  'Zrozumieć cel gry — dla graczy przechodzących ze squasha',
  'Tu leży twoja największa przestawka — i jest ona kwestią całego myślenia przestrzennego, nie techniki. Squash to gra o ścianę. Grasz piłkę o ścianę przednią, wykorzystujesz ściany boczne i tylne do kątów, i dzielisz z przeciwnikiem tę samą przestrzeń. Całe twoje rozumienie gry jest zbudowane wokół ścian i odbić.\n\nCrossminton nie ma ścian. Między tobą a przeciwnikiem leży strefa neutralna, a za nią własne, oddzielone pole, w które grasz speedera wprost. Żadna piłka nie wraca od ściany, nie ma boasta, nie ma kątów przez ścianę boczną, nie ma dzielonego pola gry. Grasz prosto na drugą stronę, w kwadrat przeciwnika.\n\nTo głębokie przestawienie. Zamiast myśleć „jak zagrać piłkę o ścianę, by była trudna dla przeciwnika", myślisz teraz „jak przenieść speedera ponad strefą wprost w narożnik, którego przeciwnik już nie dosięgnie". Twój obraz celu wędruje od ściany do pola przeciwnika.\n\nW squashu oboje gracie o tę samą ścianę, jak dwoje, którzy grają piłką o mur domu. W crossmintonie stoicie naprzeciw siebie jak ponad rowem, i każdy broni własnego kawałka ziemi. Ta sama rakieta, ale całkiem inna mapa gry.\n\nMały test: szukasz w głowie jeszcze ściany, kąta, odbicia? To znaczy, że wciąż niesie cię squashowe myślenie. Celem jest bezpośrednie spojrzenie na pole przeciwnika ponad strefą.',
  'Serwis — dla graczy przechodzących ze squasha',
  'Twój serwis squashowy celuje w ścianę przednią: grany z pola serwisowego tak, by piłka przez ścianę trafiła w tylne pole przeciwnika. To wyobrażenie tutaj odkładasz, bo nie ma ściany.\n\nSerwis crossmintonowy gra się od dołu i idzie wprost ponad strefą neutralną w pole przeciwnika. Wypuszczasz speedera z wolnej ręki i trafiasz go od dołu, przy czym cały speeder jest w chwili trafienia poniżej twojej dłoni uderzającej, z tylnej strefy twojego pola. Żadnego kontaktu ze ścianą, żadnych kątów — bezpośredni, płaski tor na drugą stronę.\n\nTo nowy ruch; naucz się go od nowa, tak jak stoi w module podstawowym. Twój serwis squashowy tu ci nie pomaga, bo cały jego sens — piłka przez ścianę przednią — tutaj odpada.\n\nCo ci pomaga, to twoje wyczucie precyzji i umiejscowienia ze squasha. Gdy tylko opanujesz nowy ruch, możesz serwis celowo zakładać — celowe umiejscowienie opanowujesz z gry o ścianę już dobrze.\n\nMały test: szukasz przy serwisie jeszcze punktu na wyobrażonej ścianie? To znaczy, że wciąż myślisz w squashowej przestrzeni. Celem jest bezpośredni, płaski tor ponad strefą w pole przeciwnika.',
  'Drive forhendowy — dla graczy przechodzących ze squasha',
  'Twój forhend squashowy wnosi wiele przydatnego: zwięzłe uderzenie, dobre czucie piłki, szybkie reakcje. Dwie rzeczy przestawiasz, i obie wiszą na brakującej ścianie.\n\nPo pierwsze cel. W squashu grasz drive’a nisko i ciasno wzdłuż ściany bocznej do ściany przedniej — piłka zbiega w dół ściany. W crossmintonie nie ma ściany, wzdłuż której prowadzisz piłkę. Grasz płasko i wprost ponad strefą neutralną w pole przeciwnika. Twój obraz celu wędruje od linii ściany do narożnika w kwadracie przeciwnika.\n\nPo drugie powierzchnia rakiety. W squashu otwierasz powierzchnię i często podcinasz piłkę, by przynieść ją nisko i kontrolowanie do ściany. W crossmintonie trafiasz speedera do podstawowego drive’a płaściej i pełniej. Podcięcie zostawiasz sobie jako osobne narzędzie na później — tam twoje squashowe czucie się wtedy opłaca.\n\nDobra strona: twój zwięzły zamach dobrze pasuje. Inaczej niż tenisista nie musisz niczego skracać — squash gra się podobnie ciasno i szybko. Przestawiasz przede wszystkim cel i powierzchnię.\n\nMały test: prowadzisz piłkę jeszcze wzdłuż wyobrażonej ściany albo mocno ją podcinasz? To znaczy, że wciąż niesie cię gra o ścianę. Celem jest płaski, pełny drive wprost w pole przeciwnika.',
  'Pozycja centralna — dla graczy przechodzących ze squasha',
  'Tu wnosisz jedną ze swoich największych sił. W squashu po każdym uderzeniu wracasz do „T" — centralnego punktu, z którego najszybciej dosięgasz wszystkich narożników. Ten powrót do środka dawno wszedł ci w krew. Właśnie ten nawyk jest w crossmintonie na wagę złota.\n\nPozycja centralna w crossmintonie działa na tej samej zasadzie co twoje „T": po każdym uderzeniu wracasz do środka, bo stamtąd drogi do wszystkich narożników są najkrótsze. Nie musisz uczyć się tej zasady na nowo — tylko ją przenosisz.\n\nJedną rzecz ustawiasz na nowo. Twoje „T" w squashu leży w polu, które obgrywasz wspólnie z przeciwnikiem, i jesteś zwrócony do ściany przedniej. W crossmintonie stoisz sam w swoim własnym kwadracie i kryjesz cztery równorzędne narożniki wokół siebie — jest symetryczne dookoła, nie ma przodu do ściany. Twój środek to centrum tego kwadratu, i ustawiasz się do przeciwnika ponad strefą, nie do ściany.\n\nTwoje squashowe „T" było punktem zaczepienia w dzielonej przestrzeni, ze spojrzeniem do przodu, do ściany. Twój crossmintonowy środek to punkt środkowy własnego ringu, który kryjesz na wszystkie strony równo. Ten sam nawyk powrotu, tylko w bardziej okrągłej geometrii.\n\nMały test: czy po powrocie do środka ustawiasz się jeszcze do przodu, jakby stała tam ściana? To znaczy, że wciąż niesie cię myślenie o „T". Celem jest symetryczny środek, z którego wszystkie cztery narożniki dosięgasz równie szybko.',
  'Podcięcie i tor lotu — dla graczy przechodzących ze squasha',
  'Podcięcie jest dla większości graczy zaawansowanym nowym terenem — dla ciebie to znajomy grunt. W squashu stale podcinasz piłkę, otwartą powierzchnią rakiety, by ją kontrolować, trzymać nisko i wydobywać z narożników. Czucie muskania piłki zamiast trafiania jej pełno wnosisz ze sobą.\n\nTo czucie przenosisz wprost. Tam gdzie inni muszą dopiero uczyć się muskać speedera z boku, by nadać mu rotację, sięgasz po wyćwiczony ruch. Twoja otwarta powierzchnia, twoje czucie nadgarstka przy podcinaniu — wszystko to pomaga ci tutaj.\n\nDwa dostosowania są. Speeder zachowuje się inaczej niż piłka squashowa: lżejszy, z silniejszym oporem powietrza, bez ściany, wzdłuż której biegnie dalej. Efekt twojego podcięcia pokazuje się więc w torze lotu przez powietrze, nie w zachowaniu przy ścianie. I stosujesz podcięcie tutaj oszczędniej niż w squashu — kosztuje nieco kontroli i opłaca się jako celowe urozmaicenie, nie jako stały środek.\n\nTwoje squashowe podcięcie oswajało piłkę przy ścianie. Twoje crossmintonowe podcięcie zakrzywia tor lotu przez powietrze. Ten sam ruch ręki, inny efekt.\n\nMały test: tworzysz podcięcie bez wysiłku ze znajomego nadgarstka? To znaczy, że niesie cię twoje squashowe doświadczenie. Uważaj tylko, by stosować je celowo i oszczędnie i mimo podcięcia trafiać speedera kontrolowanie.',
];

const r1 = insertPl('data/bausteine.delta-tennis.json', TENNIS);
const r2 = insertPl('data/bausteine.delta-squash.json', SQUASH);
console.log(`Ring 10 pl: delta-tennis ${r1.knoten} + delta-squash ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
