// Ring 3 (pl): restliche Beginner-Ebene — Taktik (20) + Mentales (15) +
// Athletik/Kondition (18) = 53 Knoten. anzeigetitel spiegeln die Ring-0-Labels.
import { insertPl } from './pl-core.mjs';

const TAKTIK = [
  'Zrozumieć cel gry',
  'Zanim pomyślisz o taktyce, musisz wiedzieć, o co w wymianie w ogóle chodzi. Brzmi prosto i w gruncie rzeczy takie jest: zdobywasz punkt, gdy speeder ląduje w polu przeciwnika — albo gdy przeciwnik popełni błąd.\n\nWłaśnie w tym tkwi cała taktyka. Bo te dwie drogi do punktu nie są równo rozłożone. Aktywnie posłać speedera w pole tak, by przeciwnik już go nie dosięgnął, jest trudno. Doprowadzić przeciwnika do sytuacji, w której to on popełni błąd, jest często łatwiej. Dobra taktyka rzadko oznacza więc efektowne kończenie. Oznacza dawanie przeciwnikowi trudniejszego zadania.\n\nObraz na to: wyobraź sobie wymianę jako próbę sił, w której oboje starają się wytrącić przeciwnika z równowagi. Wygrywa ten, kto sam pozostaje w równowadze i wyprowadza z niej drugiego — nie ten, kto uderza najmocniej.\n\nI tu wchodzi w grę to, co szczególne w crossmintonie. Nie ma siatki. Między dwoma polami leży strefa neutralna, w której speeder nie może wylądować. Pokonujesz więc odległość, nie wysokość jak w badmintonie — a za nią czeka wyraźnie ograniczone pole docelowe. Całe twoje myślenie taktyczne kieruje się zatem na to pytanie: jak przenieść speedera czysto ponad strefą w pole, którego przeciwnik już nie obroni?\n\nWszystko dalsze — pozycja, długość, czytanie przeciwnika — to odpowiedzi właśnie na to pytanie.',
  'Wróć myślami do swojego ostatniego meczu albo zwróć na to świadomie uwagę w następnym: ile z twoich punktów padło po własnym, aktywnym trafieniu — a ile dlatego, że przeciwnik posłał speedera na aut lub w strefę? Większość początkujących wyraźnie przecenia tę pierwszą drogę. Jeśli policzysz uczciwie, zobaczysz, o ile częściej do punktu prowadzi ta druga. Świadomość tej liczby zmienia to, jak grasz.',
  'Pozycja centralna i kontrola pola',
  'Jest na twoim polu miejsce, które wygrywa ci więcej meczów niż jakiekolwiek pojedyncze uderzenie: środek. Z pozycji centralnej twoje drogi do wszystkich narożników są najkrótsze. Kto tam stoi, wszędzie zdąży na czas. Kto stoi gdzie indziej, gdzieś się spóźni.\n\nDlatego powrót do środka po każdym uderzeniu nie jest samym tylko bieganiem — to decyzja taktyczna. Każdy speeder wyciąga cię ze środka, w narożnik, do przodu, do tyłu. I właśnie w tym momencie twoje pole stoi otworem. Sztuka polega na tym, by po uderzeniu natychmiast wrócić, zanim przeciwnik zagra w lukę.\n\nMyśl o środku jak o swoim domu. Wychodzisz, by odebrać piłkę, i od razu wracasz. Im dłużej zostajesz na zewnątrz, tym większe otwarte drzwi za tobą.\n\nW crossmintonie ma to szczególne znaczenie, bo pole jest kwadratem, a przeciwnik może posłać speedera w każdy narożnik. Nie ma wąskiego pasa jak w grze przy siatce — środek to jedyne miejsce, z którego wszystkie cztery narożniki osiągasz równie szybko.',
  'Zwróć w następnym meczu uwagę na jedną jedyną rzecz: czy po każdym uderzeniu wracasz do środka, czy zostajesz tam, gdzie właśnie trafiłeś? Większość traci punkty, bo po dobrym uderzeniu przystaje na chwilę i cieszy się własną piłką — i właśnie wtedy speeder ląduje w otwartym narożniku. Świadome „powrót do środka" po każdym uderzeniu zmienia twoją grę bardziej niż jakakolwiek nowa technika.',
  'Długość i głębokość jako najprostsza broń',
  'Masz broń, która nie wymaga mocnego uderzenia, a mimo to działa od razu: długość. To, gdzie posyłasz speedera, decyduje często bardziej niż to, jak mocno go uderzasz.\n\nPowód tkwi w pozycji centralnej. Twój przeciwnik, tak samo jak ty, chce stać w środku swojego pola — stamtąd najszybciej dosięga każdego narożnika. Gdy zagrasz speedera głęboko do tyłu, wypychasz go z tego środka, daleko w tył. Teraz jego przód stoi otworem. Następny speeder, zagrany krótko przed niego, staje się dla niego pogonią.\n\nTo najprostszy wzorzec taktyczny w crossmintonie: głęboko, potem krótko. Wyciągasz przeciwnika do tyłu i kładziesz następną piłkę przed nim. Albo odwrotnie — ściągasz go do przodu, a potem grasz długo ponad nim. W obu przypadkach wygrywasz dzięki odległości, którą przeciwnik musi pokonać — nie dzięki sile.\n\nMyśl o sobie jak o kimś, kto puszcza psa na długiej smyczy w koło. Ty stoisz spokojnie w środku, przeciwnik biega. Im dłuższe robisz jego drogi, tym prędzej się spóźni — a przeciwnik, który się spóźnia, popełnia błędy.\n\nPonieważ w crossmintonie nie ma siatki, głęboka piłka jest szczególnie skuteczna. Nie musisz szukać wysokości, by zagrać długo — niesiesz speedera płasko i daleko przez strefę neutralną aż w tylną część pola przeciwnika. Płaska, długa piłka jest trudniejsza do odczytania i trudniejsza do odbicia niż wysoka.',
  {
    titel: 'Trafiać w głębię',
    ziel: 'Niezawodnie posyłać speedera w tylną część pola przeciwnika.',
    schritte: [
      'Wyłóż sobie w tylnej tercji pola przeciwnika linię celu lub ręcznik jako znacznik.',
      'Graj z własnego pola serwisy i drive’y celowo za ten znacznik.',
      'Policz, ile z dziesięciu speederów ląduje za znacznikiem.',
      'Podnoś sobie poprzeczkę przez kilka rund — najpierw forhend, potem bekhend.',
    ],
    selbstkontrolle: 'Zwróć uwagę, czy głębię osiągasz płaskim, niesionym uderzeniem, czy musisz podrzucać speedera wysoko. Płaska, długa piłka to cel — dociera szybciej i daje przeciwnikowi mniej czasu.',
  },
  'Czytanie bekhendu przeciwnika',
  'Do tej pory chodziło o ciebie — twoją pozycję, twoją długość. Teraz po raz pierwszy kierujesz wzrok na przeciwnika jako kogoś ze słabością, którą możesz wykorzystać. A najczęstsza słabość ma swoją nazwę: bekhend.\n\nU większości graczy strona bekhendowa jest tą mniej pewną. Osiąga mniej tempa, mniej kontroli, mniejszy zasięg niż forhend. To reguła, nie wyjątek — również u ciebie samego, jak wiesz z części technicznej. Właśnie dlatego jedną z najbardziej niezawodnych decyzji taktycznych w ogóle jest granie speedera raz za razem na stronę bekhendową przeciwnika.\n\nEfekt jest podwójny. Po pierwsze dostajesz słabsze, krótsze odbicia, które łatwiej możesz poddać presji. Po drugie — i to subtelniejsze — zmuszasz przeciwnika, by chronił swoją słabszą stronę. Przesuwa się, by kryć bekhend, i odsłania przy tym stronę forhendową. Teraz masz dwa cele zamiast jednego.\n\nPukasz raz za razem do tych samych drzwi. Albo ustąpią — nadejdzie słabe odbicie —, albo przeciwnik stanie przed nimi i zostawi drugie drzwi bez straży.\n\nTo istota gry taktycznej, nie nieuczciwa sztuczka: rozpoznać słabość przeciwnika i cierpliwie ją rozgrywać, zamiast liczyć na jedno wielkie uderzenie.',
  {
    titel: 'Trafiać w narożnik bekhendowy',
    ziel: 'Celowo i wielokrotnie posyłać speedera na słabszą stronę przeciwnika.',
    schritte: [
      'Zaznacz w polu przeciwnika narożnik bekhendowy (dla praworęcznego lewy tylny narożnik) ręcznikiem.',
      'Graj z różnych pozycji celowo speedery w ten narożnik — najpierw serwisy, potem drive’y.',
      'Policz swoje trafienia na dziesięć prób.',
      'Podnoś trudność: graj na przemian jedną piłkę w narożnik bekhendowy i jedną krótko przed przeciwnika, by ćwiczyć wzorzec „związać słabszą stronę, potem otworzyć".',
    ],
    selbstkontrolle: 'Zadbaj o to, by zagrywać w narożnik pewną, kontrolowaną piłką, nie ryzykownym winnerem. Taktyka bekhendowa żyje z powtarzania, nie z pojedynczego perfekcyjnego uderzenia.',
  },
  'Taktyczne wykorzystanie serwisu',
  'Serwis to jedyne działanie w całej grze, które kontrolujesz w pełni. Żaden przeciwnik cię nie naciska, speeder spoczywa wyłącznie w twojej dłoni, ty wybierasz moment, cel i tempo. Zmarnować tę jedną podarowaną okazję byłoby rozrzutnością.\n\nSerwis zgodny z przepisami po prostu wprowadza speedera w pole przeciwnika. Serwis taktyczny wprowadza go tam, gdzie sprawia przeciwnikowi kłopot. Masz do tego dwa pokrętła: cel i urozmaicenie.\n\nPrzy celu obowiązuje to, co już znasz: strona bekhendowa. Serwis głęboko w narożnik bekhendowy zmusza przeciwnika już na początku wymiany do jego najmniej pewnego uderzenia. Często dostajesz słabe odbicie, które od razu możesz poddać presji.\n\nPrzy urozmaiceniu obowiązuje: nie stań się przewidywalny. Jeśli każdy twój serwis jest taki sam — ta sama długość, ten sam cel, to samo tempo — przeciwnik się do niego dostraja. Mieszaj serwisy głębokie i krótsze, zmieniaj cel. Sama nieprzewidywalność wywołuje błędy.\n\nSerwis to twój pierwszy ruch w szachach. Możesz go zmarnować, wykonując wciąż to samo posunięcie — albo otworzyć nim plan.',
  'Obserwuj w następnym meczu własne serwisy: czy wszystkie są takie same, czy świadomie je zmieniasz? I dokąd serwujesz — po prostu w pole, czy celowo na słabszą stronę? Większość początkujących serwuje tylko po to, by rozpocząć wymianę. Kto zamiast tego wiąże z każdym serwisem zamiar, zdobywa punkty, zanim wymiana się na dobre zacznie.',
  'Unikanie błędów: niedoceniana taktyka',
  'Na koniec być może najważniejsze taktyczne spostrzeżenie — i to, w które większości początkujących najtrudniej uwierzyć: na twoim poziomie zdobywasz większość punktów nie dlatego, że wielko trafiasz. Zdobywasz je, bo przeciwnik posyła speedera na aut lub w strefę. I odwrotnie — większość punktów tracisz przez własne błędy.\n\nBrzmi to otrzeźwiająco, ale to dobra wiadomość. Bo swój wskaźnik błędów możesz obniżyć od razu — całkiem bez lepszej techniki. Musisz tylko pewniej wybierać, co grasz.\n\nGrać pewnie znaczy: kłaść speedera z zapasem do środka, nie na linię. Wybierać kąt, który zostawia ci margines, nie ten efektowny. Lepiej odbić jedną piłkę więcej niż próbować ryzykownego winnera, który trzy razy na cztery ląduje na aucie. Każda piłka, którą pewnie odeślesz, daje przeciwnikowi szansę popełnić swój błąd.\n\nWyobraź sobie, że oboje niesiecie wiadro wody przez tor przeszkód. Wygrywa ten, kto najmniej rozleje — nie ten, kto biegnie najszybciej. Wymiana jest właśnie tym — rywalizacją o to, kto pierwszy straci cierpliwość albo kontrolę.\n\nTo nie znaczy, że nigdy nie masz atakować. To znaczy, że pewność jest twoim ustawieniem podstawowym, a atak wyjątkiem, dla którego nadarza się naprawdę dobra okazja. Kto to odwróci — atak jako reguła, pewność jako wyjątek — oddaje na poziomie początkującego najwięcej punktów.',
  'Policz w następnym meczu świadomie własne błędy — każdego speedera, którego posyłasz na aut lub w strefę. Porównaj tę liczbę z liczbą swoich prawdziwych winnerów. U większości początkujących własne błędy wyraźnie przewyższają winnery. Poznanie tej jednej liczby to najszybsza droga do wygrywania większej liczby meczów — jeszcze przed jakąkolwiek poprawą techniczną.',
  'Taktyczne wykorzystanie serwisu — dla graczy przechodzących z badmintona',
  'Wnosisz przemyślany repertuar serwisów — ale spora jego część celuje w coś, czego tu nie ma. W badmintonie taktyka serwisu kręci się wokół siatki: krótki, nisko trzymany serwis tuż nad krawędzią, cała gra o trzecią piłkę. W crossmintonie to odpada. Nie ma siatki, nie ma krótkiego przedpola — między wami leży strefa neutralna, a twój serwis musi ponad nią, w głębokie pole docelowe.\n\nTwoje wyobrażenie taktyczne przesuwa się tym samym z wysokości na głębię. Już nie „tuż nad i krótko", lecz „płasko, daleko i celnie". Krótki serwis, twoja subtelna broń w badmintonie, traci tutaj swoją rolę. Na jego miejsce wchodzi urozmaicenie przez długość i cel.\n\nCo możesz zachować: zagrywanie na bekhend. Serwis na słabszą stronę przeciwnika działa tu tak samo jak tam — tylko głęboko w narożnik bekhendowy zamiast krótko przy krawędzi siatki.\n\nMały test: jeśli zauważysz, że zakładasz speedera krótko i wysoko, jakbyś musiał pokonać krawędź, wciąż grasz w badmintona. Celem jest płaski, długi serwis, który mostem przechodzi ponad strefą i dociera głęboko.',
];

const MENTALES = [
  'Dlaczego głowa gra razem',
  'Ćwiczyłeś technikę i zrozumiałeś taktykę. A mimo to w grze dzieje się coś dziwnego: w jednej sytuacji udaje ci się wszystko, w następnej — zwykle gdy robi się ważnie — nagle opuszcza cię wyczucie. Rzadko wynika to z twojej techniki. Wynika z głowy.\n\nNa twoim poziomie strona mentalna decyduje o większej liczbie punktów, niż większość sądzi. Piłka, którą na treningu grasz pewnie sto razy, w ciasnym momencie idzie na aut — nie dlatego, że jej nie umiesz. To napięcie zmienia twój ruch. I odwrotnie — zdobywasz punkty, gdy zachowasz spokój, podczas gdy przeciwnik traci nerwy.\n\nTo dobra wiadomość. Bo spokój, koncentracja i radzenie sobie z błędami to nie talenty, które się ma albo nie. To narzędzia, których możesz się nauczyć — tak samo jak uderzenia.\n\nTwoje umiejętności to samochód. Głowa to kierowca. Najlepszy samochód nie dowiezie cię do celu, jeśli kierowca spina się na każdym zakręcie. W kolejnych modułach uczysz się jeździć spokojniej.\n\nJedno na wstępie: nie chodzi o to, by nie mieć nerwów. Zdenerwowanie jest częścią gry, także u zawodowców. Chodzi o to, co z nim robisz.',
  'Pomyśl o sytuacji z ostatniego meczu, w której nie wyszła ci prosta piłka, choć w zasadzie pewnie ją opanowujesz. Co było wtedy inne? Czy było blisko wyniku? Czy właśnie popełniłeś błąd? Czy coś cię rozproszyło? Nie musisz nic rozwiązywać — obserwuj tylko, w jakich momentach opuszczają cię umiejętności. To właśnie te momenty, na które zaraz dostaniesz narzędzia.',
  'Rutyna przed serwisem',
  'Serwis to jedyny moment w grze, który masz w pełni w swoich rękach — żaden przeciwnik cię nie popędza. Właśnie dlatego jest najlepszym miejscem, by zakotwiczyć spokój. Krótka, zawsze taka sama sekwencja czynności przed każdym serwisem daje twojej głowie stały punkt, w którym się wycisza.\n\nTaka rutyna ma trzy części. Małą czynność fizyczną — na przykład dwukrotne obrócenie speedera w dłoni albo jeden głęboki wdech. Myśl, która kieruje twoją uwagę — na zadanie zamiast na wynik: „płasko i długo" zamiast „byle nie błąd". I wyzwalacz, który mówi: teraz zaczynamy — spojrzenie na cel, zanim uderzysz.\n\nDecydujące jest to, by rutyna była krótka i zawsze taka sama. Działa nie dlatego, że jest magiczna. Działa, bo powtarzanie daje twojemu układowi nerwowemu poczucie niezawodności. Za każdym razem wprowadzasz się w ten sam spokojny stan, zanim zagrasz.\n\nPilot przed startem przechodzi listę kontrolną — zawsze tę samą, nawet po tysiącu lotów. Nie z przesądu, lecz dlatego, że stała kolejność zapobiega błędom i porządkuje głowę. Twój serwis zasługuje na tę samą małą listę kontrolną.\n\nWażne: rutyna to nie zwłoka. Trwa kilka sekund i nie może opóźniać serwisu — tylko go porządkuje.',
  'Zbuduj sobie własną rutynę z dokładnie trzech kroków: mała czynność fizyczna, myśl związana z zadaniem, wyzwalacz. Trzymaj ją tak krótką, by zmieściła się w kilku sekundach. Wypróbuj ją na następnym treningu przed każdym serwisem — zawsze tę samą. Zwróć uwagę, czy serwis wydaje się spokojniejszy, gdy sekwencja siedzi. Rutyna należy do ciebie; jeśli jakiś krok wydaje się nie na miejscu, wymień go.',
  'Zachować spokój, gdy robi się ciasno',
  'Są momenty, w których presja odczuwalnie rośnie. W crossmintonie jeden z nich ma nawet stały adres: stan 15:15. Od tego miejsca musisz zdobyć dwa punkty przewagi, każda wymiana może rozstrzygnąć. Właśnie w takich chwilach dzieje się to, co znasz z pierwszego modułu — napięcie sięga po twój ruch.\n\nPowód jest zawsze ten sam: twoja uwaga zsuwa się z gry na wynik. Zamiast „gdzie zagram następną piłkę" myślisz „byle teraz nie błąd". A ta myśl sama jest błędem, bo cię spina.\n\nPomagają trzy narzędzia. Po pierwsze oddech: świadomy, powolny wdech przed następną wymianą wymiernie obniża napięcie. Po drugie tempo: weź te kilka dozwolonych sekund, nie spiesz się. Kto się spieszy, przyznaje rację zdenerwowaniu. Po trzecie skupienie: myśl o zadaniu, nie o wyniku. „Płasko i na bekhend" to myśl, która pozwala ci działać. „Byle nie przegrać" to myśl, która cię paraliżuje.\n\nWyobraź sobie, że niesiesz pełną szklankę przez pokój pełen ludzi. Jeśli wpatrujesz się w szklankę i myślisz „byle nie rozlać", ręka drży. Jeśli patrzysz spokojnie przed siebie, dokąd idziesz, docierasz bezpiecznie.\n\nDlatego kluczowe zdanie na ciasny moment jest krótkie: następna piłka, nie wynik końcowy.',
  'Obmyśl przed następnym meczem jedno jedyne zdanie związane z zadaniem, które powiesz sobie w ciasnym momencie — coś konkretnego jak „płasko i długo" albo „spokojnie na bekhend". Gdy następnym razem zrobi się ciasno, wypróbuj mały program: głęboki wdech, zdjęcie tempa, twoja myśl. Zwróć potem uwagę, czy w ciasnym momencie zachowałeś więcej spokoju niż zwykle. Nie musi udać się od razu — już samo zauważenie, dokąd zsuwają się twoje myśli, to pierwszy krok.',
  'Zostawić błąd za sobą',
  'Każdy popełnia błędy — także najlepszy gracz. Różnica nie polega na tym, czy błędy popełniasz. Polega na tym, co dzieje się potem. I tu czai się pułapka: błąd często pociąga za sobą następny. Złościsz się, złość siedzi ci na karku w następnej wymianie i już ją także posyłasz na aut.\n\nTo nie przypadek ani wyobraźnia. W dużych analizach widać: błąd wymiernie zwiększa prawdopodobieństwo następnego. Nie dlatego, że nagle grasz gorzej, lecz dlatego, że twoja głowa jest jeszcze przy ostatniej piłce, gdy nowa już nadchodzi.\n\nPomaga na to krótkie, świadome cięcie — mały gest odhaczenia, który zamyka błąd. Jedni przecierają krótko dłonią po naciągu, inni raz wydychają i odwracają wzrok, jeszcze inni mówią sobie w duchu jedno słowo: „dalej". To, co wybierzesz, jest bez znaczenia. Ważne, by gest był zawsze ten sam i niósł jasny komunikat: ta piłka minęła, liczy się następna.\n\nBramkarz, który traci bramkę, nie ma czasu rozpaczać — następny atak już trwa. Najlepsi mają sekundową rutynę, którą odhaczają bramkę i znów są obecni. Dokładnie taką buduje i ty.\n\nZdanie do tego jest najkrótsze w całej skrzynce narzędzi mentalnych: co minęło, minęło.',
  'Przygotuj sobie mały gest odhaczenia — czynność fizyczną plus słowo, które zamyka błąd. W następnym meczu po każdym własnym błędzie wykonujesz świadomie ten gest, zanim zacznie się kolejna wymiana. Zwróć uwagę, czy szybciej wracasz potem do gry. Obserwuj też odwrotność: gdy zawiśniesz przy błędzie, czy częściej przychodzi zaraz następny? Dostrzec własny wzorzec to połowa drogi.',
  'Utrzymać koncentrację',
  'Koncentracja to nie ściana, która albo stoi, albo pada. Waha się na przestrzeni meczu — i szczególnie chętnie załamuje w dwóch miejscach: krótko po tym, jak wyszedłeś na prowadzenie, i w spokojnych fazach, w których akurat nic nie wydaje się być w grze. Właśnie wtedy głowa wymyka się gdzie indziej — do telefonu przy krawędzi pola, do ostatniego punktu, do wyniku końcowego.\n\nRzecz podstępna: te załamania wydają się niegroźne. Zauważasz je często dopiero, gdy oddałeś już dwa punkty i twoja przewaga przepadła. Niewielka przewaga, trzymana beztrosko, znika szybciej, niż przyszła.\n\nNarzędzie na to jest prostsze, niż myślisz: ściągaj uwagę wciąż na tę jedną następną wymianę. Nie na seta, nie na zwycięstwo — tylko na następną piłkę. Koncentracja nie znaczy spinać się godzinami. Znaczy ściągać się wciąż na nowo do teraz, gdy tylko zauważysz, że myślami odpłynąłeś.\n\nKoncentracja jest jak balansowanie na wąskiej ścieżce. Wciąż będziesz z niej lekko schodzić — to normalne. Sztuką nie jest nigdy się nie zachwiać. Sztuka to za każdym razem spokojnie wrócić na ścieżkę.\n\nDlatego narzędzie jest tu nawykiem, nie wysiłkiem: zauważyć, że cię nie ma — i wrócić. Wciąż od nowa.',
  'Zwróć w następnym meczu celowo uwagę na dwa krytyczne miejsca: moment tuż po objęciu prowadzenia i spokojne fazy. Czy tracisz tam więcej punktów niż zwykle? Gdy zauważysz, że myśli odpływają, ściągnij je jednym słowem — „tu" albo „następna piłka". Nie chodzi o to, by nigdy nie odpływać. Ważne, by zauważać odpływanie wcześniej i szybciej wracać.',
];

const ATHLETIK = [
  'Dlaczego przygotowanie fizyczne niesie twoją grę',
  'Crossminton jest szybki. Krótkie zrywy, wiele zmian kierunku, długie wymiany — i to przez całego seta. Twoja technika może na treningu siedzieć czysto. Ale gdy pod koniec seta braknie ci tchu albo nogi zrobią się ciężkie, nie przełożysz jej już na pole.\n\nWłaśnie po to jest przygotowanie fizyczne. Nie jest celem samym w sobie ani programem fitness obok gry — jest tym, co utrzymuje twoje umiejętności dostępnymi do ostatniej piłki. Dobre uderzenie w pierwszym secie jest miłe. To samo uderzenie w decydującym momencie trzeciego seta wygrywa mecze.\n\nNie chodzi przy tym o wyczyn. Chodzi o solidną podstawę: dobrze się przygotować, pozostać ruchomym, być szybkim na nogach, wytrwać i znów się zregenerować. Tę podstawę może zbudować każdy, niezależnie od wieku czy poziomu wyjściowego.\n\nTwoja technika to narzędzie, twoje przygotowanie fizyczne to ręka, która nim kieruje. Zmęczona ręka upuszcza nawet najlepsze narzędzie.\n\nW kolejnych modułach po kolei chodzi o przygotowanie, ruchomość, szybkie stopy, wytrzymałość i regenerację — pięć modułów nośnej podstawy.',
  'Pomyśl o swoim ostatnim dłuższym meczu: od kiedy twoja forma zaczęła spadać — i czy była to raczej technika, koncentracja, czy po prostu kondycja? Zwróć w następnym meczu świadomie uwagę, kiedy najpierw braknie ci tchu, nóg albo skupienia. To miejsce pokazuje, gdzie twoja podstawa ustępuje najpierw.',
  'Prawidłowa rozgrzewka',
  'Pierwszy ostry zryw z miejsca, pierwszy szeroko wyciągnięty bekhend — jeśli twoje ciało nie jest na to przygotowane, to właśnie te momenty, w których coś strzyknie. Rozgrzewka sprawia, że twoje ciało jest gotowe, zanim gra zrobi się poważna.\n\nDobra rozgrzewka robi dwie rzeczy. Rozrusza krążenie i doprowadza mięśnie do temperatury — ciepłe mięśnie pracują bardziej gładko i rzadziej się rwą. I przygotowuje właśnie te ruchy, których zaraz potrzebujesz: wykroki, obroty, wymachy ramion.\n\nDlatego kilka minut biegu samo w sobie nie wystarczy. Po rozgrzaniu należą się ruchy podobne do gry — luźne wykroki, obroty tułowia, krążenia ramion, kilka uderzeń cienia bez speedera. Tak budzisz mięśnie, które zaraz obciążysz.\n\nNie wrzuciłbyś zimnego samochodu od razu na autostradę. Silnik potrzebuje chwili, by dojść do temperatury pracy. Twoje ciało tak samo.\n\nReguła na koniec: rozgrzewka znaczy rozgrzać się, nie zmęczyć. Ma cię przygotować, nie wyczerpać.',
  {
    titel: 'Krótka sekwencja rozgrzewki',
    ziel: 'Przygotować ciało do gry — krążenie, ciepło, przygotowanie ruchowe.',
    schritte: [
      'Najpierw rozrusz krążenie: kilka minut luźnego biegu, truchtu lub skakanki, aż lekko się rozgrzejesz.',
      'Potem przygotowanie w ruchu: luźne wykroki w przód i w bok, obroty tułowia, krążenia ramion i barków.',
      'Na koniec blisko gry: kilka uderzeń cienia bez speedera — forhend, bekhend, ruch serwisu — i kilka małych zrywów.',
    ],
    selbstkontrolle: 'Jesteś dobrze rozgrzany, gdy czujesz się lekko rozgrzany i ruchomy, ale wciąż świeży. Jeśli tracisz oddech lub się męczysz, było tego za wiele. Zadbaj o to, by objąć zwłaszcza bark ramienia uderzającego i nogi.',
    abschluss: 'Ta sekwencja trwa tylko kilka minut i należy się przed każdym meczem i każdym treningiem. To najtańsza polisa na wypadek kontuzji, jaką masz.',
  },
  'Mobilność i bark',
  'Ruchomość decyduje o tym, jak daleko sięgasz, nie robiąc sobie krzywdy — głęboki bekhend, wyciągnięta piłka w narożniku. Ruchome ciało dosięga więcej piłek i lepiej znosi obciążenie. Dla crossmintona dotyczy to szczególnie jednego miejsca: barku ramienia uderzającego.\n\nPowodem jest jednostronne obciążenie. Niemal wszystko uderzasz jedną ręką, a speeder jest ciężki. Badania graczy crossmintona pokazują, że bark ramienia uderzającego zmienia się z czasem — staje się bardziej ruchomy w jednym kierunku i mniej ruchomy w drugim niż drugi bark. Ta jednostronna adaptacja jest normalna, ale na dłuższą metę może sprzyjać dolegliwościom, jeśli się jej nie wyrównuje.\n\nDlatego opłacają się dwie rzeczy. Po pierwsze: regularnie i łagodnie utrzymywać bark ramienia uderzającego ruchomym, zwłaszcza w kierunku, który przez grę robi się sztywniejszy. Po drugie: obciążać ciało całościowo obustronnie, zamiast wciąż tylko jednej strony. Kilka ruchów dla słabszej strony wyrównuje jednostronne obciążenie.\n\nDrzewo, które wiatr wygina wciąż tylko w tę samą stronę, rośnie krzywo. Regularne przeciwdziałanie trzyma je prosto.\n\nWażna uwaga: łagodna pielęgnacja ruchomości to profilaktyka, nie leczenie. Jeśli bark cię boli, ogranicza cię w grze albo dolegliwości się utrzymują, to przypadek dla lekarza lub fizjoterapeuty — nie dla samoleczenia.',
  {
    titel: 'Zadbać o bark',
    ziel: 'Utrzymać jednostronnie obciążony bark uderzający ruchomym i wyrównać obciążenie.',
    schritte: [
      'Po grze, gdy bark jest ciepły: łagodne, powolne rozciąganie tylnej części barku ramienia uderzającego — poprowadź ramię luźno przed ciałem na przeciwną stronę i przytrzymaj tam spokojnie.',
      'Zakręć barkiem uderzającym kilka razy powoli w obie strony.',
      'Obciąż świadomie także drugą stronę: kilka ruchów i luźnych uderzeń ramieniem niedominującym, by wyrównać jednostronność.',
    ],
    selbstkontrolle: 'Rozciąganie ma być lekkim ciągnięciem z tyłu w barku, nigdy bólem z przodu ani w stawie. Jeśli poczujesz ból, odpuść. Zostań zawsze w łagodnym zakresie — ruchomość zyskuje się cierpliwością, nie siłą.',
    abschluss: 'Kilka minut po każdym meczu wystarczy. Regularność liczy się tu bardziej niż intensywność — bark odwdzięczy ci się przez lata.',
  },
  'Szybkie stopy',
  'Crossminton rozstrzyga się na pierwszych dwóch metrach. Nie liczy się długi sprint, lecz krótki, eksplozywny zryw z miejsca — i zdolność, by przywoływać go raz za razem, przez całego seta. Kto jest przy speederze o dziesiątą część sekundy wcześniej, gra go kontrolowanie zamiast w pośpiechu.\n\nTa szybkość jest w dużej części do wytrenowania. Chodzi przy tym mniej o siłę, a bardziej o zwinne, uporządkowane stopy: krótkie kroki, dobre pierwsze odbicie, natychmiastowe przełączenie w nowy kierunek. Dokładnie to, co poznałeś w module technicznym o pracy nóg jako split-step i powrót, dostaje tu swoją podstawę atletyczną.\n\nKluczem są małe, szybkie kontakty zamiast dużych, ociężałych kroków. Zwinne stopy szybciej wprawiają cię w ruch i szybciej zatrzymują — a obu potrzebujesz w każdej wymianie.\n\nPomyśl o bokserze, który tańczy na przedniej części stóp. Nigdy nie stoi ciężko i płasko, lecz zawsze lekko i gotowo. Właśnie tej lekkości szukasz dla swojego pola.\n\nSzybkie stopy budujesz krótkimi, zabawowymi ćwiczeniami — nie długim, mozolnym treningiem biegowym.',
  {
    titel: 'Zryw i zmiana kierunku',
    ziel: 'Ćwiczyć krótki, eksplozywny zryw i szybkie przełączanie.',
    schritte: [
      'Zaznacz sobie kilka punktów na podłożu — narożniki i środek twojego pola wystarczą.',
      'Wystartuj z pozycji podstawowej split-stepem, sprintuj do jednego punktu, dotknij go i wróć do środka.',
      'Zmieniaj kolejność punktów, byś musiał zrywać we wszystkich kierunkach.',
      'Wpleć krótkie przerwy — chodzi o eksplozywne, czyste zrywy, nie o obciążenie ciągłe.',
    ],
    selbstkontrolle: 'Zwróć uwagę na lekkie, szybkie stopy i wyraźne pierwsze odbicie. Jeśli kroki robią się ciężkie i szurające, zrób krótką przerwę — zmęczone stopy ćwiczą zły ruch. Jakość ponad ilość.',
    abschluss: 'Takie krótkie ćwiczenia zrywu dobrze pasują na koniec rozgrzewki albo jako osobny mały blok. Kilka czystych powtórzeń daje więcej niż długie, zmęczone serie.',
  },
  'Wytrwać',
  'Set crossmintona to przeplatanie krótkich, intensywnych wymian i małych przerw między nimi — i to wiele razy z rzędu. Kto załamuje się po pierwszych intensywnych wymianach, przegrywa nie dlatego, że gra gorzej — kończą mu się siły. Wytrzymałość znaczy tu: do ostatniej piłki utrzymać ten sam poziom.\n\nTa wytrzymałość ma dwie strony. Jedna to ogólna podstawa — układ krążenia, który udźwignie obciążenie całego meczu. Budujesz ją regularnym, umiarkowanym ruchem, wszystko jedno czy bieganiem, jazdą na rowerze, czy pływaniem. Druga strona to wytrzymałość bliska grze — zdolność przywoływania krótkich intensywnych obciążeń raz za razem. Trenujesz ją najlepiej, grając i świadomie wytrzymując przy tym fazy intensywne.\n\nNa początek obowiązuje prosta prawda: kto regularnie gra i przy tym się wymaga od siebie, buduje już sporo wytrzymałości. Uzupełniający luźny trening wytrzymałościowy pomaga dodatkowo, zwłaszcza gdy tchu brakuje ci wcześnie.\n\nWytrzymałość to zbiornik, z którego czerpie wszystko inne. Gdy jest pusty, na nic ci najlepszy silnik.\n\nWażna jest budowa z cierpliwością. Wytrzymałość rośnie powoli i stale. Kto zbyt szybko chce zbyt wiele, ryzykuje przeciążenie zamiast postępu.',
  {
    titel: 'Zbudować podstawę',
    ziel: 'Stworzyć bazę wytrzymałości, która udźwignie całego seta.',
    schritte: [
      'Zbuduj regularną, luźną bazę wytrzymałości — formę ruchu, która sprawia ci radość i którą wytrwasz: bieganie, jazda na rowerze, pływanie.',
      'W grze świadomie wytrzymuj intensywne wymiany, zamiast je skracać — wytrzymałość bliska grze powstaje w samej grze.',
      'Wykorzystuj krótkie przerwy między wymianami świadomie na krótkie złapanie oddechu i zebranie się.',
    ],
    selbstkontrolle: 'Zwróć uwagę, czy pod koniec meczu masz jeszcze tę samą jakość ruchu co na początku. Jeśli się załamuje, punktem zaczepienia jest baza wytrzymałości. Zwiększaj objętość powoli — umiarkowana regularność bije rzadkie przeciążenie.',
    abschluss: 'Wytrzymałość to najcierpliwszy plac budowy: nie pokazuje się po tygodniu, ale po kilku tygodniach niesie każdy twój mecz.',
  },
  'Regeneracja',
  'Regeneracja brzmi jak to, co dzieje się, gdy nic się nie robi. W rzeczywistości jest aktywną częścią twojej kondycji — i najbardziej niedocenianą. Twoje ciało staje się silniejsze w regeneracji po treningu, nie w treningu. A wewnątrz meczu regeneracja między setami często decyduje o tym, czy w trzecim secie wciąż jesteś obecny.\n\nWażne są dwie skale czasu. Krótka: przerwy w samej grze, między wymianami i między setami. Wykorzystuj je świadomie — spokojnie oddychać, rozluźnić ciało, zebrać głowę. Kto w przerwach pozostaje nakręcony, oddaje regenerację, której zaraz potrzebuje. Długa: czas między jednostkami treningowymi. Twoje ciało potrzebuje przerw, by się adaptować i stawać silniejszym. Sen jest przy tym najważniejszym czynnikiem regeneracji w ogóle.\n\nWynika z tego coś, co wielu przychodzi z trudem: przerwy są częścią treningu, nie oznaką lenistwa. Kto codziennie gra ciężko i nigdy nie odpoczywa, nie staje się silniejszy, tylko bardziej zmęczony — i z czasem bardziej podatny na kontuzje.\n\nRegeneracja jest jak ładowanie na nowo. Pole, które bez przerwy wciąż się obsiewa, jałowieje. Faza spoczynku sprawia, że znów rodzi.\n\nSztuką jest równowaga: dość obciążenia, by stawać się lepszym, i dość regeneracji, by obciążenie zadziałało.',
  'Zwróć raz świadomie uwagę na swoje przerwy — w grze i między dniami treningowymi. Czy wykorzystujesz krótkie przerwy między setami na regenerację, czy pozostajesz nakręcony? I czy między intensywnymi dniami dajesz sobie dość odpoczynku i snu? Obserwuj, czy w dni po dobrej regeneracji czujesz się świeższy i mocniejszy w grze. Często więcej odpoczynku to postęp, którego najmniej się oczekuje.',
];

const r1 = insertPl('data/bausteine.beginner-taktik.json', TAKTIK);
const r2 = insertPl('data/bausteine.beginner-mentales.json', MENTALES);
const r3 = insertPl('data/bausteine.beginner-athletik_kondition.json', ATHLETIK);
console.log(`Ring 3 pl: taktik ${r1.knoten} + mentales ${r2.knoten} + athletik ${r3.knoten} = ${r1.knoten + r2.knoten + r3.knoten} Knoten.`);
