// Ring 12 (pl): Trainer-Trainingsgestaltung (15) + Fehlerbilder (1, erklaerteil-Objekt) = 16 Knoten.
import { insertPl } from './pl-core.mjs';

const TRAINER = [
  'Na czym polega dobre nauczanie',
  'Kto naucza crossmintona, staje przed innym zadaniem niż ten, kto w niego gra. Nie musisz sam umieć perfekcyjnego uderzenia — musisz sprawić, by inni je znaleźli. To osobne rzemiosło, i można się go nauczyć.\n\nNajważniejsza postawa podstawowa jest prosta: myśl od strony grania. Ludzie przychodzą do crossmintona, bo chcą grać, nie dlatego, że chcą rozkładać na czynniki przebiegi ruchowe. Kto każe grupie przez pół godziny w izolacji ćwiczyć uderzenia, zanim dojdzie do pierwszej wymiany, traci właśnie to, co tych ludzi przyprowadziło. Dobre nauczanie wprowadza ludzi wcześnie do gry i szlifuje technikę stamtąd.\n\nWynika z tego myśl przewodnia, która przewija się przez wszystkie kolejne moduły: najpierw doświadczenie, potem wyjaśnienie. Pozwól uczącym się przeżyć sytuację, zanim ją wyjaśnisz. Początkujący, który zauważył, że nie dosięga speedera, rozumie pracę nóg inaczej niż ten, któremu wyjaśnisz ją z góry.\n\nWidź siebie jako ogrodnika, nie jako wykładowcę przy tablicy. Tworzysz warunki, w których coś rośnie — właściwe formy gry, odpowiednie zadania —, i wkraczasz celowo tam, gdzie to konieczne. Rosnąć musi sama umiejętność.\n\nCztery kolejne moduły pokazują cztery rzemiosła nauczania: uczynić treść przystępną, rozpoznawać i korygować błędy, budować ćwiczenia, prowadzić grupę.',
  'Pomyśl o trenerze lub nauczycielu, u którego sam czegoś dobrze się nauczyłeś — w jakimkolwiek sporcie czy przedmiocie. Co ta osoba konkretnie robiła? Dużo wyjaśniała, czy pozwalała ci wcześnie samemu próbować? Jak obchodziła się z błędami? Zanotuj sobie dwie, trzy rzeczy, które chciałbyś przejąć. Twoja własna historia uczenia się to najlepsze pierwsze źródło twojego stylu nauczania.',
  'Uczynić treść przystępną',
  'Początkujący nie może zwracać uwagi na dziesięć rzeczy naraz. Twoim pierwszym zadaniem w nauczaniu jest więc uczynić treść mniejszą, niż jest — sprowadzić ją do jej rdzenia.\n\nKażda technika ma węzeł, na którym stoi lub upada. Przy chwycie to luźna ręka, przy serwisie punkt kontaktu poniżej dłoni uderzającej, przy drivie punkt kontaktu przed ciałem. Gdy znajdziesz ten jeden rdzeń i wszystko inne najpierw pominiesz, dajesz uczącemu się coś, co faktycznie może wcielić w życie. Dziesięć poprawnych wskazówek naraz jest gorsze niż ta jedna, która się liczy.\n\nTrzy drogi prowadzą do zrozumienia i najlepiej działają razem. Pokazać: zrób ruch przed nimi, powoli i z takiego kąta, z którego widać rdzeń. Powiedzieć: daj zwięzłe, jasne polecenie — co robić, nie czego unikać. I dać obraz: dobra analogia sięga dalej niż dziesięć pojęć technicznych. „Podaj rączce rękę" siedzi natychmiast; „obróć dłoń w lekko pronowane położenie neutralne" dezorientuje.\n\nObraz do tego, którego sam możesz użyć: jeden obraz na jedną rzecz. Gdy zauważysz, że potrzebujesz trzech porównań, by wyjaśnić jeden ruch, to znaczy, że nie sprowadziłeś go jeszcze do rdzenia.\n\nWłaśnie przy osobach przechodzących z innych sportów rakietowych obowiązuje: nawiąż do tego, co już umieją, i nazwij tylko tę jedną rzecz, która jest inna. To oszczędza obu stronom wiele trudu.',
  'Wybierz technikę z części dla początkujących — chwyt, serwis lub forhend. Sformułuj dla niej trzy rzeczy: ten jeden rdzeń ruchu w jednym zdaniu, zwięzłe polecenie działania, i obraz lub analogię. Sprawdź potem samokrytycznie: czy rdzeń dałoby się zredukować jeszcze bardziej? To ćwiczenie — redukcja do istoty — to podstawowa umiejętność każdego nauczania.',
  'Rozpoznawanie i korygowanie błędów',
  'Korygowanie to więcej niż nazwanie błędu. Właściwa sztuka polega na znalezieniu za widocznym błędem przyczyny — bo oba rzadko są tym samym.\n\nPrzykład: speeder uczącego się ląduje zawsze za krótko. To objaw. Przyczyna może leżeć całkiem gdzie indziej — w spiętym chwycie, w zbyt późnym punkcie kontaktu, w braku przeniesienia ciężaru, w złej pozycji wyjściowej. Kto tylko leczy objaw („graj dalej"), niczego nie zmienia. Kto trafi w przyczynę, rozwiązuje problem jedną wskazówką.\n\nDlatego dobre korygowanie rozpada się na trzy kroki. Po pierwsze zobaczyć: patrz celowo na miejsce, w którym powstaje ruch, nie tylko na jego rezultat. Po drugie wywnioskować: zapytaj siebie, która przyczyna najprawdopodobniej wyjaśnia zobaczony obraz błędu. Po trzecie zakomunikować: daj dokładnie jedną wskazówkę, która adresuje przyczynę — sformułowaną pozytywnie, jako działanie, które uczący się może wykonać. „Trafiaj speedera bardziej z przodu" prowadzi dalej niż „trafiasz za późno".\n\nBądź diagnostą, nie komentatorem. Komentator opisuje, co poszło źle. Diagnosta znajduje, dlaczego — i tylko to da się leczyć.\n\nWażna zasada na koniec: koryguj oszczędnie. Jedna korekta, która siedzi, jest warta więcej niż pięć, które przytłaczają uczącego się. I daj ruchowi czas — nie każda zmiana chwyta za pierwszym razem.',
  'Weź częsty obraz błędu — na przykład „serwis idzie zawsze na aut" albo „bekhend przychodzi za krótko". Zbierz dla tego jednego objawu co najmniej trzy możliwe przyczyny w różnych miejscach ruchu. Obmyśl potem dla każdej przyczyny pozytywną, zorientowaną na działanie wskazówkę korygującą. To ćwiczenie — wnioskować z jednego objawu o kilku możliwych przyczynach — to istota korygowania.',
  'Sensowne budowanie ćwiczeń',
  'Dobre ćwiczenie nie powstaje przypadkiem. Ma jasny cel, odpowiednią trudność i miejsce w sensownej kolejności. Ten moduł pokazuje, jak budować ćwiczenia tak, by były rzeczywiście skuteczne w nauce.\n\nNajpierw zasadnicze rozgałęzienie. Są dwie drogi budowania umiejętności. Jedna to seria ćwiczeń: rozkładasz technikę i każesz ćwiczyć ją w izolacji, od prostego do złożonego, aż na końcu stoi gra. To daje pewność, obejmuje też słabszych uczących się — ale kosztuje urok gry, bo długo się nie gra. Druga to seria gier: zaczynasz od uproszczonej formy gry i rozwijasz technikę z samej gry. To utrzymuje motywację, ale niektórych początkujących przytłacza. W praktyce mieszasz oboje — graj wcześnie, i ćwicz celowo to, co w grze się zacina.\n\nSkutecznym narzędziem są przy tym zmienione reguły. Regułą prowokacji wymuszasz określone działanie: „punkt liczy się tylko, gdy speeder został zagrany w tylną strefę" — i już wszyscy ćwiczą długość, bez tego, byś musiał wyjaśniać to pojedynczo. Regułą kontynuacji utrzymujesz grę w ruchu, a tym samym wysoką koncentrację, zamiast przerywać po każdym błędzie.\n\nTrudnością sterujesz kilkoma pokrętłami: tempo, wymóg dokładności, presja czasu, wielkość pola. Ćwiczenie, które jest zbyt łatwe, nudzi; zbyt trudne frustruje. Dobrze dozowane jest wtedy, gdy się udaje, ale nie bez wysiłku.\n\nBuduj schody, nie ścianę. Każdy stopień jest ledwie osiągalny z poprzedniego. Kto stoi przed ścianą, nie wspina się — poddaje się.',
  'Zaprojektuj małą serię ćwiczeń z trzech kroków do wybranego tematu dla początkujących — na przykład serwisu lub długości. Zacznij prosto, zwiększaj w każdym kroku dokładnie jeden wymóg, i zakończ formą gry, w której ćwiczone się pojawia. Wbuduj przynajmniej raz regułę prowokacji. Sprawdź potem: czy każdy stopień jest z poprzedniego ledwie osiągalny? Ta umiejętność — zbudować nośną progresję — to serce prowadzenia treningu.',
  'Prowadzenie grupy',
  'Gdy tylko pracujesz z więcej niż jedną osobą, do nauczania dochodzi organizacja. Prowadzić grupę znaczy uformować z różnych ludzi, ograniczonej przestrzeni i ograniczonego czasu sensowną całość.\n\nCztery rzeczy przy tym zbierasz. Po pierwsze różne poziomy. W niemal każdej grupie stoją początkujący obok bardziej zaawansowanych. Zamiast kazać wszystkim robić to samo, dajesz to samo ćwiczenie z różnymi wymogami — jeden gra na duży cel, drugi na mały. Tak nikt nie jest niedociążony i nikt nie zostaje w tyle.\n\nPo drugie dramaturgia jednostki. Dobra jednostka treningowa ma łuk: rozgrzewkę, która przygotowuje i budzi ochotę; część główną z jasnym punktem ciężkości; wyciszenie, często swobodną grę, która stosuje ten punkt ciężkości. Kto planuje bez tego łuku, tylko zestawia ćwiczenia jedno za drugim.\n\nPo trzecie przestrzeń i sprzęt. W crossmintonie jest to wdzięczne — bez siatki i z kilkoma oznaczeniami szybko rozstawisz kilka pól. Zadbaj o to, by wszyscy byli w ruchu i nikt długo nie czekał. Długie kolejki oczekujących to najczęstszy błąd i najpewniejsza droga do utraty motywacji.\n\nPo czwarte motywacja i bezpieczeństwo. Trzymaj pozytywny nastrój i osiągalne wymogi, uważaj na dość duży odstęp między polami i na bezpieczne obchodzenie się ze sprzętem. Ludzie uczą się lepiej, gdy czują się bezpiecznie i mają radość.\n\nJesteś gospodarzem, nie nadzorcą. Dobry gospodarz dba o to, by wszyscy byli zajęci, dobrze się czuli i na końcu chętnie wracali.',
  'Zaplanuj krótką jednostkę treningową dla mieszanej grupy: naszkicuj rozgrzewkę, część główną z jednym jedynym punktem ciężkości i wyciszenie. Zastanów się przy części głównej, jak to samo ćwiczenie uczynić różnie wymagającym dla mocniejszych i słabszych, i jak podzielić przestrzeń tak, by nikt długo nie czekał. To planowanie z góry to różnica między prowadzoną jednostką a zwykłym zestawieniem jednego ćwiczenia za drugim.',
];

const FEHLERBILDER = [
  {
    symptom: 'Przedramię męczy się wcześnie, uderzenia robią się twarde i niedokładne, nadgarstek pozostaje sztywny. Często widoczne po zbielałych kłykciach i chwycie, który przez całą wymianę się nie rozluźnia.',
    ursache: 'Ręka spina się trwale, zamiast zacisnąć tylko w chwili trafienia. Przeważnie z napięcia albo z pragnienia większej kontroli — ale mocny chwyt odbiera dokładnie to czucie, którego szuka.',
    korrektur: 'Chwytaj luźno jak przy uścisku dłoni; mocno robi się tylko w chwili trafienia, potem znów rozluźnij. Wskazówka: „Trzymaj chwyt tak, żebym mógł ci jeszcze lekko wykręcić rakietę z ręki — zaciśnij dopiero w trafieniu, potem natychmiast rozluźnij."',
  },
];

const r1 = insertPl('data/bausteine.trainer-trainingsgestaltung.json', TRAINER);
const r2 = insertPl('data/fehlerbilder.json', FEHLERBILDER);
console.log(`Ring 12 pl: trainer ${r1.knoten} + fehlerbilder ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
