// Ring 6 (pl): Fortgeschritten-Mentales (15) + Fortgeschritten-Athletik (15) = 30 Knoten, delta-frei.
import { insertPl } from './pl-core.mjs';

const MENTALES = [
  'Od narzędzia do systemu',
  'W części dla początkujących poznałeś pojedyncze narzędzia mentalne: rutynę serwisu, zachowanie spokoju w ciasnym momencie, odhaczanie błędu, ściąganie z powrotem koncentracji. Teraz składasz te narzędzia w system — mentalną grę, którą trenujesz tak samo jak swoje uderzenia.\n\nPierwszym krokiem jest zmiana perspektywy. Siła mentalna to zdolność, która rośnie, gdy ją ćwiczysz — nie cecha, którą się ma albo nie. Tak jak uderzenie przechodzi ona przez stopnie: najpierw rozumiesz narzędzie, potem ćwiczysz je świadomie, kiedyś działa samo. Narzędzia dla początkujących były pierwszym stopniem. Teraz ćwiczysz je świadomie tak długo, aż staną się nawykami.\n\nNależy do tego jasne spojrzenie na twoje cele. Są dwa rodzaje. Cele rezultatu kierują się na wynik: wygrać, wziąć seta. Cele procesu kierują się na to, co robisz: czysto serwować, wcześnie wracać do środka, grać następną piłkę. W grze pomagają ci cele procesu, bo leżą w twojej ręce. Wynik z nich wynika, ale nie sterujesz nim bezpośrednio.\n\nTwoja gra mentalna to skrzynka narzędzi. Do tej pory nauczyłeś się używać każdego narzędzia osobno. Teraz uczysz się we właściwym momencie sięgnąć po odpowiednie — i w ogóle mieć skrzynkę przy sobie.\n\nKolejne moduły dają ci zaawansowane narzędzia: celowany dialog wewnętrzny, wyobrażenie, radzenie sobie z momentum i stabilność przez cały mecz.',
  'Sformułuj na następny mecz dwa, trzy cele procesu — konkretne rzeczy, które chcesz robić, niezależnie od wyniku. Na przykład: po każdym uderzeniu powrót do środka, każdy serwis z zamiarem, po każdym błędzie gest odhaczenia. Obserwuj po meczu najpierw, czy osiągnąłeś swoje cele procesu — nie, czy wygrałeś. To przesunięcie spojrzenia jest istotą zaawansowanego treningu mentalnego.',
  'Kierowanie dialogiem wewnętrznym',
  'W twojej głowie nieustannie toczy się rozmowa — z samym sobą. Po błędzie mówi może „nie znowu", przed ważnym punktem „byle teraz nie". Ta wewnętrzna rozmowa wpływa na twoją grę mocniej, niż jesteś tego świadomy. Dobra wiadomość: możesz nią kierować.\n\nSą dwa użyteczne rodzaje dialogu wewnętrznego. Instruujący kieruje twoją uwagę na zadanie: „płasko i długo", „trafiać wcześnie", „oczy na speedera". Działa jak krótka autoinstrukcja i dowodnie poprawia dokładność i koordynację. Dodający otuchy daje ci energię i pewność: „dawaj, dalej", „dasz radę". Pomaga w momentach, w których głowa chce się poddać.\n\nNajważniejszym krokiem jest przeformułowanie negatywnego dialogu wewnętrznego. Zdanie „nie mogę stracić tego punktu" paraliżuje, bo wskazuje na zagrożenie. Przeformułuj je na „gram teraz pewnie na bekhend" — zdanie, które pozwala ci działać. Wymieniasz myśl, która cię blokuje, na taką, która cię prowadzi.\n\nTwój dialog wewnętrzny jest jak trener, który podszeptuje ci w trakcie gry. Ty decydujesz, czy ten trener w ciebie wątpi, czy jasno i spokojnie cię instruuje. To twój głos — więc daj mu właściwe słowa.\n\nNajskuteczniejsze są krótkie, stałe formuły. Jedno, dwa słowa, które powtarzasz sobie raz za razem, stają się niezawodnymi kotwicami w grze.',
  'Zwróć w następnym meczu raz świadomie uwagę na swoją wewnętrzną rozmowę — zwłaszcza po błędach i przed ważnymi punktami. Co sobie mówisz? Wybierz potem dwie stałe formuły: jedną instruującą do zadania (na przykład „płasko i długo") i jedną dodającą otuchy na trudne momenty (na przykład „dawaj, dalej"). Weź typowe negatywne zdanie, które sobie mówisz, i przeformułuj je na zorientowane na działanie. Ćwicz, by w grze świadomie sięgać po te słowa.',
  'Wyobrażanie sobie gry',
  'Twój mózg rozróżnia między żywo wyobrażonym a faktycznie wykonanym ruchem słabiej, niż myślisz. Jeśli dokładnie wyobrazisz sobie uderzenie, aktywujesz w mózgu podobne wzorce co przy prawdziwym uderzeniu. Tę zdolność możesz wykorzystać — na treningu i wprost w grze.\n\nTrening wyobrażeniowy znaczy przećwiczyć ruch lub sytuację w głowie, zanim ją wykonasz. Przed meczem możesz wyobrazić sobie, jak pewnie serwujesz, jak spokojnie przetrzymujesz długą wymianę, jak zachowujesz się w wyrównanym secie. Im żywiej, tym lepiej: zobacz przed sobą pole, poczuj rakietę, usłysz chwilę trafienia.\n\nTakże w środku gry pomaga wyobrażenie. Zanim zaserwujesz, widzisz na chwilę przed sobą tor lotu, który chcesz trafić — płaski, długi, w narożnik bekhendowy. Ten krótki wewnętrzny podgląd ustawia twój ruch, jeszcze zanim go zaczniesz.\n\nSkoczek narciarski stoi na górze na belce i przejeżdża skok w głowie, zanim ruszy — każdy zakręt, każdy ruch. Ta wewnętrzna próba generalna czyni prawdziwy skok pewniejszym. Tak samo wyobrażasz sobie swoje uderzenie, zanim je zagrasz.\n\nWyobrażenie nie zastępuje ćwiczenia, ale je wzmacnia. Kilka minut świadomego wyobrażenia przed meczem albo krótki podgląd przed serwisem kosztują niewiele, a działają wyczuwalnie.',
  'Weź przed następnym meczem dwie minuty i wyobraź sobie żywo, jak dobrze grasz: pewny serwis, spokojnie przetrzymana wymiana, pewnie poprowadzony wyrównany set. Użyj w miarę możliwości wszystkich zmysłów — wzroku, czucia, słuchu. Ćwicz potem w grze krótki podgląd: zanim zaserwujesz, widzisz na moment przed sobą tor lotu, który chcesz trafić. Obserwuj, czy twój serwis podąża za wyobrażeniem.',
  'Czytanie i odwracanie momentum',
  'Mecze przebiegają falami. Raz wszystko idzie dla ciebie, piłki wpadają, przeciwnik wydaje się bezradny. Potem się przechyla i nagle to on zdobywa punkty. To wznoszenie i opadanie ma swoją nazwę: momentum. Kto potrafi je czytać i na nie wpływać, wygrywa mecze, które inaczej by przegrał.\n\nMomentum powstaje często w małych seriach. Zdobywasz dwa, trzy punkty, czujesz się pewnie, grasz swobodniej — a ta pewność niesie następny punkt. Tak samo u przeciwnika. Rytm trzech serwisów w crossmintonie to wzmacnia: kto serwuje, ma często małą przewagę i może zacząć serię.\n\nNajważniejsze to przerwać negatywną falę wcześnie. Jeśli tracisz kilka punktów z rzędu, przełam rytm świadomie: weź dozwolony krótki czas, odetchnij, sięgnij po swoją rutynę, ściągnij koncentrację na tę jedną następną piłkę. Przerywasz tym bieg przeciwnika i własne zsuwanie w dół.\n\nOdwrotnie — dosiadasz pozytywnej fali, po prostu robiąc dalej to, co działa — bez popadania w brawurę. Jeśli idzie, nie zmieniaj nic i trzymaj się swojego planu.\n\nMomentum jest jak nurt rzeki. Walka z nim, gdy biegnie przeciw tobie, wyczerpuje. Mądrzej jest na chwilę wyjść na brzeg, odetchnąć i potem wejść na nowo. Jeśli nurt biegnie dla ciebie, dajesz się spokojnie nieść.',
  'Obserwuj w następnym meczu fale: kiedy seria biegnie dla ciebie, kiedy dla przeciwnika? Postanów sobie stałą reakcję na negatywne serie — jeśli tracisz dwa, trzy punkty z rzędu, przerywasz świadomie: wziąć krótki czas, oddech, rutyna, następna piłka. Obserwuj, czy potrafisz tym wcześniej zatrzymać bieg przeciwnika. I zwróć uwagę, czy pozytywne serie czasem sam kończysz, popadając w brawurę.',
  'Utrzymać stabilność przez cały mecz',
  'Mecz jest długi. Ma dobre i złe fazy, sety, które należą do ciebie, i takie, w których nic się nie udaje. Zaawansowana zdolność mentalna to pozostać stabilnym ponad wszystkimi tymi falami — nie w każdej chwili idealnym, ale niezawodnie wracać wciąż do swojej gry.\n\nStabilność nie znaczy, że nic tobą nie wstrząsa. Także najlepsi mają złe fazy. Różnica jest w tym, jak szybko wracają. Zła faza może kosztować kilka punktów — nie może określać całego meczu. Tutaj opłacają się wszystkie dotychczasowe narzędzia: odhaczasz błąd, przerywasz negatywną falę, ściągasz z powrotem koncentrację, dodajesz sobie otuchy. Razem tworzą twoją odporność.\n\nSzczególnie ważne są przejścia: moment po przegranym secie, moment po roztrwonionej przewadze. Właśnie tam rozstrzyga się, czy pękasz, czy się utrzymujesz. Przegrany set to nowy początek, nie wyrok o całym meczu. Kto następny set zaczyna świeżo, zostawił poprzedni wynik za sobą.\n\nWyobraź sobie swoją stabilność mentalną jak wstańkę. Popycha się ją, przechyla na bok — ale jej środek ciężkości zawsze przywraca ją do pozycji pionowej. Nie chwianie czyni ją mocną, lecz niezawodność, z jaką wraca.\n\nTa stabilność rośnie z doświadczeniem i ze świadomym ćwiczeniem poszczególnych narzędzi. Im bardziej są ci znajome, tym niezawodniej niosą cię przez długi mecz.',
  'Wróć myślami do meczu, w którym po złej fazie lub przegranym secie się załamałeś. Co pomogłoby ci szybciej wrócić? Postanów sobie na następny mecz jedno jedyne przejście — na przykład początek po przegranym secie — i potraktuj je świadomie jako świeży start: krótko się zebrać, ustawić cel procesu, ruszyć na nowo. Obserwuj, czy potrafisz lepiej ograniczyć złą fazę, zamiast pozwolić jej określać cały mecz.',
];

const ATHLETIK = [
  'Trenować celowo',
  'W części dla początkujących chodziło o solidną podstawę: rozgrzewka, ruchomość, szybkie stopy, wytrzymałość, regeneracja. Teraz trening staje się bardziej celowy. Pracujesz nad zdolnościami, których crossminton konkretnie wymaga — nad eksplozywnością na pierwszy krok, przenoszeniem siły na mocne uderzenia, wytrzymałością na typową przemianę krótkich intensywnych faz i przerw.\n\nJedna zasada stoi ponad wszystkim: baza przed specjalizacją. Celowany, wymagający trening buduje się na solidnej podstawie. Kto pominie podstawę i od razu zaczyna zaawansowanymi metodami, ryzykuje przeciążenie. Zaawansowane moduły zakładają dlatego, że podstawa z części dla początkujących stoi.\n\nCelowo znaczy też: obserwować własny rozwój. Zauważasz, że brakuje ci raczej eksplozywności, siły czy wytrzymałości? To szczere spojrzenie pokazuje ci, nad czym powinieneś pracować. Nie wszystkiego naraz, lecz po kolei tego, co najbardziej hamuje.\n\nWażna uwaga na wstępie, która obowiązuje dla wszystkich kolejnych modułów: ta część wyjaśnia zasady, nie gotowe plany treningowe. Zaawansowany trening fizyczny — zwłaszcza skoczność i sterowanie obciążeniem — chce być właściwie dozowany i budowany. Do konkretnego, skrojonego pod ciebie programu właściwym adresem jest wykwalifikowana trenerka lub trener. A przy bólu lub dolegliwościach diagnoza należy do rąk lekarskich lub fizjoterapeutycznych.\n\nCelowany trening jest jak rozbudowa domu. Najpierw musi stać fundament, potem budujesz celowo pomieszczenia, których potrzebujesz. Kto nadbudowuje na słabym fundamencie, zagraża całej konstrukcji.',
  'Spójrz szczerze na swoją grę: co hamuje cię najbardziej fizycznie — brakuje ci raczej eksplozywności na pierwszy krok, siły na mocne uderzenia, czy wytrzymałości pod koniec seta? Wybierz jeden jedyny punkt ciężkości, nad którym chcesz najpierw popracować. I zastanów się, czy twoja podstawa atletyczna z części dla początkujących (rozgrzewka, ruchomość, wytrzymałość bazowa) faktycznie stoi — jest warunkiem wszystkiego, co bardziej celowe. Do konkretnego programu włącz wykwalifikowane prowadzenie.',
  'Eksplozywność i skoczność',
  'Crossminton rozstrzyga się w ułamkach sekundy: pierwszy krok do speedera, odbicie do uderzenia nad głową, nagłe przełączenie kierunku. Wszystko to wymaga eksplozywności — zdolności przywołania w najkrótszym czasie dużej siły.\n\nEksplozywność trenuje się przez szybkosiłowe, sprężyste ruchy. Zasada za tym wykorzystuje naturalne napięcie twoich mięśni: mięsień, który jest krótko wstępnie rozciągnięty i natychmiast się kurczy — jak przy sprężystym skoku —, tworzy więcej siły niż z miejsca. Właśnie ta sprężyna tkwi w każdym dobrym zrywie i odbiciu.\n\nTyle zasada. Przy wykonaniu ostrożność jest najważniejszym towarzyszem. Szybkosiłowe skoki mocno obciążają ścięgna i stawy. Należą na koniec solidnej podstawy, nie na początek, i wymagają czystej techniki — miękkie, kontrolowane lądowanie jest ważniejsze niż duża wysokość. Kto zbyt szybko zwiększa obciążenie, ryzykuje właśnie tę kontuzję, której dobry trening ma zapobiegać.\n\nDlatego jasna rada: pierwsze kroki w stronę skoczności robisz najlepiej z wykwalifikowanym prowadzeniem, które ma na oku technikę i progresję. Pokaże ci, które ruchy pasują do twojego stanu i jak bezpiecznie budować.\n\nEksplozywność jest jak napięta sprężyna. Właściwie użyta wystrzeliwuje mocno do przodu. Przeciągnięta lub źle obciążona, ustępuje. Budowa decyduje, które z dwojga nastąpi.',
  'Obserwuj w swojej grze momenty eksplozywne: pierwszy krok z pozycji podstawowej, odbicie do wysokiej piłki, przełączenie kierunku. Gdzie ruszasz za późno lub zbyt ociężale? To pokazuje ci, gdzie eksplozywność dałaby ci najwięcej. Jeśli chcesz celowo pracować nad skocznością, weź do tego wykwalifikowane prowadzenie — zadba o bezpieczną technikę i właściwą budowę. Sam zwracaj uwagę przede wszystkim na jedno: miękkie, kontrolowane lądowanie przy wszystkim, co skaczesz.',
  'Stabilność tułowia i przenoszenie siły',
  'Mocne uderzenie nie powstaje w ramieniu. Zaczyna się w nogach, biegnie przez tułów i kończy w bacie nadgarstka. Tułów — brzuch, plecy, głęboka muskulatura wokół kręgosłupa — to decydujące ogniwo w tym łańcuchu. Jest stabilny, przenosi siłę bez strat. Jest słaby, siła rozprasza się w drodze w górę.\n\nTo powód, dla którego stabilność tułowia w crossmintonie tak wiele daje. Twoja siła uderzenia bierze się z całego ciała, a tułów to most, przez który płynie. Badania sportowców rakietowych pokazują: stabilny tułów poprawia prędkość uderzenia, a także dokładność i kontrolę nad podcięciem. Zarazem chroni — stabilny tułów odciąża bark, łokieć i plecy, które inaczej musiałyby wyrównywać słabe przenoszenie siły.\n\nStabilność tułowia budujesz ćwiczeniami, które trzymają ciało stabilnie wobec ruchu — ćwiczeniami izometrycznymi, w których trzymasz pewną pozycję wobec grawitacji lub wobec obrotu. Piękne w tym: te ćwiczenia są mało ryzykowne i nie potrzebują sprzętu. Ważna jest czysta postawa, nie czas trwania czy ilość.\n\nTułów jest jak pień drzewa, z którego wyrastają gałęzie. Mocny pień niesie potężne gałęzie, które gną się na wietrze, nie łamiąc się. Miękki pień pozwala każdej sile pójść na marne.\n\nPonieważ ćwiczenia tułowia są mało ryzykowne, tu możesz dobrze zacząć sam — ze skupieniem na czystej postawie. Do trudniejszych wariantów i właściwego wykonania także tu opłaca się sprawdzające spojrzenie kogoś z doświadczeniem.',
  {
    titel: 'Trzymać tułów stabilnie',
    ziel: 'Wzmocnić głęboką muskulaturę tułowia jako stabilny most przenoszenia siły — ze skupieniem na postawie.',
    schritte: [
      'Przyjmij stabilną pozycję izometryczną, w której trzymasz tułów pewnie wobec grawitacji — na przykład podpór na przedramionach z prostym ciałem.',
      'Zwróć uwagę na czystą linię: żadnego zapadania, żadnego przeprostu w lędźwiach, brzuch pozostaje napięty.',
      'Trzymaj pozycję spokojnie, dopóki postawa pozostaje czysta, i zakończ ją, gdy tylko forma słabnie.',
      'Uzupełnij ćwiczeniami, które stabilnie amortyzują obrót, by wesprzeć rotację twoich uderzeń.',
      'Wplataj ćwiczenia regularnie, z przerwami między jednostkami.',
    ],
    selbstkontrolle: 'Czy twoja postawa pozostaje czysta, czy ciało zapada się, gdy tylko robi się ciężko? Jakość idzie wyraźnie przed czasem — krótka, czysta pozycja izometryczna daje więcej niż długa, przy której forma się rozpada. Jeśli czujesz obciążenie w plecach zamiast w tułowiu, przerwij i sprawdź postawę.',
    abschluss: 'Stabilny tułów opłaca się podwójnie: więcej siły w uderzeniach i mniej obciążenia dla podatnych na kontuzje stawów. To niewidzialna podstawa twojego bata.',
  },
  'Wytrzymałość specyficzna — charakter interwałowy',
  'Crossminton to nie bieg ciągły. To nieustanna przemiana krótkich, wysoko intensywnych wymian i małych przerw między nimi — i to przez całego seta. Właśnie ten wzorzec musisz trenować, jeśli pod koniec seta nie chcesz się załamać. Sama równomierna wytrzymałość ciągła do tego nie wystarcza.\n\nKlucz tkwi w charakterze interwałowym. Twoje ciało musi nauczyć się przywołać intensywne obciążenie, w krótkiej przerwie częściowo się zregenerować i potem natychmiast znów dać pełny gaz — raz za razem. Ta zdolność powtarzania intensywnych akcji to coś innego niż długie równomierne wytrzymywanie. Miesza stronę wytrzymałościową i szybkosiłową.\n\nDobre jest to: ten charakter interwałowy trenujesz najlepiej w samej grze i w formach bliskich grze. Kto intensywne wymiany świadomie rozgrywa w pełni, krótką przerwę wykorzystuje na częściową regenerację i potem następną znów podejmuje z pełnym zaangażowaniem, trenuje właśnie właściwy wzorzec. Uzupełniająco pomaga solidna wytrzymałość bazowa jako baza, na której interwały się osadzają.\n\nTwoja wytrzymałość w crossmintonie jest jak akumulator, który w przerwach krótko się ładuje. Wytrenowany jest ten akumulator, który szybko znów się ładuje i natychmiast oddaje dużo mocy — nie ten, który tylko długo równomiernie trzyma.\n\nWażna pozostaje cierpliwa budowa. Intensywne interwały są wymagające — zwiększaj je powoli i daj ciału między jednostkami czas na regenerację.',
  {
    titel: 'Grać intensywnie, krótko się regenerować',
    ziel: 'Trenować interwałowy wzorzec crossmintona — pełne wymiany, krótka częściowa regeneracja, znów pełnia.',
    schritte: [
      'Rozgrywaj wymiany świadomie z pełnym zaangażowaniem, zamiast je skracać.',
      'Wykorzystuj krótką przerwę po nich na świadome złapanie oddechu i krótką regenerację.',
      'Podejmij następną wymianę znów z pełnym zaangażowaniem, zanim całkiem się zregenerujesz.',
      'Korzystaj z form bliskich grze, w których intensywne fazy i krótkie przerwy następują po sobie.',
      'Trzymaj wysoką jakość ruchu i zakończ jednostkę, gdy wyraźnie słabnie.',
    ],
    selbstkontrolle: 'Czy po krótkich przerwach potrafisz znów przywołać intensywność, czy każda wymiana robi się słabsza? Jeśli jakość mocno spada, potrzebujesz albo więcej wytrzymałości bazowej jako bazy, albo dłuższych przerw. Zwiększaj intensywność powoli i daj sobie między wymagającymi jednostkami regenerację.',
    abschluss: 'Kto trenuje wzorzec interwałowy, w trzecim secie wciąż jest obecny, gdy inni się załamują. To często różnica, która rozstrzyga wyrównane mecze.',
  },
  'Sterowanie obciążeniem i regeneracja',
  'Im bardziej celowo trenujesz, tym ważniejsze staje się pytanie, jak zrównoważyć obciążenie i regenerację. W części dla początkujących chodziło o to, że regeneracja w ogóle należy do treningu. Teraz chodzi o to, by świadomie nią sterować — na przestrzeni tygodnia treningowego, na przestrzeni turnieju.\n\nZasada podstawowa jest prosta i mimo to często lekceważona: twoje ciało staje się silniejsze w regeneracji, nie w obciążeniu. Obciążenie stawia bodziec, regeneracja buduje adaptację. Brakuje regeneracji, efekt się odwraca — robisz się bardziej zmęczony zamiast silniejszy i z czasem bardziej podatny na kontuzje. Więcej nie jest tu automatycznie lepsze.\n\nSterować obciążeniem znaczy na przemian dawać dni ciężkie i lekkie, po wymagających jednostkach planować regenerację i słuchać sygnałów swojego ciała. Utrzymujące się zmęczenie, spadająca forma mimo treningu, małe dolegliwości, które nie znikają — to znaki, że równowaga się przechyla. Traktowanie ich poważnie to znak doświadczenia, nie słabości.\n\nSzczególnie wokół turniejów opłaca się świadome spojrzenie: przed ważnymi zawodami zredukować obciążenie, byś był świeży; potem podarować ciału regenerację. Sen jest i pozostaje przy tym najważniejszym czynnikiem regeneracji.\n\nTrening jest jak napinanie łuku. Napięcie daje siłę — ale łuk, który stale pozostaje napięty, traci swoją sprężystość. Dopiero gra napinania i luzowania trzyma go mocnym.\n\nUwaga na koniec: do konkretnego sterowania twoim obciążeniem — zwłaszcza gdy trenujesz poważnie lub grasz zawody — wykwalifikowane prowadzenie jest cenne. A wszystko, co wygląda na kontuzję, należy fachowo zdiagnozować, nie zatrenować.',
  'Obserwuj przez tydzień, dwa swoją relację obciążenia i regeneracji: czy na przemian dajesz dni wymagające i lekkie, czy stale dajesz pełny gaz? Jak twój sen? Zwróć uwagę na sygnały ostrzegawcze — utrzymujące się zmęczenie, spadająca forma mimo treningu, małe dolegliwości, które zostają. Postanów sobie po wymagających jednostkach świadomie planować regenerację. Jeśli trenujesz poważnie lub grasz zawody, weź do sterowania obciążeniem wykwalifikowane prowadzenie — a wszystko, co kontuzyjne, zdiagnozuj fachowo.',
];

const r1 = insertPl('data/bausteine.fortgeschritten-mentales.json', MENTALES);
const r2 = insertPl('data/bausteine.fortgeschritten-athletik_kondition.json', ATHLETIK);
console.log(`Ring 6 pl: mentales ${r1.knoten} + athletik ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
