// Ring 14 (pl): regeln.json — 146 Knoten in Dokumentreihenfolge
// (13 Abschnitte je titel + optionale einleitung, 42 Regeln je titel + inhalt + erklaerung).
// Titel INLINE (via text()) — direkt übersetzt, nicht gespiegelt. _meta bleibt untranslated.
import { insertPl } from './pl-core.mjs';

const PL = [
  'Podstawowe pojęcia',
  'Kilka pojęć, które w zasadach powracają raz za razem. Kto je zna, rozumie resztę bez trudu.',
  'Kort, pole gry i strefa bezpieczeństwa',
  'Kort składa się z dwóch pól gry, ustawionych równolegle do siebie w odległości 12,80 m. Strefa bezpieczeństwa to powierzchnia wokół i między polami gry.',
  'Nie gracie ponad siatką, lecz ponad przerwą. Między twoim a polem przeciwnika leży wolna przestrzeń 12,80 m — strefa bezpieczeństwa. Tam speedera zagrać nie wolno; musi przejść ponad strefą w pole przeciwnika.',
  'Speeder i rakieta',
  'Piłkę nazywa się speederem. Gra się rakietą.',
  'Speeder to specjalna piłka crossmintona — cięższa i szybsza niż lotka, o stabilnym torze lotu.',
  'Gra pojedyncza i podwójna',
  'Gra pojedyncza: jeden gracz w każdym polu. Gra podwójna: dwoje graczy w każdym polu.',
  'W grze pojedynczej stoisz sam naprzeciw przeciwnika. W grze podwójnej dzielisz pole z partnerem — z własnymi zasadami, zobacz rozdział o grze podwójnej.',
  'Serwujący, odbierający i wymiana',
  'Serwujący to strona serwująca, odbierający to strona odbierająca. Wymiana to ciąg uderzeń od serwisu aż do momentu, w którym speeder jest poza grą.',
  'Każda wymiana zaczyna się serwisem i trwa, aż speeder dotknie podłoża albo zdarzy się błąd. Ten ciąg nazywa się wymianą.',
  'Sprzęt (speeder i rakieta)',
  'Wersja ICO 2024 ma własny rozdział o sprzęcie. Ustala, które speedery i rakiety są zgodne z przepisami — reszta wyboru pozostaje wolna.',
  'Wymiary speedera',
  'Speeder waży co najmniej 8 i najwyżej 10 gramów (w kategorii wiekowej U12: 6 do 10 gramów). Ma 57 do 63 mm wysokości, koszyk mierzy w najszerszym miejscu 47 do 53 mm. Główka uderzeniowa jest półkulista, z termoplastu, o średnicy 25 do 27 mm. Oficjalną piłką meczową jest żółty Match Speeder; w U12 obowiązuje czerwony Fun Speeder.',
  'Nie każdy speeder nadaje się na turniej: waga, wysokość i kapturek są dokładnie określone. W zawodach grasz żółtym Match Speederem, u najmłodszych wolniejszym czerwonym Fun Speederem.',
  'Pierścień wiatrowy, wiatr i zmiana kształtu',
  'Gumowy pierścień bezpośrednio pod główką uderzeniową może przekroczyć maksymalną wagę o 1 gram. Przy silnym wietrze, po uzgodnieniu z organizatorem i za zgodą sędziego głównego, można użyć innego speedera. Kształt speedera nie może się zmieniać przed meczem ani w jego trakcie; działania, które mogłyby na niego wpłynąć — na przykład wkładanie do kieszeni spodni — są zabronione.',
  'Przeciw wiatrowi dozwolony jest pierścień wiatrowy (może uczynić piłkę nieco cięższą), przy silnym wietrze po uzgodnieniu także cięższy speeder. Czego ci nie wolno: zmieniać kształtu speedera — także przez kieszeń spodni.',
  'Wymiary rakiety',
  'Rakieta ma najwyżej 61 cm długości, główka mierzy najwyżej 650 cm² (wymiary zewnętrzne). W U12 długość i wielkość główki mogą odbiegać. Niedozwolone jest żadne urządzenie, które zmienia jakość lotu speedera, sztucznie wpływa na jego właściwości albo zagraża przeciwnikom lub partnerom.',
  'Uregulowane są tylko dwie górne granice — długość i główka — plus zakaz zagrożeń i manipulacji. Waga, materiał, balans, naciąg i chwyt pozostają twoim wolnym wyborem.',
  'Losowanie przed rozpoczęciem gry',
  'Kto wybiera co',
  'Przed rozpoczęciem gry przeprowadza się losowanie — zwykle przez rzut speederem; decyduje kierunek, w którym główka uderzeniowa wskazuje na podłożu. Strona wygrywająca decyduje albo, czy najpierw serwuje czy odbiera, albo po której stronie zaczyna. Strona przegrywająca decyduje o pozostałej możliwości.',
  'Zamiast monety rzucasz speederem: w którą stronę kapturek wskazuje na podłożu, ta strona wygrywa wybór. Kto wygra, wybiera jedno — serwis/odbiór albo stronę. Drugie zostaje przeciwnikowi.',
  'Role w grze podwójnej',
  'W grze podwójnej strona serwująca informuje odbierającą, kto pierwszy serwuje (gracz tylny). Strona odbierająca decyduje swobodnie, kto jest graczem atakującym, a kto tylnym.',
  'Już przed pierwszą piłką ustalacie w grze podwójnej swoje role — kto zaczyna z przodu jako gracz atakujący, a kto z tyłu jako gracz tylny.',
  'Punkty i sety',
  'Best of 3',
  'Mecz toczy się w formacie Best of 3 sety: do wygrania meczu potrzebne są dwa wygrane sety.',
  'Musisz wygrać dwa sety. Przy stanie 1:1 w setach decyduje trzeci.',
  '16 punktów — i reguła 15:15',
  'Strona, która pierwsza osiągnie 16 punktów, wygrywa seta — z jednym wyjątkiem: przy stanie 15:15 wygrywa strona, która ma 2 punkty przewagi.',
  'Normalnie wystarczy mieć pierwszy 16. Ale gdy jest 15:15, musisz odskoczyć o dwa punkty — przy 15:15 gra więc trwa, aż jedna strona prowadzi dwoma punktami. To czyni wyrównane sety szczególnie nerwowymi.',
  'System punktu za wymianę',
  'Kto wygra wymianę, otrzymuje punkt — niezależnie od tego, kto serwował. Strona wygrywa wymianę, gdy druga popełni błąd albo speeder dotknie podłoża w polu przeciwnika.',
  'Każda wymiana przynosi punkt, wszystko jedno, kto serwował. Nie ma „serwisu bez szansy na punkt" — każda wymiana się liczy.',
  'Kto zaczyna następnego seta',
  'Strona, która przegrała seta, zaczyna następnego seta serwisem.',
  'Małe wyrównanie: przegrasz seta, możesz serwować w następnym.',
  'Zmiana stron',
  'Kiedy zmienia się strony',
  'Strony zmieniają się: po pierwszym secie; po drugim secie, jeśli jest trzeci; i w trzecim secie co 6 rozegranych punktów.',
  'Żeby nikt nie miał niekorzyści przez światło, wiatr czy podłoże, zmieniacie strony — między setami, a w secie decydującym nawet co 6 punktów.',
  'Zapomniana zmiana stron',
  'Jeśli zmiana stron została pominięta, następuje ona, gdy tylko błąd zostanie zauważony, a speeder nie jest w grze. Stan punktowy pozostaje.',
  'Zapomnicie o zmianie, po prostu nadrabiacie ją, gdy tylko to zauważycie — punkty zostają, jak są.',
  'Serwis',
  'Serwis ma najdokładniejsze zasady w całej grze. Kto je zna, nie oddaje punktów przez nieważne serwisy.',
  'Ze strefy serwisowej',
  'Serwujący stoi w tylnej części pola gry (strefa serwisowa), nie przekraczając w chwili uderzenia żadną częścią stopy (wyobrażonej) linii serwisowej.',
  'Serwujesz z tylnego obszaru swojego pola i nie możesz przy tym wykroczyć do przodu za linię serwisową.',
  'Jedna stopa na podłożu',
  'Od początku do końca serwisu jedna stopa serwującego musi dotykać podłoża.',
  'Przy serwisie nie możesz się odbić — jedna stopa pozostaje cały czas na podłożu.',
  'Speeder poniżej dłoni uderzającej',
  'W chwili trafienia w rakietę cały speeder musi być poniżej dłoni uderzającej serwującego.',
  'To centralna reguła serwisu: trafiasz speedera od dołu. Cały speeder jest w chwili trafienia niżej niż twoja dłoń uderzająca — serwis powyżej wysokości barku jest nieważny.',
  'Do przodu i bez zwlekania',
  'Po rozpoczęciu serwisu rakieta musi być prowadzona do przodu aż do końca ruchu (bez przerywania). Serwisu nie wolno celowo opóźniać, gdy obie strony są gotowe.',
  'Ruch serwisu biegnie jednym ciągiem do przodu — nie możesz go zatrzymać ani zwieść nim. A gdy oboje są gotowi, grasz sprawnie.',
  'Tylko gdy odbierający jest gotowy',
  'Serwujący może zacząć tylko, gdy odbierający jest gotowy. Odbierający jest gotowy, gdy widać, że chce odebrać serwis.',
  'Nie serwuj, dopóki przeciwnik jeszcze nie stoi. Dopiero gdy jest widocznie gotowy, możesz serwować.',
  'Trzy serwisy z rzędu',
  'Każda strona wykonuje 3 kolejne serwisy, zanim druga strona otrzyma prawo serwisu.',
  'Serwujesz trzy razy z rzędu, potem prawo serwisu przechodzi do przeciwnika. To nadaje grze rytm.',
  'Od 15:15 po każdym punkcie',
  'Przy stanie 15:15 prawo serwisu zmienia się po każdym punkcie.',
  'W końcowej fazie wyrównanego seta nikt nie może już odskoczyć na trzech serwisach — od 15:15 prawo serwisu wędruje po każdym pojedynczym punkcie.',
  'Po serwisie swobodnie',
  'Po serwisie serwujący może wyjść ze strefy serwisowej.',
  'Gdy tylko serwis wyjdzie, jesteś swobodny — poruszasz się normalnie po polu i grasz wymianę.',
  'Ekstremalna pogoda: 30 sekund',
  'W ekstremalnych warunkach pogodowych serwis musi nastąpić najpóźniej 30 sekund po zakończeniu poprzedniego punktu.',
  'Na zewnątrz przy wietrze, upale czy zimnie gra nie ma się zacinać: po każdym punkcie masz wtedy najwyżej 30 sekund do następnego serwisu. Ten wymóg doszedł z wersją 2024.',
  'Gra pojedyncza',
  'Serwis i przebieg w grze pojedynczej',
  'Serwuje się z tylnej części kortu (strefa serwisowa), z każdej pozycji w niej. Podczas wymiany serwujący i odbierający grają speedera na przemian z każdej pozycji, aż wyjdzie z gry.',
  'W grze pojedynczej jest prosto: serwis z tylnego obszaru, potem gracie na przemian, gdzie chcecie, aż wymiana się skończy.',
  'Gra podwójna',
  'Gra podwójna ma własne zasady dotyczące ról, kolejności serwisu i pozycji. Ich znajomość zapobiega dającym się uniknąć stratom punktów.',
  'Role w grze podwójnej',
  'Jeden gracz strony serwującej serwuje ze strefy serwisowej. Każdy gracz strony odbierającej uchodzi za odbierającego. Po serwisie speedera może grać każdy gracz strony z każdej pozycji (uwzględnij regułę pozycji).',
  'Dzielicie się na gracza atakującego (z przodu) i gracza tylnego (z tyłu). Po serwisie każdy z was może wziąć speedera — dopóki przestrzegacie reguły pozycji.',
  'Kolejność serwisu',
  'Prawo serwisu zmienia się w stałej kolejności: od gracza tylnego strony A (który serwuje na początku) do gracza atakującego strony B (który potem serwuje i staje się graczem tylnym), potem do partnera A, potem do partnera B, potem znów do pierwszego serwującego. Poza tą kolejnością nikt nie może serwować.',
  'Serwis wędruje w stałym łańcuchu przez wszystkich czterech graczy: A1 → B1 → A2 → B2 → znów A1. Kto serwuje, jest przy tym zawsze graczem tylnym. Tę kolejność musicie mieć w głowie.',
  'Reguła pozycji',
  'Błąd pozycyjny podczas wymiany: gracz tylny w chwili uderzenia stawia część swojej stopy bliższej linii końcowej przed stopę partnera — albo atakujący stawia swoją stopę bliższą linii końcowej za stopę partnera. Oba to błąd pozycyjny.',
  'W chwili trafienia kolejność musi się zgadzać: gracz atakujący zostaje z przodu, gracz tylny z tyłu. Zamienicie porządek w chwili uderzenia, to błąd.',
  'Skutek błędu pozycyjnego',
  'Gdy błąd pozycyjny przy serwisie albo podczas wymiany przy odbiorze zostanie ukarany, punkt jest natychmiast stracony, choć wymiana jeszcze się nie skończyła.',
  'Błąd pozycyjny kończy wymianę natychmiast na waszą niekorzyść — punkt przepada, nawet jeśli właśnie atakujecie. Dlatego opłaca się czysty podział.',
  'Ogłoszenie ról na początku seta',
  'Na początku seta najpierw strona odbierająca ogłasza, kto jest graczem atakującym, a kto tylnym, potem strona serwująca.',
  'Przed każdym setem jawnie ustalacie swoje role, żeby dla wszystkich było jasne, kto gra z przodu, a kto z tyłu.',
  'Błędy',
  'Błąd kończy wymianę i daje drugiej stronie punkt. Oto najważniejsze rodzaje błędów.',
  'Nieważny serwis',
  'Serwis, który nie jest wykonany zgodnie z zasadami serwisu, jest błędem.',
  'Obowiązuje wszystko z rozdziału o serwisie: zła postawa, wyskok, speeder trafiony za wysoko, przerwany ruch — każde naruszenie jest błędem.',
  'Speeder poza polem, o sufit lub ścianę',
  'Błąd, gdy speeder dotknie kortu poza liniami (nie na liniach ani wewnątrz nich) albo dotknie sufitu lub ścian bocznych.',
  'Na linii liczy się jako w polu. Poza nim, o sufit lub o ścianę to błąd. Inaczej niż w squashu żadna ściana tu nie gra.',
  'Speeder dotyka gracza lub przedmiotu',
  'Błąd, gdy speeder dotknie gracza lub jego odzieży — łącznie z butami i skarpetami —, albo przedmiotu lub osoby poza kortem.',
  'Jeśli speeder trafi ciebie, twoją odzież, twoje buty lub skarpety albo coś poza kortem, wymiana jest przegrana. Wersja 2024 wymienia buty i skarpety wyraźnie — jeden powód więcej dla obcisłej odzieży.',
  'Złapanie, rzucenie, podwójne dotknięcie',
  'Błąd, gdy speeder zostanie rakietą złapany/zatrzymany i potem rzucony, albo gdy zostanie dotknięty przez tego samego gracza dwa razy. Nie jest błędem, gdy speeder w jednym uderzeniu trafi jednocześnie ramę i naciąg.',
  'Musisz uderzyć speedera czysto, nie łapać i rzucać, i trafić tylko raz. Gdy w jednym uderzeniu dotknie zarazem ramy i strun, jest to dozwolone.',
  'Podwójne dotknięcie przez partnerów, speeder nie przechodzi',
  'Błąd, gdy speeder zostanie dotknięty przez jednego gracza, a potem przez jego partnera, albo gdy dotknie rakiety i potem nie poleci w kierunku drugiej strony kortu.',
  'W grze podwójnej tylko jeden z was może dotknąć speedera na jedno uderzenie. I twoje uderzenie musi faktycznie przenieść speedera na drugą stronę.',
  'Przeszkadzanie, rozpraszanie, sięganie w pole',
  'Błąd, gdy gracz przy będącym w grze speederze wejdzie na kort przeciwnika rakietą lub ciałem, przeszkodzi przeciwnikowi w prawidłowym uderzeniu albo rozproszy go krzykiem lub gestykulacją.',
  'Zostań u siebie: nie sięgać w pole przeciwnika, nie przeszkadzać przeciwnikowi i nie zakłócać go krzykiem czy gestami.',
  'In czy out — decyzja liniowa',
  'O tym, kiedy piłka jest „in", decyduje nie cały speeder, lecz jego główka. Wersja 2024 wyraźnie to sprecyzowała.',
  'Główka decyduje',
  'Główka (kapturek uderzeniowy) speedera uderza pierwsza. Dotknie główka linii — piłka jest „in". Nie dotknie główka linii — piłka jest „out", nawet jeśli inna część speedera dotknie linii.',
  'Patrz na kapturek, nie na koszyk: tylko gdy główka trafi linię, piłka liczy się jako w polu. Jeśli tylko koszyk musnie linię, podczas gdy główka ląduje obok, jest na aucie.',
  'Ślad poślizgu przy linii przedniej',
  'Gdy speeder ląduje przed linią przednią i zostawia widoczny ślad poślizgu, uchodzi za „in" tylko wtedy, gdy ślad jest najwyżej tak długi jak główka speedera.',
  'Jeśli speeder ślizga się przed linią przednią jeszcze w linię, decyduje długość śladu poślizgu: jest dłuższy niż główka, pierwszy kontakt z podłożem był za daleko z przodu — piłka jest na aucie. To też jest nowe w wersji 2024.',
  'Powtórzenia',
  'Czym jest powtórzenie',
  'Przy powtórzeniu serwis ostatniej wymiany jest nieważny, a ostatnio serwujący gracz powtarza serwis.',
  'Powtórzenie (w tenisie „let") oznacza: wymiana się nie liczy, nie ma punktu, ten sam serwis gra się jeszcze raz.',
  'Kiedy się powtarza',
  'Powtórzenie, gdy m.in.: serwujący uderzy, zanim odbierający jest gotowy; błąd zostanie popełniony jednocześnie przez obie strony; speeder jest uszkodzony lub się odkształca; dwa speedery spotkają się w powietrzu; linia zostanie przesunięta podczas wymiany; gra zostanie zakłócona; albo przedmiot wpadnie w pole gry podczas wymiany.',
  'Zawsze, gdy zdarzy się coś niesprawiedliwego lub nieprzewidzianego, czego nie można przypisać żadnej stronie, wymiana jest powtarzana zamiast przyznania punktu. Wersja 2024 wymienia dodatkowo dwa zderzające się speedery i przesuniętą w grze linię.',
  'Kiedy speeder jest poza grą',
  'Koniec wymiany',
  'Speeder nie jest już w grze, gdy dotknie podłoża kortu albo gdy jest błąd lub powtórzenie.',
  'Wymiana kończy się w chwili, gdy speeder dotknie podłoża albo nastąpi błąd lub powtórzenie. Do tego czasu jest w grze.',
  'Porozumienie bez sędziego',
  'W grach bez sędziego pokazujecie decyzje prostym znakiem ręcznym wolnej ręki.',
  'Trzy znaki ręczne',
  '„In": palec wskazujący wolnej ręki wskazuje w dół. „Out": palec wskazujący wskazuje w górę. „Powtórzenie": palec wskazujący i środkowy wskazują w górę jako „V".',
  'Zapamiętaj kierunek: palec wskazujący w dół znaczy „w polu" (speeder był w polu), w górę znaczy „aut". V z dwóch palców znaczy „powtórzenie". Tak wyjaśniacie piłki uczciwie bez sędziego.',
];

const r = insertPl('data/regeln.json', PL);
console.log(`Ring 14 pl: regeln ${r.knoten} Knoten.`);
