// Ring 7 (pl): Ausrüstung-Fortgeschritten (6) + Fortgeschritten-Doppel (23) = 29 Knoten
// (inkl. 1 BAD-Delta) — damit Fortgeschritten-Stufe komplett polnisch.
import { insertPl } from './pl-core.mjs';

const AUSRUESTUNG = [
  'Naciąg',
  'Naciąg to miejsce, w którym crossminton najwyraźniej różni się od badmintona — i wokół którego krąży najwięcej nieporozumień, bo wielu graczy przychodzi z badmintona. Kto po prostu przenosi badmintonowe nawyki, tutaj się myli.\n\nNaciąga się strunami do squasha lub tenisa, o grubości najwyżej około 1,25 milimetra. Dla porównania: w badmintonie zwykłe jest około 0,65 milimetra. Powód tkwi w piłce. Speeder o wadze 8 do 10 gramów przy tempie do blisko 290 kilometrów na godzinę obciąża struny nieporównanie mocniej niż lotka; cienka struna badmintonowa nie wytrzymałaby tego długo. Używa się miększych strun multifilamentowych, które oszczędzają ramię, ale szybciej tracą właściwości, oraz twardszych strun monofilamentowych, które trzymają dłużej i dają bardziej bezpośrednie czucie.\n\nWłaściwym pokrętłem jest twardość. Twardszy naciąg daje ci więcej kontroli i czucia piłki, a mniej siły ze struny; miększy odwraca to. Poglądowym modelem na to jest trampolina: luźno napięte płótno odrzuca piłkę mocno, ciasno napięte ustępuje mniej, za to daje się dokładniej sterować. Wynika z tego zasada, która pochodzi z badmintona i dobrze się przenosi: kto nie czerpie jeszcze dość siły z własnej techniki, zyskuje z miększym naciągiem; kto ma dość siły, a mimo to traci na długości, zyskuje z twardszym. Najprostszy autotest: jeśli twoje piłki regularnie wylatują poza pole, przemawia to za twardszym; jeśli padają za krótko, za miększym.\n\nZmieniaj twardość ostrożnie i małymi krokami. Duży skok kosztuje cię czucie piłki, odbiera za dużo siły i obciąża ramię uderzające — to punkt, w którym zły sprzęt szkodzi ciału. Lepiej podchodź do swojej wartości powoli.\n\nKilka wartości orientacyjnych dla ustawienia, nie przepisów: na rakietach turniejowych stoi często zalecenie w rodzaju „16 x 14 kp" — 16 kilopondów wzdłuż, 14 w poprzek, jako zalecane maksimum. Ramy aluminiowe znoszą mniej, przeważnie do około 12 kilopondów; ramy karbonowe leżą powyżej. Za zgrubną granicę uchodzi, by iść najwyżej około dwóch kilopondów ponad zalecenie na ramie — kilopond i kilogram oznaczają przy tym to samo. A ponieważ naciąg także bez zerwania z tygodniami traci napięcie, zerwana struna to najpóźniejszy, nie najlepszy moment na nowy naciąg.',
  'Sprawdź, co na twojej ramie stoi jako zalecany naciąg i czy jest z aluminium czy z carbonu — to wyznacza ramy, w których możesz się poruszać. Potem obserwuj swoje piłki w następnym meczu: padają raczej za krótko, czy wylatują za długo? Jeśli chcesz w związku z tym coś zmienić, zmień to małym krokiem i wsłuchaj się, zanim pójdziesz dalej.',
  'Chwyt i owijka',
  'Grubość chwytu to niepozorna wielkość o wielkim wpływie — na twój nadgarstek i na twoje zdrowie. Zasada pochodzi z badmintona: gdy chwytasz rakietę normalnie, między czubkami palców a kłębem dłoni powinno zostać mniej więcej tyle miejsca, ile wynosi szerokość małego palca. Inaczej mówiąc, kciuk dotyka chwytu, nie zachodząc na pozostałe palce.\n\nNiebezpieczny błąd idzie w dół. Jeśli chwyt jest za cienki, czubki palców wbijają się w kłąb, i musisz stale mocno ściskać rakietę, żeby nie obracała się przy uderzeniu. To stałe napięcie wędruje w przedramię i uchodzi za jeden z głównych wyzwalaczy łokcia tenisisty. Dla twojej gry ma to bezpośrednie następstwo: luźny chwyt jest warunkiem bata z nadgarstka. Zbyt cienki chwyt czyni tę swobodę niemożliwą — wtedy materiał pracuje przeciw twojej technice.\n\nNa chwycie siedzą do trzech warstw. Owijka bazowa jest założona fabrycznie, około 1,8 milimetra grubości, tłumi wibracje i trzyma długo. Owijka wierzchnia jest z 0,4 do 0,7 milimetra cienka, nawija się ją na wierzch i jest częścią zużywalną. Owijka frotté jest grubsza i chłonie pot jak ręcznik — właściwy wybór do mocno pocących się dłoni, często razem z odrobiną pudru do chwytu.\n\nOwijka wierzchnia jest zarazem twoim narzędziem do drobnego regulowania grubości chwytu: każda warstwa zwiększa średnicę. Jeśli wiesz, że i tak używasz owijki wierzchniej, wybierz rakietę od razu o numer cieńszą. Odwrotnie, możesz nawinąć owijkę wierzchnią wprost na goły chwyt, by chwytać szczególnie cienko. Za górną granicę uchodzi: owijka bazowa plus jedna wierzchnia; wszystko ponad to robi się za grube.\n\nOwijki wierzchnie to części zużywalne. Po kilku tygodniach tracą chwytność — wtedy je wymieniasz, zamiast od razu odnawiać droższą owijkę bazową. Owijka bazowa trzyma zależnie od stanu około pół roku. A ponieważ chwyt to miejsce, w którym pot i dłoń schodzą się najdłużej, trzymaj go czysto i wymień, gdy się wytrze.',
  'Chwyć rakietę tak, jak trzymasz ją w grze, i wsuń palec między czubki palców a kłąb dłoni: mieści się dobrze mały palec, czy jest ciaśniej? Zwróć w następnej wymianie uwagę, czy musisz ściskać chwyt, żeby się nie obracał — znak, że jest dla ciebie za cienki. I sprawdź swoją owijkę wierzchnią: jest jeszcze chwytna, czy czas na świeżą?',
];

const DOPPEL = [
  'Gra podwójna jako osobna gra',
  'We wprowadzeniu do debla poznałeś strukturę podstawową: gracza atakującego i tylnego, kolejność serwisu, regułę stopy, pierwsze porozumienie. Ten blok tematyczny wchodzi w głąb — i pokazuje ci, że debel to gra o własnych prawach, która sięga przez wszystkie obszary twojej gry.\n\nSzczególne w deblu jest to, że wszystko się podwaja i zarazem połowi. Kryjecie powierzchnię we dwoje, więc każdy musi ogarnąć mniej terenu sam — ale tylko wtedy, gdy mądrze się dzielicie. Jeśli wchodzicie sobie w drogę, w rzeczywistości kryjecie mniej niż pojedynczy gracz, który wie, dokąd ma iść.\n\nDlatego dobry debel dotyka więcej niż taktyki. Wymaga współdziałania taktycznego (kto atakuje, kto asekuruje), zgranego ruchu (jako jedność po polu) i ciągłego porozumienia (krótki okrzyk, umowa). Te trzy nici — taktyka, ruch, komunikacja — schodzą się w deblu razem. Kolejne moduły podejmują je po kolei.\n\nDobry debel jest jak para taneczna. Dwoje ludzi porusza się jako jedna figura, każdy wie, co robi drugi, i z dwojga pojedynczych powstaje jedność, która potrafi więcej niż oboje razem. Zły debel jest jak dwoje tancerzy do tej samej muzyki, którzy nadeptują sobie na stopy.\n\nKto pojmuje debla jako osobną grę, a nie jako singiel we dwoje, zrobił już najważniejszy krok.',
  'Wróć myślami do swojego ostatniego debla: poruszaliście się jako jedność, czy byliście dwoma pojedynczymi graczami na jednym polu? Gdzie leżały luki — w środku, bo nikt nie szedł, czy po bokach, bo oboje biegli do środka? Weź do kolejnych modułów to jedno pytanie: na której z trzech nici — współdziałaniu, ruchu, porozumieniu — zacina się u was najbardziej?',
  'Atak w parze',
  'W ataku wasza para gra swoją największą siłą: możecie naciskać przeciwnika i zarazem natychmiast zamykać luki. Udaje się to przez jasny podział zadań między tyłem a przodem.\n\nGracz tylny to silnik ataku. Z tyłu kładzie mocne, głębokie uderzenia — smecz, dociskowy drive —, które zmuszają przeciwnika do podbicia speedera wysoko albo słabego odesłania. Utrzymuje presję.\n\nGracz atakujący z przodu to egzekutor. Czyha na słabe odbicie, które wywołuje presja z tyłu, i kończy je krótko i mocno, zanim przeciwnik się pozbiera. Jego zadaniem jest przechwycenie i zakończenie — stoi gotów, by każdą krótką, wysoką odpowiedź od razu wykorzystać.\n\nRazem daje to obcęgi: jeden dociska, drugi zatrzaskuje. Dopóki ten rytm biegnie — presja z tyłu, zakończenie z przodu —, wasza para pozostaje w ataku, a przeciwnik w defensywie.\n\nJesteście młotem i kowadłem. Gracz tylny to młot, który uderza z tyłu; gracz atakujący to kowadło z przodu, na którym pęka słaba piłka. Brakuje jednego z dwojga, atak ulatnia się na darmo.\n\nNajczęstszym błędem jest to, że oboje zostają z tyłu i krótkie piłki przeciwnika padają bezkarnie. Bez gracza z przodu, który kończy, najlepsza presja z tyłu pozostaje bez efektu.',
  {
    titel: 'Presja i zakończenie',
    ziel: 'Jako para utrzymać atak — tył dociska, gracz atakujący kończy.',
    schritte: [
      'Ustawcie się jako para: jeden z tyłu jako gracz tylny, jeden z przodu jako gracz atakujący.',
      'Gracz tylny kładzie głębokie, dociskowe uderzenia, które podający przeciwnik może odesłać tylko wysoko lub krótko.',
      'Gracz atakujący z przodu przechwytuje te słabe odbicia i kończy je krótko.',
      'Trzymajcie rytm przez kilka piłek: presja z tyłu, zakończenie z przodu.',
      'Zmieńcie po kilku rundach role.',
    ],
    selbstkontrolle: 'Czy gracz atakujący naprawdę przechwytuje krótkie piłki, czy padają bezkarnie? Czy presja z tyłu pozostaje dość wysoka, by wymuszać słabe odbicia? Atak niesie tylko wtedy, gdy obie role współpracują.',
    abschluss: 'Obcęgi z presji i zakończenia to figura podstawowa ataku deblowego. Gdy siedzą, wasza para staje się w ataku trudna do zatrzymania.',
  },
  'Obrona w parze',
  'Gdy przeciwnik atakuje, wasza para staje się jednostką obronną. Teraz chodzi o to, by pokryć powierzchnię, zdjąć z ataku tempo i wypatrzeć moment, w którym sami możecie znów uderzyć.\n\nNajważniejsze w obronie jest to, byście sensownie podzielili powierzchnię i nie zostawili luki, w którą przeciwnik może mocno wbić. Każdy kryje swój obszar, a najgroźniejsza przestrzeń — tam, gdzie przeciwnik może położyć swoją najmocniejszą piłkę — musi być zabezpieczona. Stoicie głębiej i szerzej, by mieć czas na reakcję.\n\nW obronie świadomie zdejmujesz tempo. Zamiast odbijać mocną piłkę mocno, odsyłasz ją kontrolowanie, kupujesz sobie czas i czekasz na błąd lub słabsze zagranie przeciwnika. Każde pewne odbicie trzyma was w wymianie i zmusza przeciwnika, by atak zbudował jeszcze raz.\n\nI wypatrujesz momentu przełączenia. Gdy tylko atak przeciwnika słabnie — krótszy smecz, wysoka piłka —, to wasz sygnał, by z obrony przejść do ataku. Obrona w deblu nigdy nie jest tylko odpieraniem; to czekanie na własną szansę.\n\nJesteście razem tarczą, która wyłapuje szturm. Tarcza z luką jest bezwartościowa — sztuką jest, by wasze dwie połowy bez luk wchodziły jedna w drugą, aż atak się wyczerpie.',
  {
    titel: 'Kryć powierzchnię, zdejmować tempo',
    ziel: 'Jako para wyłapać atak, bez luki, i wypatrzeć moment przełączenia.',
    schritte: [
      'Niech przeciwnicy atakują was jako parę (mocne, głębokie piłki).',
      'Podzielcie powierzchnię jasno, tak by nie zostawała luka na mocną piłkę.',
      'Odsyłajcie piłki ataku kontrolowanie, zamiast odpowiadać mocno — zdejmujcie tempo.',
      'Uważajcie na moment, w którym atak słabnie, i przełączcie się wtedy wspólnie na atak.',
      'Zmieńcie po kilku rundach role ataku i obrony par.',
    ],
    selbstkontrolle: 'Czy między wami zostaje luka, w którą przeciwnik mocno wbija? Czy zdejmujecie dość tempa, by zostać w wymianie? I czy rozpoznajecie moment, w którym możecie się przełączyć? Dobra obrona kryje bez luk i cierpliwie czeka na szansę.',
    abschluss: 'Obrona, która nie zostawia luki i wykorzystuje moment przełączenia, wyprowadza was z opresji z powrotem do ataku.',
  },
  'Ruch jako jedność',
  'Dwoje graczy, którzy dobrze się poruszają, to jeszcze nie dobry debel. Dopiero gdy poruszacie się dostrojeni do siebie — jako jedność, nie jako dwoje pojedynczych —, naprawdę pokrywacie pole. To atletyczna strona debla.\n\nReguła podstawowa brzmi: jesteście połączeni, jakby wisiała między wami niewidzialna nić. Poruszy się jeden w lewo, drugi przesuwa się razem, by zamknąć powstającą lukę. Idzie jeden do przodu do piłki, drugi asekuruje z tyłu. Trzymacie zawsze sensowny odstęp od siebie — dość blisko, by się uzupełniać, dość daleko, by pokryć powierzchnię.\n\nWynika z tego najważniejsza dyscyplina ruchu w deblu: nigdy nie biegnijcie oboje do tej samej piłki. To najczęstszy i najdroższy błąd. Gdy oboje gonicie tego samego speedera, połowa powierzchni stoi otworem, a następna piłka przeciwnika ląduje tam z pewnością. Kto bierze piłkę, woła ją; drugi zostaje i kryje.\n\nDrogi nie są przy tym przypadkowe. Po każdym uderzeniu ustawiacie się wspólnie na nowo, tak byście znów stali wyważenie. To ciągłe wspólne przestawianie to praca — kosztuje kondycję i uwagę —, ale to różnica między parą a dwoma graczami grającymi obok siebie.\n\nJesteście jak dwie wycieraczki na przedniej szybie, które biegną synchronicznie. Poruszają się dostrojone — żadne miejsce nie zostaje suche. Biegną przeciw sobie — zakleszczają się, a szyba zostaje brudna.',
  {
    titel: 'Na niewidzialnej nici',
    ziel: 'Poruszać się jako para w zgraniu, zamykać luki, nigdy oboje do tej samej piłki.',
    schritte: [
      'Poruszajcie się jako para po polu i wyobraźcie sobie, że nić was łączy: idzie jeden, drugi przesuwa się razem.',
      'Niech ktoś gra wam piłki w różne obszary i ćwiczcie, by zawsze jeden szedł, a drugi asekurował lukę.',
      'Wołajcie przy każdej piłce, kto ją bierze, by nigdy oboje nie ruszali.',
      'Ustawiajcie się po każdym uderzeniu wspólnie na nowo, tak byście znów stali wyważenie.',
      'Zwiększajcie tempo dopiero, gdy zgrany ruch siedzi.',
    ],
    selbstkontrolle: 'Czy odstęp między wami pozostaje sensowny, czy zbijacie się w kupę i zostawiacie jedną połowę otworem? Czy biegniecie czasem oboje do tej samej piłki? Obserwujcie, czy po każdym uderzeniu ustawiacie się jako para na nowo. Zgrany ruch jest męczący i właśnie dlatego to cel treningowy.',
    abschluss: 'Ruch jako jedność to atletyczna podstawa debla. Gdy siedzi, we dwoje pokrywacie więcej, niż dwoje pojedynczych graczy kiedykolwiek mogłoby.',
  },
  'Porozumienie w parze',
  'Żaden debel nie działa w milczeniu. Porozumienie z partnerem jest tak samo ważne jak każde uderzenie — i jest zarazem mentalną stroną debla, bo decyduje, czy zrastacie się jako zespół, czy rozpadacie.\n\nPorozumienie biegnie na trzech poziomach. Przed serwisem robicie krótkie ustalenia: kto przejmuje który obszar, jaką taktykę gracie. W czasie wymiany pomagają krótkie, jasne okrzyki — „Moja!", „Twoja!", „Zostaw!" —, które w ułamkach sekundy wyjaśniają, kto bierze piłkę. Między punktami dajecie sobie krótki feedback i dostrajacie się na nowo.\n\nDecydujące jest, by okrzyki były krótkie, głośne i jednoznaczne. Wymamrotane, spóźnione słowo nie pomaga. Jasne „Moja!" we właściwym momencie zapobiega temu, byście oboje pobiegli do tej samej piłki — najdroższy błąd deblowy.\n\nStrona mentalna sięga jednak głębiej niż wołanie. W deblu także twój partner popełnia błędy, a to, jak na nie reagujesz, kształtuje całą grę. Partner, który po każdym błędzie zwiesza głowę albo obwinia drugiego, ciągnie zespół w dół. Partner, który podnosi i zostaje spokojny, trzyma go razem. Wygrywacie i przegrywacie wspólnie — ta postawa to podstawa każdego dobrego partnerstwa na polu.\n\nWasz debel jest jak łódź wioślarska z dwoma wioślarzami. Tylko gdy ciągniecie w rytmie i w tym samym kierunku, łódź płynie. Wiosłuje jeden zgorzkniale przeciw drugiemu — kręcicie się w kółko.',
  'Ustal z partnerem deblowym przed następnym meczem trzy rzeczy: jasne okrzyki na środek („Moja!"/„Twoja!"), kto w razie wątpliwości bierze piłkę w środku, i że po błędach podnosicie się nawzajem zamiast obwiniać. Zwróć w grze uwagę, czy naprawdę wołacie dość głośno i wcześnie. I obserwuj samego siebie: jak reagujesz, gdy partner popełni błąd? Twoja reakcja kształtuje zespół bardziej niż sam błąd.',
  'Serwis i odbiór w grze podwójnej',
  'Serwis otwiera także w deblu każdą wymianę — ale tutaj jest osadzony w stałym systemie i oferuje parze własne możliwości taktyczne.\n\nPrawo serwisu wędruje w deblu w stałej kolejności przez wszystkich czterech graczy, a serwującym jest zawsze gracz tylny. To znaczy: z każdą zmianą prawa serwisu wasze role układają się na nowo. Znajomość tej kolejności i trzymanie jej w głowie należy do podstaw debla — kto się pogubi, ryzykuje błędy jeszcze przed pierwszym uderzeniem.\n\nTaktycznie wykorzystujesz serwis w deblu podobnie jak w singlu, z jednym ważnym dodatkiem: twój partner z przodu jest gotów wykorzystać odbiór. Dobry serwis zmusza przeciwnika do słabej, wysokiej odpowiedzi — a właśnie ją przechwytuje twój gracz atakujący z przodu. Serwis jest tym samym pierwszym ruchem obcęgów, które zamykają się przy trzeciej piłce.\n\nPrzy odbiorze obowiązuje odwrotność: chcesz uniknąć dostarczenia graczowi atakującemu przeciwnika z przodu łatwego łupu. Odeślij odbiór kontrolowanie, w miarę możliwości głęboko lub w lukę, zamiast grać go wysoko i krótko do czyhającego egzekutora.\n\nSerwis w deblu jest jak zagranie otwierające w szachach we dwoje — otwiera plan, który dopełnia twój partner. Bezmyślny serwis marnuje tę przewagę, celowany zakłada punkt dla waszej pary.',
  'Wbij sobie z partnerem kolejność serwisu tak, byście pewnie opanowali ją w grze. Obmyślcie potem prostą taktykę serwisu: dokąd serwuje gracz tylny, by gracz atakujący z przodu mógł przechwycić słabe odbicie? A przy odbiorze: jak unikacie dostarczenia graczowi atakującemu przeciwnika łatwej piłki? Obserwujcie w grze, czy wasz serwis faktycznie przygotowuje trzecią piłkę.',
  'Przełączanie w grze podwójnej',
  'Wymiana w deblu zmienia się nieustannie między atakiem a obroną — a to, jak jako para przełączacie się między tymi stanami, decyduje, kto zachowa kontrolę. Ten moduł łączy obie role z poprzednich modułów.\n\nMoment przełączenia jest w deblu wspólny. Gdy przeciwnik pod waszą presją zagra słabą piłkę, musicie oboje jednocześnie rozpoznać: teraz atakujemy. Gdy odwrotnie przeciwnik wchodzi do ataku, musicie oboje zarazem znaleźć się w obronie. Rozpozna zmianę tylko jeden — powstaje właśnie ta luka, która kosztuje punkt.\n\nW crossmintonie to przełączanie ma pewną osobliwość. Wasze role są związane z serwisem i uformowane regułą pozycji — gracz atakujący zostaje z przodu, gracz tylny z tyłu, ich ustawienie stóp względem siebie jest w chwili trafienia narzucone. Przełączanie biegnie dlatego mniej przez swobodną zamianę pozycji, a bardziej przez zgrany wspólny ruch i jasne porozumienie: czytacie sytuację razem i reagujecie razem.\n\nDlatego dwie poprzednie nici są tu decydujące: ruch jako jedność, byście wspólnie znaleźli pozycję, i porozumienie, byście moment przełączenia wywołali razem. Krótki okrzyk we właściwym momencie — „Atak!" albo „Wracaj!" — synchronizuje was.\n\nWasze przełączanie jest jak wspólne zawracanie długiej łodzi. Tylko gdy oboje w tym samym czasie sterują w tym samym kierunku, łódź obraca się czysto. Ciągnie jeden jeszcze prosto, gdy drugi już zawraca — wszystko zaczyna się ślizgać.',
  'Obserwujcie w swoim następnym deblu momenty przełączenia: rozpoznajecie je wspólnie, czy często reaguje tylko jeden? Umówcie się na krótki okrzyk na zmianę — na przykład „Atak!", gdy przeciwnik odgrywa słabo, i „Wracaj!", gdy musicie do obrony. Zwróćcie uwagę, czy przez wspólne wywoływanie przełączacie się szybciej i bardziej zwarcie.',
  'Przełączanie w grze podwójnej — dla graczy przechodzących z badmintona',
  'Przełączanie między atakiem a obroną znasz dobrze z debla badmintonowego — ale tam znaczy ono coś innego niż tutaj, i właśnie to jest przestawka.\n\nW deblu badmintonowym przełączasz się, zmieniając formację: z ustawienia przód-tył w ataku w ustawienie bok w bok w obronie, płynnie i zależnie od tego, kto akurat uderza. To ciągłe rotowanie między dwiema formacjami siedzi w tobie głęboko.\n\nW crossmintonie tej płynnej rotacji formacji nie ma. Wasze role są związane z serwisem i uformowane regułą pozycji — gracz atakujący zostaje z przodu, gracz tylny z tyłu, a w chwili trafienia ich ustawienie stóp względem siebie jest narzucone. Przełączacie się wewnątrz sztywniejszej struktury, zamiast swobodnie zmieniać między dwiema formacjami: przez zgrany ruch i wspólne porozumienie, nie przez swobodną zamianę pozycji.\n\nPrzestaw więc swoje myślenie o przełączaniu: precz od odruchowej zmiany formacji, ku wspólnemu czytaniu i reagowaniu wewnątrz stałych, związanych z serwisem ról. Porozumienie zastępuje tu część tego, co w badmintonie robi rotacja.\n\nMały test: łapiesz się z partnerem na odruchowym rotowaniu w obronę bok w bok albo na swobodnej zamianie pozycji? To znaczy, że wciąż niesie cię debel badmintonowy. Celem jest wspólne przełączanie wewnątrz stałych, crossmintonowi własnych ról.',
];

const r1 = insertPl('data/bausteine.ausruestung-fortgeschritten.json', AUSRUESTUNG);
const r2 = insertPl('data/bausteine.doppel-thema.json', DOPPEL);
console.log(`Ring 7 pl: ausruestung ${r1.knoten} + doppel-thema ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
