// Ring 9 (pl): Experte-Mentales (15) + Experte-Athletik (15) + Doppel-Experte (15) = 45 Knoten, delta-frei.
import { insertPl } from './pl-core.mjs';

const MENTALES = [
  'Optymalny stan startowy',
  'Każdy gracz ma stan, w którym gra najlepiej: akurat właściwie pobudzony, ani zbyt spięty, ani zbyt ospały. Poznanie tego optymalnego stanu startowego i świadome jego wywoływanie to jedna z najsubtelniejszych umiejętności mentalnych eksperta.\n\nSzczególne jest to: ten punkt jest u każdego inny. Jeden gra najlepiej mocno napięty i pełen energii, drugi spokojny i opanowany. Za dużo napięcia czyni nerwowym i spiętym, za mało czyni zmęczonym i nieskupionym. Twoim zadaniem jest znaleźć swój własny optymalny punkt — przez obserwację: jak się czułeś, gdy grałeś szczególnie dobrze?\n\nNajważniejszym narzędziem, by wywołać ten stan, jest stała rutyna przedstartowa. Niezmienna sekwencja przed meczem — rozgrzewka, kilka oddechów, krótkie wyobrażenie, znajome formuły — przełącza cię w tryb startowy. Działa podwójnie: odbiera ci decyzje i daje pewność, bo już wiele razy zadziałała.\n\nA tu zmiana myślenia, która wiele zmienia: zdenerwowanie przed ważnym meczem nie jest wrogiem. Kołatanie serca, napięcie — to energia, którą twoje ciało udostępnia, by umożliwić najwyższą formę. Kto odczytuje zdenerwowanie jako pozytywny znak i wykorzystuje jego energię, zamiast z nim walczyć, gra lepiej.\n\nTwój stan startowy jest jak temperatura pracy silnika. Za zimny nie chodzi równo, za gorący się przegrzewa. Rutyna przedstartowa doprowadza cię dokładnie do temperatury, w której chodzisz najlepiej.',
  'Wróć myślami do dwóch, trzech swoich najlepszych meczów: jak się przed nimi i w ich trakcie czułeś — raczej spokojnie czy raczej mocno napięty? To wskazówka co do twojego optymalnego stanu. Zbuduj sobie z tego stałą rutynę przedstartową, która cię tam doprowadza (np. rozgrzewka, kilka świadomych oddechów, krótkie wyobrażenie, twoje formuły). I ćwicz przeformułowanie: gdy następnym razem przed ważnym meczem będziesz zdenerwowany, powiedz sobie, że ta energia ci pomaga — i wykorzystaj ją.',
  'Wejść w flow',
  'Czasem grasz jak sam z siebie. Uderzenia udają się bez namysłu, czas wydaje się wolniejszy, jesteś całkiem zatopiony w grze. Ten stan nazywa się flow i przynosi często twoje najlepsze wyniki. Ekspert uczy się go zapraszać.\n\nFlow powstaje, gdy wymaganie dokładnie pasuje do twoich umiejętności. Jest przeciwnik zbyt łatwy, robi się nudno; jest przytłaczający, powstaje presja. Pomiędzy, gdzie zadanie stawia ci akurat właściwe wyzwanie, otwiera się brama do flow. Dlatego eksperci przeżywają flow często w wyrównanych, równorzędnych meczach.\n\nFlow nie możesz wymusić na komendę — ale możesz stworzyć jego warunki. Jasne, proste cele w danym momencie. Pełna uwaga na następnej piłce, nie na wyniku. Twoja rutyna przedstartowa, która cię uspokaja i skupia. I nieobecność lęku i zwątpienia w siebie, które niezawodnie niszczą flow.\n\nNajważniejsze, gdy flow się pojawi: nie zakłócaj go namysłem. Gdy tylko zaczniesz świadomie analizować swoją technikę — „jak to ja trzymam rakietę" —, nić się rwie. We flow ufasz swojemu ciału i pozwalasz mu działać. Świadome sterowanie należy do ćwiczenia, nie do flow.\n\nFlow jest jak nurt, który cię niesie, gdy tylko przestajesz z nim walczyć. Nie możesz go pchać, ale możesz uformować brzegi tak, by płynął sam. A gdy płynie, nie stajesz w jego środku, by go badać.',
  'Przypomnij sobie moment, w którym byłeś we flow — wszystko szło jak samo z siebie. Jakie były okoliczności? Przeważnie to przeciwnik na twoim poziomie i pełna obecność w grze. Postanów sobie w następnym wymagającym meczu stworzyć te warunki: prosty cel na dany moment, pełna uwaga na następnej piłce, żadnego rozmyślania o wyniku. A gdy zacznie iść: nie analizuj, lecz daj temu płynąć.',
  'Presję traktować jako wyzwanie',
  'Decydujący punkt, piłka meczowa, ciasna końcówka — tu ekspert odróżnia się od dobrego gracza sposobem, w jaki odczytuje presję, nie lepszymi uderzeniami. A tę interpretację możesz świadomie sterować.\n\nTen sam moment można przeżyć jako zagrożenie albo jako wyzwanie. Jako zagrożenie: „byle teraz nie przegrać" — spojrzenie na niebezpieczeństwo, które paraliżuje, spina i odbiera siły. Jako wyzwanie: „teraz nadchodzi mój moment, potrafię to" — spojrzenie na szansę, które uwalnia energię i czyni ciało sprawniejszym. Różnicę robi twoja interpretacja, nie sytuacja.\n\nTrzy rzeczy sprzyjają odczytaniu jako wyzwanie. Zaufanie do twoich umiejętności — tę sytuację już opanowałeś. Poczucie kontroli — kierujesz spojrzenie na to, czym możesz sterować, na swoją następną piłkę, zamiast na wynik. I cel skierowany do przodu — „gram teraz swój wzorzec", nie „unikam błędu".\n\nDo tego dochodzi świadome przełączenie na wyższy bieg. Inaczej niż flow, który przychodzi sam, gra w decydującym momencie jest często świadomą decyzją: rozpoznajesz „teraz nadszedł czas", stawiasz sobie jasny cel i przełączasz wysiłek i intensywność o stopień wyżej. To przełącznik, który świadomie przestawiasz.\n\nPresja jest jak wiatr dla żeglarza. Kto boi się jej jak zagrożenia, zostaje wywrócony. Kto wykorzystuje ją jak wyzwanie, płynie właśnie wtedy najszybciej. Wiatr pozostaje ten sam — liczy się, jak ustawisz żagle.',
  'Wróć myślami do decydującego punktu, który przegrałeś: przeżyłeś go jako zagrożenie („byle nie przegrać") czy jako wyzwanie („teraz to pokażę")? Ćwicz na następny ważny moment świadome przeformułowanie: skieruj spojrzenie na to, co kontrolujesz (swoją następną piłkę), postaw sobie cel do przodu (grać swój niezawodny wzorzec), a presję odczytaj jako swój znak, by teraz przełączyć o stopień wyżej.',
  'Zachować spokój, gdy gra jest nie fair',
  'Nie wszystko w grze jest sprawiedliwe. Piłka, która ledwie była na aucie, a mimo to się liczy. Przeciwnik, który gra na czas albo prowokuje. Seria pecha. Ekspert wyróżnia się tym, że takie rzeczy nie wytrącają go z toru.\n\nKluczem jest proste rozróżnienie: są rzeczy, które kontrolujesz, i rzeczy, których nie kontrolujesz. Sporna decyzja, zachowanie przeciwnika, szczęście — wszystko to leży poza twoją kontrolą. Twoja reakcja na to, twoja następna piłka, twoja koncentracja — to leży w twojej ręce. Kto trwoni energię na to, co niekontrolowalne, odbiera ją temu, co kontrolowalne.\n\nSzczególnie prowokacja przeciwnika jest pułapką. Kto da się zezłościć, gra dokładnie tę grę, której chce przeciwnik — traci koncentrację i podejmuje gorsze decyzje. Najmocniejszą odpowiedzią na prowokację jest niezakłócone kontynuowanie własnej gry. Twój spokój jest zarazem twoją bronią.\n\nTo nie znaczy, że niesprawiedliwość nie może cię poruszać. Ale odhaczasz ją jak własny błąd — krótko przyjąć do wiadomości, potem świadomie skierować spojrzenie na następną piłkę. Gest odhaczenia, który znasz z części dla początkujących, pomaga i tutaj.\n\nNiesprawiedliwość jest jak zła pogoda na wędrówce. Nie możesz jej zmienić, a oburzanie się na nią nie posuwa cię ani o krok. Kto opuszcza głowę i idzie dalej, dociera; kto staje i przeklina, traci tylko czas.',
  'Przypomnij sobie mecz, w którym niesprawiedliwa decyzja lub prowokujący przeciwnik wytrącił cię ze spokoju. Ile energii kosztowała cię złość? Ćwicz rozróżnienie: co z tego mogłeś kontrolować, a czego nie? Postanów sobie następnym razem to, co niekontrolowalne, krótko odhaczyć — swoim gestem odhaczenia — i skierować energię natychmiast na swoją następną piłkę. Przeciw prowokacji twoja spokojna dalsza gra to najlepsza odpowiedź.',
  'Rozwijanie własnej siły mentalnej',
  'Siła mentalna to nie stały stan, który raz się osiąga i potem posiada. To zdolność, która rośnie przez całe życie. Dojrzały ekspert traktuje swoją grę mentalną jak techniczną: jako coś, co świadomie i na bieżąco rozwija.\n\nPierwszym krokiem jest samoświadomość. Znasz już swoje mentalne siły i swoje czułe punkty: może w budowie jesteś cierpliwy, ale przy ciasnych stanach tracisz spokój. Może grasz swobodnie, gdy prowadzisz, i spinasz się na stracie. Ta szczera samowiedza to podstawa każdego rozwoju.\n\nZ niej budujesz swoją osobistą skrzynkę narzędzi mentalnych. Z czasem nauczyłeś się, które narzędzia u ciebie działają — ta jedna technika oddechu, ta jedna formuła, ta jedna rutyna. Nie każde narzędzie działa u każdego tak samo; twoje to te, które ci niezawodnie pomagają. Ekspert zna swoją skrzynkę i sięga we właściwym momencie po odpowiednie narzędzie.\n\nA nad wszystkim stoi postawa wzrostu. Także najlepsi gracze mają mentalne porażki — przegrane bitwy nerwów, mecze, które wypuścili z rąk. Różnica jest w tym, że traktują je jako materiał do nauki, nie jako wyrok. Każdy trudny mecz to okazja, by zrobić następny krok w swoim rozwoju mentalnym.\n\nSiła mentalna rośnie z każdą przetrwaną próbą — każdy trudny mecz hartuje cię o kawałek. Uczysz się, co u ciebie się rozwija, plewisz to, co szkodzi, i patrzysz, jak całość z czasem rośnie. Żaden ogród nigdy nie jest gotowy — i właśnie to czyni go żywym.',
  'Poświęć czas na szczery bilans swojej gry mentalnej: jaka jest twoja największa siła mentalna, a jaki najbardziej czuły punkt? I które narzędzia mentalne (technika oddechu, formuła, rutyna, przeformułowanie) pomagają ci niezawodnie — twoja osobista skrzynka narzędzi? Postanów sobie pracować nad jednym jedynym punktem mentalnym przez najbliższy sezon, a porażki traktuj przy tym jako materiał do nauki, nie jako wyrok o tobie.',
];

const ATHLETIK = [
  'Planowanie formy na sezon',
  'Na poziomie eksperckim forma nie jest niczym przypadkowym. Kto chce grać stabilnie przez sezon i być na ważne turnieje w szczytowej formie, myśli w dłuższych odcinkach czasu niż pojedyncza jednostka treningowa. Ten moduł zaznajamia cię z zasadą — konkretne planowanie należy do wykwalifikowanych rąk.\n\nMyśl przewodnia jest taka, że formy nie da się trwale utrzymać na najwyższym poziomie. Są fazy, w których budujesz podstawę, fazy intensywnej pracy i fazy, w których świadomie się cofasz, by ciało mogło dokonać adaptacji. Ta zaplanowana przemiana sprawia, że szczyt przychodzi wtedy, gdy go potrzebujesz.\n\nSzczególnie ważna jest faza przed ważnymi zawodami. Kto pracuje ciężko do ostatniej chwili, wchodzi na turniej zmęczony. Kto w porę zredukuje obciążenie, dociera świeży i sprawny. To świadome cofnięcie przed szczytem to jeden ze znaków rozpoznawczych doświadczonych sportowców.\n\nTu ważna granica: dobry plan sezonu jest indywidualny i należy do rąk wykwalifikowanego prowadzenia — trenera lub specjalisty nauk o treningu. Ten moduł chce cię uwrażliwić na zasadę, nie narzucić plan. Twoim zadaniem jest myśleć w dłuższych łukach i podejść do planowania z fachowym towarzyszeniem.\n\nTwoja forma na przestrzeni sezonu jest jak wzrost w ogrodzie na przestrzeni roku. Są czasy siania, wzrostu i zbioru — i nikt nie zbiera przez cały rok. Kto chce wszystkiego naraz, nie dostaje niczego we właściwym czasie.',
  'Pomyśl o swoim sezonie w dłuższych łukach: kiedy są twoje najważniejsze turnieje i czy dotąd pracujesz równomiernie, czy świadomie planujesz fazy budowy i regeneracji? Obserwuj, czy na ważne terminy docierasz świeży czy zmęczony. Jeśli chcesz sterować formą bardziej celowo na przestrzeni sezonu, następnym krokiem jest zaplanować to z trenerem lub specjalistą nauk o treningu — ten moduł nie zastępuje tego towarzyszenia, lecz je zaleca.',
  'Siła reaktywna — szybki kontakt z podłożem',
  'To, co wyróżnia eksperta atletycznie, to często szybkość kontaktu z podłożem, nie surowa siła. Siła reaktywna to zdolność, by dotknąć podłoża tylko krótko i natychmiast znów się odbić — sprężyście zamiast ciężko. Tkwi za każdą szybką zmianą kierunku i każdym eksplozywnym zrywem.\n\nZa tym stoi prosta zasada: twoje ścięgna działają jak sprężyny. Gdy lądujesz, napinają się i magazynują energię; odbijasz się natychmiast, oddają tę energię i wzmacniają twój ruch. Im krótszy kontakt z podłożem, tym więcej tej zmagazynowanej energii wykorzystujesz. Długi, ciężki kontakt pozwala jej ujść na darmo.\n\nDlatego przy sile reaktywnej chodzi o jakość, nie o ilość. Kontakt ma się czuć lekko i sprężyście, jak piłka, która odbija się od podłoża. Lądowanie pozostaje przy tym zawsze miękkie i kontrolowane — sprężystość powstaje z elastyczności, nie z twardości.\n\nJasna granica: strukturalny trening siły reaktywnej ze skokami należy do wykwalifikowanych rąk. Budowa, obciążenie i dobór ćwiczeń to sprawa dla trenera lub nauk o treningu — właśnie dlatego, że obciążenie skokowe bez dobrej budowy obciąża stawy. Tu chodzi wyłącznie o czucie krótkiego, sprężystego kontaktu w ruchach, które i tak grasz.\n\nWyobraź sobie, że podłoże jest gorące i chcesz stać na nim jak najkrócej. Właśnie to krótkie, lekkie odbicie to siła reaktywna.',
  {
    titel: 'Krótko i sprężyście',
    ziel: 'Rozwinąć czucie krótkiego, elastycznego kontaktu z podłożem w znanych ruchach — jakość, nie objętość.',
    schritte: [
      'Graj swoją zwykłą pracę nóg i zwracaj świadomie uwagę na długość kontaktu z podłożem: jak krótko potrafisz go utrzymać?',
      'Przy małych podskokach wyrównawczych i zmianach kierunku: wyobraź sobie podłoże jako gorące, które natychmiast znów opuszczasz.',
      'Zadbaj o to, by lądowanie pozostawało przy tym zawsze miękkie i ciche — sprężyste, nie twarde.',
      'Wsłuchaj się w dźwięk: cichy kontakt jest przeważnie elastyczny.',
      'Zakończ ćwiczenie, gdy tylko ruch robi się ciężki lub lądowanie twarde — jakość przed kontynuacją.',
    ],
    selbstkontrolle: 'Czy twój kontakt z podłożem czuje się lekko i sprężyście, czy ciężko i długo? Czy lądowanie pozostaje miękkie i ciche? Jeśli sprężystość słabnie lub lądowanie robi się twarde, ćwiczenie na dziś skończone. Do strukturalnego treningu skoków zwróć się do wykwalifikowanego prowadzenia.',
    abschluss: 'Siła reaktywna to lekki, krótki kontakt z podłożem, który czyni twój ruch bardziej efektywnym. Rośnie przez jakość kontaktu — zaplanowana budowa należy do fachowych rąk.',
  },
  'Ekonomia ruchu — efektywnie zamiast nerwowo',
  'Doświadczeni gracze wydają się często bez wysiłku, podczas gdy mniej wyćwiczeni nerwowo biegają za tymi samymi piłkami. Różnicą jest ekonomia ruchu: dotrzeć tam, dokąd musisz, jak najmniejszym nakładem. Kto gra ekonomicznie, pozostaje dłużej świeży i pod koniec meczu wciąż jest obecny.\n\nEkonomia zaczyna się od pomijania zbędnego ruchu. Każdy niepotrzebny krok, każdy zbyt szeroki zamach, każda nerwowa korekta kosztuje siły. Ekspert porusza się jasnymi, bezpośrednimi drogami do piłki i z powrotem, bez wiercenia się, bez okrężnych dróg. Spokój w ruchu to znak efektywności, nie powolności.\n\nDrugą częścią jest dobra pozycja wyjściowa. Kto po każdym uderzeniu sprawnie wraca do centralnej, wyważonej pozycji, ma krótsze drogi do następnej piłki. Ekonomia powstaje także dzięki temu, że w ogóle nie musisz daleko biec, bo mądrze stoisz.\n\nI wiąże się ściśle z siłą reaktywną: kto wykorzystuje sprężystą energię swoich ścięgien, porusza się mniejszym nakładem mięśniowym. Efektywny ruch czuje się lekko, bo wykorzystuje darmową energię elastyczną, zamiast czerpać wszystko z czystej siły mięśni.\n\nDoświadczony biegacz sunie po trasie, początkujący tupie. Oboje docierają, ale jeden ma na końcu jeszcze rezerwy, drugi jest pusty. W crossmintonie ta rezerwa często rozstrzyga trzeciego seta.',
  'Obserwuj się na następnym treningu: gdzie marnujesz ruch — przez niepotrzebne kroki, nerwowe wiercenie, zbyt długie drogi, bo nie wracasz na pozycję? Postanów sobie jeden jedyny punkt: na przykład po każdym uderzeniu spokojnie i sprawnie wracać do pozycji centralnej. Zwróć uwagę, czy pod koniec meczu czujesz się świeższy, gdy twój ruch robi się spokojniejszy i bardziej bezpośredni.',
  'Szybkość antycypacyjna — wczesny start',
  'Najszybsi gracze nie zawsze są tymi, którzy najszybciej biegają — to często ci, którzy najwcześniej startują. Szybkość antycypacyjna łączy twoją fizyczną szybkość z wczesnym czytaniem: jesteś prędzej przy piłce, bo prędzej ruszasz.\n\nKlucz tkwi w tym, że dobrzy gracze reagują już na oznaki przed piłką, zamiast czekać na samą piłkę. Postawa ciała przeciwnika, jego zamach, ustawienie jego rakiety często już zdradzają, dokąd idzie piłka — na długo zanim ją trafi. Kto czyta te znaki, startuje o ułamek sekundy wcześniej. Na przestrzeni całego meczu ta przewaga sumuje się do ogromnej różnicy.\n\nTo wczesne czytanie to zdolność do wytrenowania, nie wrodzony dar. Im częściej świadomie zwracasz uwagę na przygotowanie przeciwnika zamiast tylko na piłkę, tym lepsza staje się twoja przepowiednia. Z czasem dzieje się to samo — „przeczuwasz", dokąd przyjdzie piłka, bo twój wzrok nauczył się właściwych znaków.\n\nAtletycznie opłaca się to podwójnie: wczesny start czyni cię efektywnie szybszym, bez tego, byś musiał szybciej biec. I łączy się z techniką wczesnego przyjmowania — kto wcześnie startuje, może wcześniej trafić piłkę i ukraść przeciwnikowi czas.\n\nAntycypacja jest jak czytanie chmur przed deszczem. Kto czyta niebo, jest w suchym, zanim spadnie pierwsza kropla. Kto czeka na deszcz, moknie — nawet jeśli szybko biega.',
  'Postanów sobie w następnym meczu świadomie obserwować także przygotowanie przeciwnika, nie tylko piłkę: jego postawę ciała, jego zamach, ustawienie rakiety. Czy zdradzają ci wcześnie, dokąd idzie piłka? Zwróć uwagę, czy ruszasz wcześniej, gdy czytasz te znaki — i czy dzięki temu jesteś spokojniej i w porę przy piłce, nie biegnąc szybciej.',
  'Zdrowie i wytrzymałość na długo',
  'Największa forma atletyczna nic nie da, jeśli ciało nie udźwignie jej przez lata. Długoterminowa wytrzymałość — pozostać zdrowym i sprawnym przez sezon i dłużej — to cicha podstawa każdej kariery eksperckiej. Tu myśl o zdrowiu obowiązuje szczególnie surowo.\n\nPierwsza zasada to słuchać ciała. Doświadczeni sportowcy znają różnicę między normalnym zmęczeniem treningowym a sygnałem ostrzegawczym. Utrzymujące się wyczerpanie, ruchy, które robią się cięższe, słabnięcie sprężystej szybkości — to znaki, które wymagają uwagi, nie twardości wobec siebie.\n\nDruga zasada to, że jakość ruchu chroni. Czyste, ekonomiczne poruszanie obciąża stawy i ścięgna mniej niż nerwowe, niekontrolowane. Wiele z tego, czego nauczyłeś się w tej aplikacji o technice i ruchu, służy także twojemu zdrowiu.\n\nA tu jasna, ważna granica: wszystko, co ma związek z bólem, kontuzją, utrzymującym się przeciążeniem lub konkretną budową obciążenia, należy do fachowych rąk — medycyny sportowej, fizjoterapii, wykwalifikowanego towarzyszenia treningowego. Ta aplikacja nie daje ci wskazówek leczniczych, żadnych zaleceń obciążenia ani diagnoz. Zachęca cię, byś przy takich pytaniach zwrócił się do właściwego specjalisty. To znak doświadczenia, nie słabości.\n\nInstrument, który się pielęgnuje, brzmi przez całe życie; taki, który się przeciąża, pęka. Twoje ciało to twój instrument — kto obchodzi się z nim uważnie i w razie wątpliwości pyta fachowca, gra najdłużej.',
  'Pomyśl szczerze o swojej wytrzymałości: słuchasz sygnałów ostrzegawczych swojego ciała, czy regularnie je przegrywasz? Znasz różnicę między normalnym zmęczeniem a znakiem, który wymaga uwagi? Postanów sobie przy utrzymującym się wyczerpaniu, bólu lub przeciążeniu zwrócić się do właściwego specjalisty, zamiast trenować twardziej — medycyny sportowej, fizjoterapii lub wykwalifikowanego towarzyszenia treningowego. Długoterminowe zdrowie to podstawa, na której stoi wszystko inne.',
];

const DOPPEL = [
  'Para jako system',
  'Na poziomie eksperckim dwoje dobrych pojedynczych graczy to jeszcze daleko nie dobry debel. Różnicą jest system: para, która myśli jako zgrana jedność, uzupełnia się i z góry wie, co robi. Dwoje graczy, którzy tylko obok siebie grają swój najlepszy singiel, przegrywa z prawdziwym zespołem.\n\nRdzeniem jest połączenie sił obojga. Może jeden ma mocniejszy atak, drugi lepszy ogląd z przodu; jeden jest spokojnym biegunem, drugi motorem. Dobry system dzieli role tak, że siły się uzupełniają, a słabości są nawzajem kryte. Gracie razem z powodu waszych różnic, nie mimo nich.\n\nNależą do tego z góry ustalone wzorce. Doświadczone pary mają standardowe przebiegi, które przywołują bez słów: określone warianty serwisu ze stałym ruchem następczym, stałe reakcje na typowe sytuacje. Te wzorce zdejmują w szybkiej grze ciężar decyzji i sprawiają, że myślicie tymi samymi torami.\n\nNa końcu system porusza się jako jedność. Obraz niewidzialnej liny obowiązuje tu w pełni: każdy ruch jednego wyzwala odpowiednią odpowiedź drugiego, aż para działa na oba pola jak jeden organizm.\n\nDebel na najwyższym poziomie jest jak zgrany duet muzyczny. Oboje znają utwór, każdy ma swój głos, a we współgraniu powstaje coś, czego nikt sam nie stworzy.',
  'Pomyśl o swoim deblu jako o systemie: jakie są siły twoje i twojego partnera i czy się uzupełniają, czy gracie dwa single obok siebie? Macie z góry ustalone wzorce, które przywołujecie bez słów? Postanów sobie ustalić z partnerem jeden, dwa stałe przebiegi i podzielić role tak, by wasze siły się połączyły.',
  'Czytanie pary przeciwników',
  'Para przeciwników ma słabe punkty, których pojedynczy przeciwnik nie ma — a ekspert je znajduje i wykorzystuje. Kto czyta duet przeciwników, atakuje dokładnie tam, gdzie parze szkodzi to najbardziej, nie gdziekolwiek.\n\nPierwszym słabym punktem jest słabszy z dwojga. Niemal zawsze jeden jest bardziej wrażliwy — słabszy w obronie, wolniejszy, bardziej nerwowy. Mądra para rozpoznaje to wcześnie i kieruje większość piłek celowo na tego gracza, aż pod ciągłym obciążeniem popełni błędy albo wypadnie z pozycji.\n\nDrugim, często jeszcze skuteczniejszym słabym punktem jest luka między obojgiem — środek. Piłka, która pada dokładnie między dwoje przeciwników, tworzy strefę niepewności: oboje krótko wahają się, bo żaden nie jest pewien, czy to jego piłka. To wahanie testuje ich uzgodnienie i kosztuje ich decydujący moment. Przeciw parze w obronie bok w bok piłka w środek jest szczególnie mocna.\n\nOboje razem daje plan: obciąż słabszego przeciwnika i szukaj szwu między obojgiem. Tak grasz przeciw ich zgraniu, nie przeciw dwóm pojedynczym graczom.\n\nPara przeciwników jest jak mur z dwóch kamieni. Uderzasz w fugę pomiędzy, nie w twardy kamień — tam mur trzyma najsłabiej.',
  'Pomyśl o mocnej parze przeciwników: który z dwojga był bardziej wrażliwy i czy obciążałeś go celowo? I czy szukałeś luki między obojgiem, czy grałeś tylko na samych graczy? Postanów sobie w następnym deblu wcześnie określić słabszego przeciwnika i świadomie zagrywać w środek między obojgiem, zwłaszcza gdy bronią bok w bok.',
  'Ustawić partnera w pozycji',
  'W deblu na najwyższym poziomie często grasz po to, by ustawić partnera w idealnej pozycji ataku, nie dla własnego zdobycia punktu. To bezinteresowne budowanie to znak rozpoznawczy dojrzałych deblistów: najlepsze uderzenie to czasem to, które przygotowuje punkt partnerowi.\n\nMyślą przewodnią jest wymusić słabą piłkę przeciwnika, którą partner może wykorzystać. Głęboki, precyzyjny serwis albo płaska, dociskowa piłka zmusza przeciwnika do defensywy i wysokiego, krótkiego returnu — dokładnie tej podania, którą twój tylny partner zamienia w atak.\n\nPrzy tym działa podział ról gracza atakującego i tylnego. Gracz tylny buduje dociskowymi piłkami i kończy; przedni gracz atakujący czyha z przodu, by natychmiast przechwycić słaby return. Po własnym serwisie sam wysuwasz się do przodu, by wcześnie zdejmować krótkie odbicia i osłaniać partnerowi plecy.\n\nTo wymaga myślenia o punkcie dwa ruchy naprzód: „jak wymuszę podanie, które partner zamieni", nie „jak wygram tę piłkę". Kto tak gra, robi z dwojga graczy maszynę atakującą.\n\nJesteś przygotowującym, który dośrodkowuje, by partner musiał już tylko zamienić piłkę. Bramkę strzela on — ale bez twojego podania nie byłoby jej.',
  {
    titel: 'Zagrać podanie',
    ziel: 'Zakładać piłki tak, by partner wchodził w pozycję ataku.',
    schritte: [
      'Grajcie we czworo i dajcie tylnemu graczowi zadanie, by dociskowymi, głębokimi piłkami wymusić wysoki, krótki return.',
      'Przedni gracz atakujący czyha z przodu i natychmiast przechwytuje słaby return.',
      'Ćwiczcie serwis jako podanie: głęboko i precyzyjnie, tak by przeciwnik mógł odegrać tylko słabo.',
      'Po własnym serwisie serwujący wysuwa się do przodu, by wcześnie zdejmować krótkie odbicia.',
      'Myślcie o każdej wymianie jako o przygotowaniu: która piłka ustawia partnera w pozycji?',
    ],
    selbstkontrolle: 'Czy grasz, by samemu zdobyć punkt, czy by ustawić partnera w pozycji? Czy twoja budowa wymusza słaby return, który partner może wykorzystać? Czy myślisz o punkcie dwa ruchy naprzód? Dobry debel to często zagrać podanie, zamiast samemu kończyć.',
    abschluss: 'Ustawienie partnera w pozycji robi z dwojga graczy system atakujący. Kto buduje bezinteresownie, zdobywa jako para więcej punktów niż każdy dla siebie.',
  },
  'Płynne przełączanie',
  'Debel zmienia się nieustannie między dwiema formacjami: atakiem przód-tył i obroną bok w bok. Na poziomie eksperckim ta zmiana dzieje się płynnie — szybko, gładko i niemal bez słów. Kto się zatnie lub zawaha, otwiera przeciwnikowi lukę właśnie w tym momencie.\n\nWyzwalacz jest prosty: kto bije speedera w dół, atakuje; kto musi go podbić wysoko, broni. Gracie mocną piłkę w dół, jeden wysuwa się do przodu i stoicie przód-tył. Musicie podbić piłkę wysoko, natychmiast obracacie się w obronę bok w bok, by pokryć szerokość. To czytanie sytuacji musi dziać się w ułamkach sekundy.\n\nPłynność powstaje przez zgraną rotację. Wysuwa się jeden do przodu, drugi automatycznie wypełnia tylną przestrzeń; obraca się jeden w bok, drugi kryje drugą połowę. Na najwyższym poziomie ledwie potrzebuje to jeszcze słów — ruch jednego jest sygnałem dla drugiego. Niewidzialna lina ciągnie w czasie rzeczywistym.\n\nBy to niosło pod presją, rotacja musi być głęboko wyćwiczona. W meczu nie ma czasu na namysł; zmiana biegnie automatycznie, bo zagraliście ją razem setki razy.\n\nDebel na najwyższym poziomie zmienia formację jak drzwi obrotowe — oba skrzydła poruszają się jednocześnie, jedno zwalnia przestrzeń, którą zajmuje drugie, bez zacięcia.',
  {
    titel: 'Obracać atak i obronę',
    ziel: 'Szybko i płynnie zmieniać między formacją ataku a obrony.',
    schritte: [
      'Grajcie we czworo i uświadomcie sobie regułę: piłka w dół = atak (przód-tył), piłka w górę = obrona (bok w bok).',
      'Ćwiczcie zmianę z obrony w atak: jeden wysuwa się do przodu, drugi wypełnia tylną przestrzeń.',
      'Ćwiczcie zmianę z ataku w obronę: przedni obraca się w bok, tylny kryje drugą połowę.',
      'Redukujcie stopniowo słowa, aż ruch jednego będzie sygnałem dla drugiego.',
      'Zwiększajcie tempo, aż zmiana udaje się płynnie także pod presją.',
    ],
    selbstkontrolle: 'Czy wasza zmiana biegnie płynnie, czy zacinacie się i zostawiacie luki? Czy partner automatycznie wypełnia przestrzeń, którą opuszczasz? Czy potrzebujecie jeszcze wielu słów, czy jeden czyta ruch drugiego? Płynne przełączanie powstaje tylko przez dużo wspólnego ćwiczenia.',
    abschluss: 'Płynne przełączanie trzyma was zawsze we właściwej formacji. Kto rotuje płynnie i bez słów, nie zostawia przeciwnikowi luki w zmianie.',
  },
  'Ślepe porozumienie',
  'Najwyższy stopień gry deblowej ledwie potrzebuje jeszcze słów. Zgrane pary rozwijają ślepe porozumienie: przeczuwają, co zrobi drugi, zanim to zrobi, i kryją się nawzajem, nie patrząc. To porozumienie to ciche zwieńczenie wspólnej gry.\n\nJego rdzeniem jest antycypacja partnera. Czytasz także ruch swojego partnera, nie tylko przeciwnika i speedera: dokąd startuje, którą piłkę bierze, którą przestrzeń opuszcza. Z tego czytania automatycznie wypełniasz lukę, którą otwiera — jeszcze zanim mogłoby paść słowo.\n\nFundamentem tego porozumienia jest zaufanie. Polegasz na tym, że partner weźmie swoją piłkę, i nie musisz kontrolująco patrzeć. To zaufanie uwalnia cię, byś skupił się na własnym zadaniu. Para, która sobie ufa, gra spokojniej i szybciej niż taka, która stale się asekuruje.\n\nŚlepego porozumienia nie da się wymusić — rośnie przez wspólne granie z czasem. Im częściej gracie razem, tym bardziej uwewnętrzniacie wzorce i reakcje drugiego, aż zgranie dzieje się bez słów. To plon cierpliwej wspólnej pracy.\n\nZgrany debel jest jak dwie ręce tej samej osoby. Nie muszą się umawiać — jedna wie, co robi druga, i splatają się jak coś oczywistego.',
  'Pomyśl o zgraniu ze swoim stałym partnerem: przeczuwasz jego ruchy, czy musisz stale patrzeć i się asekurować? Ufasz, że weźmie swoją piłkę? Ślepe porozumienie rośnie tylko przez wspólne granie — postanów sobie grać regularnie ze stałym partnerem i świadomie zwracać uwagę na czytanie jego ruchu i ufanie mu, zamiast kontrolować.',
];

const r1 = insertPl('data/bausteine.experte-mentales.json', MENTALES);
const r2 = insertPl('data/bausteine.experte-athletik_kondition.json', ATHLETIK);
const r3 = insertPl('data/bausteine.doppel-experte.json', DOPPEL);
console.log(`Ring 9 pl: mentales ${r1.knoten} + athletik ${r2.knoten} + doppel ${r3.knoten} = ${r1.knoten + r2.knoten + r3.knoten} Knoten.`);
