// Ring 11 (pl): Outdoor-Thema (18) + Spielmodi (12) = 30 Knoten, delta-frei (Umgebungs-Achse).
import { insertPl } from './pl-core.mjs';

const OUTDOOR = [
  'Gra na zewnątrz',
  'Crossminton to gra na dworze — jako taka został wymyślony. Nie zna siatki; między dwoma polami leży strefa neutralna, i właśnie to czyni go grywalnym wszędzie: na plaży, w parku, na łące, na boisku. Kto przywykł do gry w hali, na zewnątrz trafia na nowe warunki, które zmieniają grę.\n\nNajważniejszą różnicą jest wiatr. Bez siatki i z otwartym torem lotu wiatr działa wprost na speedera. Do tego speeder jest stworzony: cięższy, węższy i krótszy niż lotka, leci stabilnie i jest dobrze grywalny do mniej więcej siły wiatru 4. Przy silniejszym wietrze jest specjalnie do tego opracowany, cięższy speeder (Cross Speeder) zamiast szybszego Match Speedera — na turnieju zmodyfikowany speeder może jednak zostać użyty tylko za zgodą organizatora i sędziego głównego.\n\nTakże podłoże się zmienia: piasek, trawa, mączka czy sztuczna trawa wymagają za każdym razem innej pracy nóg niż twarda podłoga hali. A słońce, wilgoć i upał dochodzą jako warunki, których w hali nie ma. Nie na ostatnim miejscu reguła zmiany stron ma na zewnątrz namacalny sens: wyrównuje wiatr i światło między obiema stronami.\n\nKolejne moduły omawiają te warunki po kolei. Myśl przewodnia jest zawsze ta sama: na zewnątrz grasz z warunkami, nie przeciw nim.\n\nŻeglarz nie przeklina wiatru, ustawia żagle. Na zewnątrz otoczenie jest twoim współgraczem — kto je czyta, ma przewagę.',
  'Pomyśl o ostatnim razie, gdy grałeś na zewnątrz: który warunek najbardziej zmienił twoją grę — wiatr, podłoże, słońce czy upał? I czy próbowałeś z nim walczyć, czy się na niego nastawić? Postanów sobie następnym razem na zewnątrz najpierw świadomie odczytać warunki, zanim zaczniesz grać — tak jak czytasz przeciwnika.',
  'Czytanie i wykorzystanie wiatru',
  'Wiatr to właściwe, znakowe wyzwanie gry plenerowej. Ponieważ żadna siatka nie ogranicza toru lotu, a speeder leci po otwartej trasie, wiatr wyczuwalnie ingeruje — a kto go czyta, czyni go sprzymierzeńcem.\n\nNajpierw czytasz kierunek. Grasz pod wiatr, hamuje speedera i każe mu opaść krócej; uderzasz wtedy mocniej i płaściej, by utrzymać długość. Grasz z wiatrem, niesie speedera dalej; zdejmujesz tempo i grasz bardziej kontrolowanie, żeby nie zniosło go na aut. Wiatr boczny znosi speedera w bok — celujesz świadomie przeciw znoszeniu, kawałek w wiatr.\n\nCiężki, stabilny przy wietrze speeder ci w tym pomaga: leci niezawodnie do mniej więcej siły wiatru 4. Przy silniejszym wietrze cięższy Cross Speeder to lepszy wybór. Ale i najlepszy speeder nie znosi znoszenia — twoje dostosowanie pozostaje decydujące.\n\nTaktycznie wiatr staje się wręcz bronią. Z wiatrem w plecy możesz budować presję długością; pod wiatr wysoka, długa piłka jest ryzykowna, a płaska, mocna pewniejsza. A reguła zmiany stron sprawia, że obie strony niosą korzyść i niekorzyść wiatru po równo.\n\nWiatr jest jak nurt przy pływaniu. Kto naciera przeciw niemu, traci siły; kto go czyta i wykorzystuje, posuwa się naprzód połowicznym nakładem.',
  {
    titel: 'Grać z wiatrem',
    ziel: 'Świadomie dostosować moc, długość i punkt celu do kierunku wiatru.',
    schritte: [
      'W wietrzny dzień ustaw się najpierw tak, byś grał pod wiatr: uderzaj mocniej i płaściej, by utrzymać długość.',
      'Zmień kierunek i graj z wiatrem: zdejmij tempo i graj bardziej kontrolowanie, żeby speedera nie zniosło na aut.',
      'Przy wietrze bocznym: celuj świadomie kawałek w wiatr, przeciw znoszeniu.',
      'Obserwuj, jak daleko wiatr za każdym razem znosi speedera, i koryguj z uderzenia na uderzenie.',
      'Gdy wiatr robi się zbyt silny dla Match Speedera, zmień na cięższego Cross Speedera.',
    ],
    selbstkontrolle: 'Czy dostosowujesz moc i długość do kierunku wiatru, czy grasz pod wiatr i z wiatrem tak samo? Czy przy wietrze bocznym celujesz przeciw znoszeniu? Wiatr jest przewidywalny, gdy go czytasz — wtedy grasz z nim zamiast przeciw niemu.',
    abschluss: 'Czytanie i wykorzystanie wiatru to sedno gry plenerowej. Kto uwzględnia kierunek i siłę, nie traci już na zewnątrz punktów na rzecz wiatru — lecz zdobywa je dzięki niemu.',
  },
  'Słońce i oślepienie',
  'Słońce jest na zewnątrz cichym przeciwnikiem. Zwłaszcza przy wysokich piłkach może cię oślepić i kosztować decydujący ułamek sekundy, w którym tracisz speedera z oczu. Kto wlicza słońce, nie traci tych punktów.\n\nRadzenie sobie zaczyna się od świadomości: wiesz, gdzie stoi słońce, i liczysz się z tym, że wysokie piłki w jego stronę są trudne do zobaczenia. Zamiast patrzeć wprost w słońce, obracasz lekko głowę i bierzesz speedera kątem oka albo przechwytujesz go wcześniej, zanim wzniesie się w jaskrawy obszar. Wczesne czytanie toru lotu pomaga ci tu podwójnie.\n\nDaszek przy czapce albo okulary przeciwsłoneczne mogą zmniejszyć oślepienie. A taktycznie opłaca się zostawić słońce przeciwnikowi: wysoka piłka w jego stronę oślepienia jest trudniejsza do odebrania.\n\nTakże tu działa reguła zmiany stron: sprawia, że nie jedna strona stoi przez całą grę ze słońcem w twarzy. Niekorzyść wędruje uczciwie między obojgiem.\n\nSłońce jest jak reflektor, który oślepia cię w niewłaściwym momencie. Kto wie, gdzie stoi, w porę obraca głowę — i nie patrzy w nie.',
  'Pomyśl o grze w słońcu: traciłeś wysokie piłki, bo światło cię oślepiało? Postanów sobie następnym razem świadomie wiedzieć, gdzie stoi słońce, wysokie piłki wcześnie przechwytywać albo lekko obracać głowę, zamiast patrzeć wprost — i wykorzystywać wysoką piłkę w stronę oślepienia przeciwnika jako środek taktyczny.',
  'Wilgoć i stabilna postawa',
  'Wilgoć zmienia na zewnątrz przede wszystkim jedno: przyczepność. Sam speeder jest wodoodporny i leci dalej, ale podłoże robi się śliskie — i tym samym bezpieczeństwo wysuwa się na pierwszy plan. Przy wilgoci obowiązuje: kontrolowany ruch przed maksymalnym tempem.\n\nNajważniejszym punktem jest pewna postawa. Na mokrej trawie, wilgotnej nawierzchni czy gładkim podłożu trudniej hamować i zmieniać kierunek; zbyt pośpieszny zryw może prowadzić do poślizgu. Dlatego świadomie cofasz nieco tempo, robisz krótsze, kontrolowane kroki i unikasz gwałtownych zmian kierunku, przy których stopa mogłaby uciec.\n\nOdpowiednie obuwie z dobrym bieżnikiem pomaga zachować przyczepność. I sprawdzasz podłoże przed grą: gdzie jest szczególnie ślisko, gdzie zbiera się woda? Te miejsca świadomie omijasz.\n\nChodzi tu o nienaruszalność, nie o formę. Gdy podłoże robi się zbyt śliskie, mądrzej jest przerwać grę, niż ryzykować kontuzję. Przy wszystkim, co wykracza poza ostrożną grę — na przykład bólu po poślizgu —, wykwalifikowana porada jest właściwym adresem, nie dalsza gra.\n\nNa mokrym podłożu poruszasz się jak po świeżo umytej podłodze — krótkimi, pewnymi krokami, nie pełnym biegiem. Kto to weźmie sobie do serca, zostaje w grze i cały.',
  'Pomyśl o grze na mokrym podłożu: uważasz na postawę, czy grasz pełnym tempem dalej, jakby podłoże było suche? Postanów sobie przy wilgoci robić krótsze, kontrolowane kroki, unikać gwałtownych zmian kierunku i wcześniej sprawdzać podłoże pod kątem śliskich miejsc. I uświadom sobie: gdy robi się zbyt ślisko, przerwać jest mądrzej niż upaść — przy bólu po poślizgu ocena należy do fachowych rąk.',
  'Upał',
  'W upale gra także ciało. Mecz w pełnym słońcu wymaga więcej niż ta sama gra w chłodnej hali — i tu uważność na siebie samego stoi ponad wszystkim. Ten moduł wyostrza spojrzenie na znaki, zamiast dawać ci zalecenia.\n\nPierwszą zasadą jest traktować sygnały własnego ciała poważnie. Silne wyczerpanie, zawroty głowy, mdłości albo słabnięcie koncentracji mogą być w upale znakami przegrzania — wymagają przerwy, nie zaciskania zębów. Przebijanie się przez upał nie jest znakiem siły.\n\nDrugą zasadą jest mądrze wykorzystywać warunki. Przerwy między setami spędzasz w miarę możliwości w cieniu. Rozkładasz siły na mecz, zamiast grać każdą wymianę na maksa. I planujesz, jeśli to możliwe, najgorętsze godziny dnia nie na najintensywniejszą grę.\n\nTu obowiązuje jasna granica ramy zdrowotnej: ta aplikacja nie daje ci zaleceń co do picia, odżywiania ani obciążenia. Przy wszystkim, co wykracza poza normalną grę — utrzymującym się złym samopoczuciu, oznakach udaru cieplnego —, porada lekarska lub fachowa jest właściwym adresem. Uważać na siebie to doświadczenie, nie słabość.\n\nTwoje ciało jest w upale jak silnik, który się przegrzewa. Kto ma wskaźnik temperatury na oku i w porę chłodzi, dojeżdża — kto go ignoruje, zostaje na trasie.',
  'Pomyśl o grze w upale: traktujesz znaki ostrzegawcze jak zawroty głowy, mdłości czy silne wyczerpanie poważnie, czy przegrywasz je? Postanów sobie w upale spędzać przerwy w cieniu, rozkładać siły i przy oznakach przegrzania robić przerwę zamiast grać dalej. I uświadom sobie: przy utrzymującym się złym samopoczuciu porada lekarska lub fachowa jest właściwym adresem.',
  'Różne podłoża',
  'Twarda podłoga hali to tylko jedna z wielu. Na zewnątrz grasz na piasku, trawie, mączce czy sztucznej trawie — a każde podłoże wymaga innej pracy nóg. Kto czyta podłoże i dostosowuje ruch, stoi pewnie i jest szybciej przy piłce.\n\nNa piasku, na przykład na plaży, podłoże jest miękkie i nierówne. Hamuje każdy krok, kosztuje siły i utrudnia szybkie zrywy. Grasz tu szerszą, stabilną postawą, robisz krótsze drogi i liczysz się z wolniejszym odbiciem. Na trawie może być, zależnie od wilgoci, ślisko lub nierówno — przyczepność się zmienia, i sprawdzasz podłoże wcześniej. Mączka jest śliska i pozwala na kontrolowany poślizg, ale wymaga pewnej postawy. Sztuczna trawa daje przeważnie dobry grip, podobny do hali.\n\nDochodzi praktyczny punkt: oznaczenie pola. Na miękkim podłożu jak piasek czy trawa boisko zabezpiecza się śledziami, na twardym taśmą klejącą lub kredą. Czysto przymocowane pole zapobiega pułapkom do potknięcia.\n\nWspólnym mianownikiem jest świadome odczytanie podłoża przed grą i nastawienie na nie pracy nóg, zamiast po prostu przenosić halowy nawyk.\n\nDobry wędrowiec dobiera krok do podłoża — na skale inaczej niż na rumowisku, na piasku inaczej niż na leśnej ściółce. Tak samo dostosowujesz pracę nóg do podłoża, na którym grasz.',
  {
    titel: 'Czytać podłoże',
    ziel: 'Świadomie dostosować pracę nóg do danego podłoża.',
    schritte: [
      'Zagraj lub porusz się na próbę na nieznanym podłożu (np. piasek lub trawa) i poczuj, jak zmieniają się odbicie i przyczepność.',
      'Na miękkim, wolnym podłożu: szersza, stabilna postawa, krótsze drogi, liczenie się z wolniejszym odbiciem.',
      'Na gładkim lub śliskim podłożu: kontrolowane kroki, żadnych gwałtownych zmian, sprawdzenie podłoża wcześniej pod kątem przyczepności.',
      'Zadbaj o dostosowanie ruchu, zamiast po prostu przenosić halowy nawyk.',
      'Przy własnym rozstawianiu zabezpiecz pole odpowiednio: śledzie na miękkim, taśma klejąca lub kreda na twardym podłożu.',
    ],
    selbstkontrolle: 'Czy dostosowujesz pracę nóg do podłoża, czy poruszasz się wszędzie jak w hali? Czy sprawdzasz przyczepność, zanim zagrasz pełnym tempem? Każde podłoże ma swój własny krok — kto je czyta, stoi pewnie i szybciej dociera do speedera.',
    abschluss: 'Różne podłoża wymagają różnej pracy nóg. Kto świadomie czyta podłoże i się nastawia, gra na zewnątrz pewnie na każdym gruncie.',
  },
];

const SPIELMODI = [
  'Przegląd odmian gry',
  'Crossminton pozostaje tą samą grą, gdziekolwiek go grasz. Wokół gry podstawowej wykształciło się jednak kilka nazwanych odmian, które mają przede wszystkim jedno wspólne: zmieniają otoczenie, podczas gdy przepisy pozostają te same.\n\nTrzy z nich są zdefiniowane przez otoczenie. Snowminton gra się na śniegu, z zimnem jako towarzyszem. Beachminton toczy się na piasku, przeważnie w upale i słońcu. A Blackminton odbywa się w ciemności, ze świecącym speederem jako jedynym niezawodnym sygnałem. We wszystkich trzech liczysz, serwujesz i zmieniasz strony dokładnie jak zwykle — zmienia się podłoże pod stopami, temperatura albo światło.\n\nOd tego trzeba odróżnić dwie inne kategorie, które są tu tylko sklasyfikowane. Gra pojedyncza i podwójna to formy współzawodnictwa: zmieniają strukturę gry (jeden lub dwoje na stronę), nie otoczenie, i mają w podręczniku własne miejsce. I są swobodne, towarzyskie sposoby gry, w których chodzi tylko o to, by wspólnie jak najdłużej utrzymać speedera w grze — bez liczenia, bez rywalizacji.\n\nTen blok omawia po kolei trzy odmiany zależne od otoczenia. Nić przewodnia z rozdziału plenerowego obowiązuje dalej: grasz z warunkami, nie przeciw nim — tu tylko pod śniegiem, na piasku i w ciemności.\n\nDobra piosenka pozostaje ta sama, czy śpiewana przy ognisku, czy w hali. Tylko przestrzeń wokół niej brzmi inaczej — i właśnie ją uczysz się tu czytać.',
  'Która z trzech odmian nęci cię najbardziej — śnieg, piasek czy ciemność? Zastanów się, co w niej wobec gry halowej naprawdę się zmienia: podłoże, temperatura czy światło. I uświadom sobie, że przepisy we wszystkich trzech pozostają te same — sztuka polega na nastawieniu się na zmienione otoczenie, tak jak ćwiczyłeś to już na zewnątrz przy wietrze i słońcu.',
  'Snowminton — gra na śniegu',
  'Snowminton to crossminton na śniegu — według przepisów ta sama gra, tylko powierzchnia pola leży w bieli. Liczy się, serwuje i zmienia strony jak zawsze; speeder leci jak zwykle. Zmieniają się dwie rzeczy: podłoże i zimno.\n\nŚnieg czyni podłoże miękkim i śliskim zarazem. Jak już na mokrym gruncie obowiązuje: kontrolowany ruch przed maksymalnym tempem. Robisz krótsze, pewne kroki, unikasz gwałtownych zmian kierunku, przy których stopa ucieka, i pracujesz bardziej na szerokiej, stabilnej postawie niż na eksplozywnych zrywach. Udeptany śnieg niesie inaczej niż świeży — podłoże czytasz przed grą.\n\nZimno jest drugim czynnikiem, i tu uważność na siebie samego stoi ponad wszystkim. Zimne mięśnie są bardziej podatne na kontuzje, dlatego rozgrzewka przy mrozie nabiera szczególnej wagi — porównanie z zimnym silnikiem robi się na śniegu dosłowne. Utrzymujesz się między wymianami w cieple i ubierasz się na warstwy, które w razie potrzeby możesz rozpiąć. ICO wymienia dokładnie to jako jedyną różnicę w sprzęcie: inne buty i odzież, odpowiednie na zimno i śnieg.\n\nPrzy obuwiu liczy się grip na śliskim, zimnym gruncie — gładka podeszwa halowa jest tu nie na miejscu. Przy odzieży pomaga zasada warstw z rozdziału o sprzęcie: warstwa, która odprowadza wilgoć od ciała, na niej warstwy grzejące i wiatroszczelna.\n\nJasna granica pozostaje: ta aplikacja nie daje ci zaleceń co do wartości ochrony przed zimnem ani obciążenia. Przy wszystkim, co wykracza poza ostrożną grę — drętwieniu, drżeniu, utrzymującym się marznięciu —, ocena należy do fachowych rąk, nie do dalszej gry.\n\nNa śniegu poruszasz się jak po zamarzniętym jeziorze: spokojnymi, pewnymi krokami, z okiem na śliskie miejsca. Kto to weźmie sobie do serca, gra pewnie także w bieli.',
  'Pomyśl o grze w zimnie lub na gładkim gruncie: rozgrzałeś się wcześniej dokładnie, czy wszedłeś zimny? Postanów sobie na śnieg dać rozgrzewce więcej czasu, ubrać się na warstwy, utrzymywać się między wymianami w cieple i grać krótkimi, pewnymi krokami. I uświadom sobie: przy znakach ostrzegawczych jak drętwienie czy utrzymujące się marznięcie przerwać jest mądrzej niż grać dalej — ocena należy wtedy do fachowych rąk.',
  'Beachminton — gra na piasku',
  'Beachminton to crossminton na plaży — na piasku, przeważnie w upale i słońcu. ICO prowadzi go jako format Fun Series; według przepisów pozostaje tą samą grą. Szczególne jest połączenie trzech warunków, które pojedynczo już znasz: miękkie podłoże, upał i oślepienie.\n\nPiasek jest rdzeniem. Jest miękki i nierówny, hamuje każdy krok i odbiera ci twardą krawędź odbicia, do której przywykłeś w hali. Jak przy grze na różnych podłożach znaczy to: szeroka, stabilna postawa, krótsze drogi i wolniejsze odbicie. Szybkie, eksplozywne zrywy kosztują w piasku dużo siły i niewiele dają — rozkładasz drogi mądrzej. Boso czy w odpowiednim bucie to kwestia gustu i zależy od piasku i podłoża.\n\nUpał jest drugim czynnikiem. Tu obowiązuje rama zdrowotna z rozdziału plenerowego bez zmian: traktować znaki ostrzegawcze jak zawroty głowy czy silne wyczerpanie poważnie, spędzać przerwy w cieniu, rozkładać siły. Aplikacja nie daje ci przy tym zaleceń co do picia ani obciążenia; przy utrzymującym się złym samopoczuciu porada fachowa jest właściwym adresem.\n\nDo tego dochodzi słońce. Na otwartej plaży stoi często wysoko i jasno, a wysokie piłki mogą cię oślepić — radzenie sobie jest takie samo jak przy module plenerowym o oślepieniu: wcześnie przechwycić, lekko obrócić głowę, stronę oślepienia zostawić przeciwnikowi. A boisko na miękkim piasku zabezpiecza się śledziami, żeby oznaczenie trzymało.\n\nPlaża jest jak miękki dywan, który połyka każdy krok. Kto ją zna, stąpa krócej i stabilniej — i oszczędza siły na piłki, które się liczą.',
  'Pomyśl o grze w piasku lub w pełnym słońcu: próbowałeś sprintować jak w hali i traciłeś przez to wcześnie siły? Postanów sobie na plażę grać szerszą postawą i krótszymi drogami, rozkładać siły w upale i spędzać przerwy w cieniu. I przenieś radzenie sobie z oślepieniem z gry plenerowej: wysokie piłki wcześnie przechwytywać, zamiast patrzeć w słońce.',
  'Blackminton — gra w ciemności',
  'Blackminton to crossminton nocą — ta sama gra w ciemności, od zmierzchu po świt. W przepisach nic się nie zmienia; całe odstępstwo leży w świetle i w twojej percepcji. To czyni Blackminton skrajnym przypadkiem tematu światła i widoczności, który napocząłeś już przy grze pod słońce.\n\nSą dwa stopnie rozbudowy. W prostym grasz Night Speederem — pociskiem z przezroczystą nakładką, w którą wciska się Speedlight, światło chemiczne podobne do tych używanych przy wędkowaniu. Świeci około trzech godzin i nie jest w zestawie; kilka świecących taśm na ciele pomaga dodatkowo. W bardziej rozbudowanym stopniu zestaw z czarnym światłem rozświetla pole, sprzęt i odzież przez materiały fluorescencyjne.\n\nDecydującą różnicą jest percepcja. W ciemności brakuje ci niemal wszystkich znanych punktów oparcia: speeder to punkt świetlny bez rozpoznawalnego położenia lotu, rama i dłoń przeciwnika pozostają niewidoczne, a granice pola się rozmywają. Zamiast czytać z wielu sygnałów, polegasz na tym jednym niezawodnym: torze świecącego punktu. Właśnie w tym tkwi urok — Blackminton szkoli czytanie toru lotu, które w jasności pozostaje ukryte pod nawałem wrażeń.\n\nPonieważ wczesne znaki z postawy przeciwnika odpadają, wczesne przyjmowanie robi się trudniejsze, a zwód przez przygotowanie traci na skuteczności. Kierujesz całą uwagę na punkt świetlny i wyprowadzasz punkt kontaktu z jego toru.\n\nWskazówka bezpieczeństwa należy do tego: przy ograniczonej widoczności spada percepcja głębi, lądowania i skróty robią się mniej pewne. Graj na wolnej, dobrze uprzątniętej powierzchni, zdławcie tempo wobec światła dziennego i nie podejmuj ryzyka dla piłki, której ledwie widzisz.\n\nW ciemności cała gra kurczy się do jednego świecącego punktu — jak robaczek świętojański w nocy, za którym podąża twój wzrok. Kto nauczył się ufać temu punktowi, widzi nagle wyraźniej niż w jasnym rojowisku.',
  {
    titel: 'Podążać za punktem świetlnym',
    ziel: 'Wyostrzyć percepcję przy słabym świetle na tor lotu świecącego speedera — pewnie i z kontrolowanym tempem.',
    schritte: [
      'Wybierz wolną, dobrze uprzątniętą powierzchnię i przyciemniaj światło stopniowo (zmierzch lub zaciemniony pokój), zamiast zaczynać od razu w zupełnej ciemności.',
      'Graj Night Speederem luźno na podania i skieruj wzrok wyłącznie na punkt świetlny — czytaj jego tor, zamiast szukać ramy lub dłoni przeciwnika.',
      'Cofnij świadomie tempo i przechwytuj speedera raczej wcześnie, gdy tylko rozpoznasz jego tor.',
      'Zwiększaj ciemność dalej dopiero, gdy potrafisz pewnie podążać za punktem świetlnym i pewnie poruszać się po powierzchni.',
    ],
    steigerung: 'Skracaj stopniowo czas, którego potrzebujesz, by odczytać tor, i graj płaskie, szybsze piłki — zawsze tylko na tyle, na ile pewnie potrafisz podążać za punktem.',
    selbstkontrolle: 'Czy podążasz za punktem świetlnym spokojnie wzrokiem, czy szukasz znanych sygnałów, których w ciemności brak? Czy twoje tempo pozostaje kontrolowane, a postawa pewna? Kto ufa torowi punktu, trafia także w ciemności.',
    abschluss: 'Blackminton robi ze speedera punkt świetlny, a z gry szkołę percepcji. Kto podąża za torem lotu i trzyma tempo w garści, gra pewnie przez całą noc.',
  },
];

const r1 = insertPl('data/bausteine.outdoor-thema.json', OUTDOOR);
const r2 = insertPl('data/bausteine.spielmodi.json', SPIELMODI);
console.log(`Ring 11 pl: outdoor ${r1.knoten} + spielmodi ${r2.knoten} = ${r1.knoten + r2.knoten} Knoten.`);
